### ISSUE TITLE
Add acceptance test for doi manuscript pdf service

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#1004]
# What? 

The pass-ui interaction usage of the DOI service which returns available pdfs should have an acceptance test.

# Why?

We missed updating the calls to the doi service for CSRF protection by the ui because of a lack of testing.

# How?

# Acceptance Criteria 

A dedicated acceptance test.

# Related Issues

**Comment by rpoet-jh** [comment]
@markpatton Does this test cover the case? https://github.com/eclipse-pass/pass-acceptance-testing/blob/776d26909ea1be4366b342214985ce5a750936b9/tests/dashboardTests.js#L26

**Comment by rpoet-jh** [comment]
@markpatton or maybe you are referring to the Files step where the calls to the DOI service are made for `manuscript`?

**Comment by rpoet-jh** [comment]
I also wanted to confirm a doubt I have.  I ran a test locally using pass-docker.  I entered DOI `10.1039/c7an01256j`.  I got to the Files step, and I see this request being made `http://localhost:8080/doi/manuscript?doi=10.1039/c7an01256j`, and it returns:

```

    {
        "url": "https://europepmc.org/articles/pmc6759371?pdf=render",
        "repositoryLabel": "PubMed Central - Europe PMC",
        "type": "application/pdf",
        "source": "Unpaywall",
        "name": "pmc6759371?pdf=render",
        "isBest": true
    },
    {
        "url": null,
        "repositoryLabel": null,
        "type": "application/pdf",
        "source": "Unpaywall",
        "name": null,
        "isBest": false
    }
]
```

Based on the code I see in the UI, I think the UI should show the `pmc6759371?pdf=render` manuscript PDF, but it displays this message instead: `We could not find any existing open access copies for your manuscript/article. Please upload your own copy.`

**Comment by markpatton** [comment]
@rpoet-jh Right, I was referring the Files step in particular. I also have observed the same behavior of the service not seeming to work. I had meant to make a separate ticket.
