### ISSUE TITLE
Bootstrap css not loading in pass-ui production build

### ISSUE THREAD

**Issue by rpoet-jh** [eclipse-pass/main#1027]
The production build has a few layout issues.  Identified issue is how the bootstrap 5 css needs to be loaded.

**Comment by jaredgalanis** [comment]
This actually not a loading of bootstrap 5 issue after all. It is that coreUI, which is a fork of bootstrap, wasn't loading (and neither was bootstrap directly), so we were missing styles. Then it turned that loading bootstrap directly conflicts with coreUI and also was not needed.
