### ISSUE TITLE
404 produces Whitelabel Error Page with stacktrace

### ISSUE THREAD

**Issue by rpoet-jh** [eclipse-pass/main#1062]
# Environment 
PROD

# Date/time occurred

2024-10-09 10:30a

# Description

Typing an invalid path on PASS produces the default Whitelabel Error Page with stacktrace.

# Steps to Reproduce

Log into https://app.pass.jhu.edu/
In the browser address bar, type https://app.pass.jhu.edu/foobar
You'll see the Whitelabel Error Page with stacktrace

# Expected Results

A standard error page should be returned for invalid paths without stacktrace.  Note that if the path has /app, then it is good, this is just an issue when /app is not in the path.

# Actual Results

Default error page is returned which contains stacktrace which is not recommended.

# Evidence

# Estimated Severity

Major

**Comment by rpoet-jh** [comment]
`server.error.whitelabel.enabled=false` has been set in jhu stage and prod to disable whitelabel error page.  Now error page looks like:

![Image](https://github.com/user-attachments/assets/85d410a0-9d1a-4970-b6f0-305cb6161dcb)

We should configure a more "user friendly" error page.

**Comment by markpatton** [comment]
When /app/ is in the path, then the error page is handled by pass-ui. Otherwise it is handled by pass-core and we can add whatever default error page we want.
