### ISSUE TITLE
Update links in release template to new documentation

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#1093]
# What? 

The release issue template has links to the old documentation location.

# Why?

Links should not be broken.

# How?

# Acceptance Criteria 

No broken links in template.

# Related Issues

**Comment by tsande16** [comment]
This is a duplicate of [1056](https://github.com/orgs/eclipse-pass/projects/4/views/2?pane=issue&itemId=81630910&issue=eclipse-pass%7Cmain%7C1056)

**Comment by markpatton** [comment]
@tsande16 Good catch.
