### ISSUE TITLE
REQUEST: baseline bootstrap utility

### ISSUE THREAD

**Issue by derekbelrose** [eclipse-pass/main#121]
As we build a new environment, it would be nice to be able to bootstrap a baseline fedora repository with no data from COEUS or NIHMS.

As far as I can tell, the only containers that are not populated by this are policies, repositories, and alcs.  There may be more, but I'm not aware of them.

This is also going to be important for any new instances of PASS that we host such as MIT or Harvard.

**Comment by htpvu** [comment]
@derekbelrose To determine what should go into a baseline repo and what shouldn't, could you say more about the distinction you're making between COEUS & NIHMS data vs other?
