### ISSUE TITLE
Fedora returns HTML payload when ember requested compacted JSON-LD, causing things to barf

### ISSUE THREAD

**Issue by htpvu** [eclipse-pass/main#143]
sometimes when a submission in PASS is trying to load, user encounter this message: 
<img width="1417" alt="Screen Shot 2020-06-09 at 12 20 47 AM" src="https://user-images.githubusercontent.com/11050142/84173032-b76e9180-aa4a-11ea-89fd-a04fc0a99a76.png">

This behavior has not been observed  when using PASS in incognito mode.

some digging by ESM revealed that in some cases where a browser cache had become "ditry", Fedora will return HTML payload, in spite of compacted JSON-LD content type being requested.  see the attached .har file.
[pass.jhu.edu.txt](https://github.com/OA-PASS/general-issues/files/4753374/pass.jhu.edu.txt)

Or see the below screenshots: 

![image (5)](https://user-images.githubusercontent.com/11050142/84173474-55625c00-aa4b-11ea-9387-9632ef560d17.png)
![image (6)](https://user-images.githubusercontent.com/11050142/84173481-572c1f80-aa4b-11ea-8df1-e12f250e8735.png)

What can we do to make sure Fedora doesn't behave this way. We can't ask users to clear cache when using PASS

**Comment by markpatton** [comment]
I had a thought that maybe the response wasn't setting the Vary header and the cache was returning the wrong request. But that would require a previous request for a different content type. In any case the Vary header is set in responses.
