### ISSUE TITLE
Migrate assets image from birkland's private repo

### ISSUE THREAD

**Issue by htpvu** [eclipse-pass/main#152]
i'm not sure where this assets image currently live specifically. But i can find out if you dont already have this information. 

here is some notes related to assets image in case it could provide some more details https://docs.google.com/document/d/1FRemPPFheDjjipjfsSYcZ7kwVOn6XUGf0iQuTqPfS0U/edit

**Comment by markpatton** [comment]
Right now the image is in docker hub and referenced in docker-compose files in at least pass-docker and pass-ember as  `birkland/assets:2019-04-08_3.4@sha256:7ec44bd52d7cf635ad05a3f509cf7439e187b7768b8a05abae81b49744ec9d5f`.

I believe it should be moved to github packages as per the plan discussed here: https://docs.google.com/document/d/13RQR7sKIhkUFpljkypiY5AYmMgeaM1tSYJAyt0APxgk/edit?usp=sharing.

Doing the upload to github packages is simple after the access token stuff is done, we just need to decide on a naming convention for the assets image.

**Comment by markpatton** [comment]
Done
