### ISSUE TITLE
Update PostGRES driver for PASS

### ISSUE THREAD

**Issue by htpvu** [eclipse-pass/main#153]
Prompted by the impending version upgrade for PostGRES, as described here https://jhulibraries.atlassian.net/browse/OPS-2087, we have looked into the impact of the upgrade. 

Latest assessment is that we need to update the JBDC driver for PostGRES to the latest version in order to support the new PostGRES version. 

This ticket cover the work to make the driver upgrade. and see through its deployment to the 4 PASS cloud instances.

**Comment by jrmartino** [comment]
What seems to be happening is this: the fcrepo image in pass=docker is built based on a fcrepo 4.7.5 war wile from maven central. This version of fcrepo has postgresql jar version 9.4.1211, and this is the version of the jar which is preent in the running fcrepo container (webapps/fcrepo/WEB-INF/lib/postgresql-9.4.1211.jar/ What we will need to do is choose a way to update this jar in the fcrepo image, and then release a new version of the image,  Modeshape does not seem to be involved in this.

**Comment by jrmartino** [comment]
A pull request is in here: https://github.com/OA-PASS/pass-docker/pull/258

**Comment by bbranan** [comment]
- PR merged on 3/15/22
- Deployment to 3 environments completed on 3/22/22: https://jhulibraries.atlassian.net/browse/OPS-2130
