### ISSUE TITLE
Update contact info on static pages 

### ISSUE THREAD

**Issue by htpvu** [eclipse-pass/main#154]
Update contact info on PASS static pages as described in the below screenshot
Contact Us page:

![Screen Shot 2022-01-27 at 1 05 56 PM](https://user-images.githubusercontent.com/11050142/151422154-a0947e1a-d627-40de-8086-cf36abbe38b9.png)

FAQ page:
![Screen Shot 2022-01-27 at 1 05 44 PM](https://user-images.githubusercontent.com/11050142/151422162-3a9e9f7b-cad0-4143-8696-1cdc2004f60e.png)
.

**Comment by jaredgalanis** [comment]
@htpvu this has successfully been deployed to test

**Comment by jaredgalanis** [comment]
Should we go to prod or wait until issues around duplicates are resolved?
