### ISSUE TITLE
produce a list of PASS repos to be moved to Eclipse GH org

### ISSUE THREAD

**Issue by htpvu** [eclipse-pass/main#166]
Determine which code repositories will move to EF and approach (e.g. archive) for those that will not be migrated

**Comment by bbranan** [comment]
The determination of which code repositories to move to EF is listed in this spreadsheet: https://docs.google.com/spreadsheets/d/1Zz0GQy64Sj0-LJjSGd63hMcqJ8LJVe1WLskUg8Bh5_8/edit#gid=0. See the "Should be included in ownership transfer" column.
