### ISSUE TITLE
Look into enabling UI development in the clouds

### ISSUE THREAD

**Issue by htpvu** [eclipse-pass/main#168]
Setup continuous deployment to a test environment
Make it easy for UI developers to directly use this test environment instead of relying on complex local setup.

@markpatton could you fill in the details for this ticket please?

**Comment by markpatton** [comment]
Initial approach is to see if ember can be run locally and everything else run in pass-docker. If that works, the docker stack could be put in the cloud.

**Comment by aforward** [comment]
@jaredgalanis / @markpatton I use an ubuntu cloud server (managed with bash scripts to install the necessary components) so we could look into moving those scripts into a Dockerfile and then having a setup like

Build the image (possibly built and availble within GH registry)

```
docker build -t pass-ui-dev .
```

Run the image (note that mapping to the current project)

```
docker run -v "$PWD":/usr/app -it --entrypoint bash pass-ui-dev)
```

And within the docker file we have the pass-ui in a VOLUME

```
VOLUME /usr/app
```

**Comment by jaredgalanis** [comment]
Closing in favor of https://github.com/eclipse-pass/main/issues/245 and https://github.com/eclipse-pass/main/issues/246.
