### ISSUE TITLE
Create deployment plan for PASS within Eclipse infrastructure

### ISSUE THREAD

**Issue by htpvu** [eclipse-pass/main#174]
Create a written deployment strategy for all required PASS components using Eclipse infrastructure

Use JHU PASS deployment as reference:
https://github.com/jhu-sheridan-libraries/pass-terraform/
https://github.com/jhu-sheridan-libraries/pass-terraform/blob/master/docs/architecture.png

Definition of done:

- A written plan in [main/docs](https://github.com/eclipse-pass/main/tree/main/docs) for how each PASS application component will be built and deployed.

Requires ticket #170

**Comment by aforward** [comment]
Updates are being pushed to a `174-pipeline-documentation` branch

In particular, I migrated the architecture from the pass-terraform and the phase 1 docs
https://github.com/eclipse-pass/main/blob/174-pipeline-documentation/docs/architecture.md

I continue to work on the pipeline (was based on "proposed" repo migrations, but will be updated based on actual migrated repos into this organization).
https://github.com/eclipse-pass/main/blob/174-pipeline-documentation/docs/pipeline

**Comment by aforward** [comment]
Some good docs here
https://github.com/eclipse-pass/main/issues/152

Namely
https://docs.google.com/document/d/1FRemPPFheDjjipjfsSYcZ7kwVOn6XUGf0iQuTqPfS0U/edit

**Comment by aforward** [comment]
We have this repo for managing EF infra
https://gitlab.eclipse.org/eclipsefdn/it/infra/eclipse-pass/

As much as possible this will be (and has been) shared within this project, for example https://github.com/eclipse-pass/main/pull/284
