### ISSUE TITLE
Update codebase to pull image from GHCR

### ISSUE THREAD

**Issue by htpvu** [eclipse-pass/main#175]
With the CI/CD work, we are likely to move to push our docker images to GH container registry, in effort to move away from using DockerHub. 

Once the build pipeline is able to push images to GHCR, this ticket covers the work to update relevant docker-compose files to pull images from the GHCR rather than DockerHub

**Comment by jabrah** [comment]
Need to ensure that Docker images in the GHCR are accessible without GH credentials, but assuming they are, it would make sense to start transitioning now with our new demo deploys, having our legacy code stay in Docker Hub and publishing images from the new codebase to GHCR
