### ISSUE TITLE
Create and mock any integration points or data required by PASS to operate in a Sandbox environment

### ISSUE THREAD

**Issue by htpvu** [eclipse-pass/main#177]
With the goal of a Sandbox PASS for demonstration purpose, mock and create necessary integration point and data to enable PASS to operate. 

THis will likely become an epic, with multiple integration point and mock datasets to be created. 

A follow up work from  #176

**Comment by bbranan** [comment]
Closing as complete. Mocks have been created. List can be found here: https://github.com/eclipse-pass/pass-ui/blob/main/mirage/config.js

Action to create sample data for Sandbox is being addressed in #361
