### ISSUE TITLE
Review all GH issues in the OA-PASS gh Org 

### ISSUE THREAD

**Issue by htpvu** [eclipse-pass/main#185]
Review to determine which issues are still relevant. Close the obsolete ones. identify ones that needs to be moved over. 

record assessment in this spreadsheet https://docs.google.com/spreadsheets/d/1Zz0GQy64Sj0-LJjSGd63hMcqJ8LJVe1WLskUg8Bh5_8/edit#gid=0

**Comment by bbranan** [comment]
Actions remaining:
- Review all identified tickets and close any that are no longer relevant
- Determine if remaining tickets will stay where they are after repo transfer or is they will be moved to the main repo

**Comment by jabrah** [comment]
Tickets related to the Harvard Pilot effort are now closed

**Comment by jabrah** [comment]
Went through the old tickets with @jaredgalanis earlier and closed a couple more tickets
