### ISSUE TITLE
Look for and review any GH wikis that exist in this organization

### ISSUE THREAD

**Issue by htpvu** [eclipse-pass/main#186]
Report assessment in this spreadsheet https://docs.google.com/spreadsheets/d/1Zz0GQy64Sj0-LJjSGd63hMcqJ8LJVe1WLskUg8Bh5_8/edit#gid=0

**Comment by bbranan** [comment]
This review has been completed. The only wiki identified was: https://github.com/OA-PASS/pass-ui/wiki.
