### ISSUE TITLE
Remove or replace Gentona font - requirement from EF IP review

### ISSUE THREAD

**Issue by htpvu** [eclipse-pass/main#187]
It seems EF IP review team takes issue with the Gentona font we use. Please run a few options for dealing with this by the team, then implement necessary changes. 

> We have completed a preliminary review of the code package and have identified
> two files related to the Gentona font that are licensed under the MyFonts EULA.
> These font files are not open source and may not be redistributed by Eclipse.
> Please review and advise if these files can be removed/replaced with an open
> source alternative. If changes are required, please attach a revised code
> package.
> 
> PASS_Archive/pass-offline-docker/files/fonts/gentona.css
> 
> PASS_Archive/pass-ui-static/fonts/gentona.css

**Comment by jabrah** [comment]
I have a PR to be reviewed in each of the two repos called out in this ticket. I've removed the fonts in question and went with standard web safe fonts. The look and feel of the application is impacted somewhat, but we can make tweaks down the road.

I don't see any mention of it in this ticket, but if we need to be concerned with the non-open source fonts being present in our Docker images, then I'll have to modify the `pass-docker` repo and create a new image that doesn't include the fonts.

**Comment by bbranan** [comment]
@jabrah if there is an update in the `pass-docker` repo that is necessary to make it consistent with these changes, please create a PR there as well. I'm not sure that a new docker image would be needed immediately though. This ticket is primarily about cleaning up the codebase prior to the move to EF-PASS. We don't need to get these changes into the deployed system just yet.

**Comment by jabrah** [comment]
The PRs are now merged - so the fonts are no longer present on the tip of the respective repos' `master` branches. What are the next steps to re-submit for IP review, to move this ticket forward?

**Comment by bbranan** [comment]
I've made a note on the [IP review ticket](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23943) that this work is done. There is no need to resubmit. Once the PR for `pass-docker` is merged, this issue can be closed.

**Comment by jabrah** [comment]
The PR to `pass-docker` is now merged. The Docker images referenced in that repo should no longer include the flagged font files
