### ISSUE TITLE
Epic - Recreate PASS projects written in Go in Java

### ISSUE THREAD

**Issue by bbranan** [eclipse-pass/main#194]
In order to harmonize the language requirements in the PASS project, this task is to create a Java equivalent of each project component currently written in Go that will replace the Go version. To the extent that the rewrite also allows the Java version to be simpler and/or more efficient, that is encouraged.

Current PASS repos utilizing Go:

- pass-dupe-checker
  - 26 go files
  - 7633 lines of code
- pass-download-service
  - 15 go files
  - 2782 lines of code
- pass-metadata-schemas
  - 31 go files
  - 1324 lines of code
- pass-policy-service
  - 30 go files
  - 3666 lines of code
- pass-tools
  - 17 go files
  - 1433 lines of code

An independent issue should be created and linked here for each repo in the list above.

**Comment by jrmartino** [comment]
Links for individual project issues
#202 
#203
#204
#205
#206
