### ISSUE TITLE
Develop or adopt a code style guide and engage tooling to enforce it across all repos

### ISSUE THREAD

**Issue by bbranan** [eclipse-pass/main#195]
Examples of Java code style guides and enforcement tooling:
- [DuraSpace](https://github.com/duraspace/codestyle)
- [DSpace](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide)

**Comment by jrmartino** [comment]
also interesting: https://google.github.io/styleguide/javaguide.html

**Comment by bbranan** [comment]
Another example: https://github.com/spring-projects/spring-framework/wiki/Code-Style

**Comment by jabrah** [comment]
JS only: `pass-ui` runs ESLint with the automated tests. The repo uses a [customized linting ruleset](https://github.com/OA-PASS/pass-ui/blob/main/.eslintrc.js#L21) based on the [Airbnb JS style guide](https://airbnb.io/javascript/). We currently do not have the settings to enforce linting locally, but instead will get linting reports when PRs are submitted.

**Comment by jrmartino** [comment]
oracle's take on style:

https://www.oracle.com/technetwork/java/codeconventions-150003.pdf

**Comment by bbranan** [comment]
A benefit of using checkstyle: https://checkstyle.org/ is that the same style xml file can be used in both the IDE and in the Maven builds. The DuraSpace and DSpace references I included in the issue description both use Checkstyle. I'm sure there are other alternatives. We'll want to choose one that allows the style guidelines to be defined in one place and referenced everywhere.

**Comment by jrmartino** [comment]
the duraspace github repo for checkstyle: https://github.com/duraspace/codestyle
i can live with these style details - what does everyone think?

**Comment by markpatton** [comment]
Overall, I like the duraspace guidelines better, but either would work.

**Comment by jrmartino** [comment]
a side issue related to checkstyle - we'd have to use an older (v8) release to be compatible with our current jdk build version, which is already past end of life.  i don't know what the implications are for our deploy environment - but at some point we ought to look into moving to java 17, which has another 4 years of active support and 9 years of security support  ahead of it.  if we were to be able to build and deploy with java 17, we could use the latest stable release of checkstyle (10) as well. one approach might be to base our checkstyle configuration on duraspace's setup, and then edit and maintain our own xml files, compatible with the latest checkstyle version, perhaps placing them in eclipse-pass/main for easy access.

**Comment by jrmartino** [comment]
the group met and decided:

- we will adopt the style used by duraspace, and point to the duraspace configuration xml files instead of maintaining a fork ourselves
- we will use checkstyle version 8.x (x=30 works) while our code base is java 8, and leave open th possibility to ugrade to the current version upon upgrading to java 17
