### ISSUE TITLE
Investigate common integration testing framework

### ISSUE THREAD

**Issue by jrmartino** [eclipse-pass/main#201]
Currently each project has its own way of performing integration testing. This often involves standing up a Docker stack to simulate the production PASS stack. Unfortunately, various projects will have a different set of components, and may be using versions of these components which are different from each other and from prod. 

It might make sense to have a common integration testing framework which each project could access for its integration tests. This should both simplify integration testing and provide greater confidence that the project will behave well in production when integration tests succees.

**Comment by bbranan** [comment]
As part of this, also consider whether integration tests should remain as part of independent projects or be pulled together in an independent project that does nothing but integration testing.

**Comment by markpatton** [comment]
Every Java project that does integration testing with the exception of pass-indexer uses Maven to setup a docker environment. Instead pass-indexer provides a docker-compose.yml. That docker-compose.yml setup could be moved into Maven.

**Comment by markpatton** [comment]
For discussion: https://docs.google.com/document/d/1Yp-cBKfNCHqRLcsZQvn4SNyIu7DrSL183v0_cuDzqsc/edit?usp=sharing

**Comment by bbranan** [comment]
Based on discussion of Mark's document (linked above), the team decided to back off on rebuilding the IT structure and focus instead on larger project architecture considerations, particularly the Fedora replacement work. These changes are likely to have a big impact on how ITs are built and executed. This ticket should be revisited soon after the repository replacement work has completed.

**Comment by dkriethof** [comment]
post 1.0

**Comment by dkriethof** [comment]
no longer needed
