### ISSUE TITLE
Port refactored pass-policy-service to pass-core

### ISSUE THREAD

**Issue by jrmartino** [eclipse-pass/main#205]

**Comment by jrmartino** [comment]
Part of epic #194

**Comment by markpatton** [comment]
See https://github.com/eclipse-pass/pass-policy-service/tree/205-java-impl for the refactored code

**Comment by jrmartino** [comment]
Changes in the code have been made to accommodate the switch to Long from URI for PassEntityIDs, and the Policy repositories field containing a collection of Repositories instear of just their IDs. Changes also made to move from Elide from Fedora, but there is still something wrong with the test setup - lots of NPEs related to this I think, haven't found the cause yet. Hoping it's something simple which I have missed.

**Comment by jrmartino** [comment]
Unit tests pass, but integration tests need to be completes to verify that the translation to Java faithfully preserved the rewuired functionality. This is proceeding, but many cases still need to be checked.
