### ISSUE TITLE
Refactor loading of UI config to enable asset fingerprinting

### ISSUE THREAD

**Issue by jabrah** [eclipse-pass/main#207]
The current way the UI reads some of its configuration is loaded and added to the rendered application does not allow us to do asset fingerprinting, which is a best practice and generally nice to have to ensure end users don't get obsolete cached versions of assets. We should refactor how certain configuration values are loaded into the application to enable this feature.

https://github.com/OA-PASS/pass-ui/blob/main/app/services/app-static-config.js

**Comment by dkriethof** [comment]
Tech debt, post 1.0.0

**Comment by dkriethof** [comment]
dupe #608
