### ISSUE TITLE
Eclipse IP review for Data Conservancy repos

### ISSUE THREAD

**Issue by bbranan** [eclipse-pass/main#208]
Initiate and see through to completion the Intellectual Property review with Eclipse that is required prior to transitioning the two repositories listed below from the Data Conservancy organization.

| Repo | Link |
| ---- | ---- |
| pass-fcrepo-jms | https://github.com/DataConservancy/pass-fcrepo-jms |
| pass-fcrepo-jsonld | https://github.com/DataConservancy/pass-fcrepo-jsonld |

**Comment by jabrah** [comment]
New CQ created to get the ball rolling:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24088

**Comment by jabrah** [comment]
As per [comment #3](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=24088#c3), the IP review was approved and marked as resolved

**Comment by bbranan** [comment]
Closing, next step will be in #219
