### ISSUE TITLE
Ensure issues added to the main repo are also added to the project board

### ISSUE THREAD

**Issue by bbranan** [eclipse-pass/main#210]
Issues [added to the main project](https://github.com/eclipse-pass/main/issues) should be added to the [Eclipse PASS project board](https://github.com/orgs/eclipse-pass/projects/4) with Status `New`.

So far the following PRs have been opened and merged in relation to this issue:
* https://github.com/eclipse-pass/main/pull/190
* https://github.com/eclipse-pass/main/pull/199

Latest error:
* https://github.com/eclipse-pass/main/runs/6183083389

**Comment by grant-mcs** [comment]
The current problem is caused by GitHub API returning an empty set when querying for list of projects in `eclipse-pass` org.

As an example, this query returns an empty array (same happens when authorization is added to the query):

    curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/eclipse-pass/projects

I'm looking into why this might be happening for this specific query (other queries are successful). Alternatively, I'll look for a way to discover the project ID through the website (the ID is what is needed for other queries).

**Comment by grant-mcs** [comment]
There is now a new project in eclipse-pass ("webmaster test project" at https://github.com/orgs/eclipse-pass/projects/5) and it *is* being returned by the query so the problem with our primary project not being returned must be due to how it's configured.

**Comment by bbranan** [comment]
I believe the distinction is that the "Eclipse PASS" project (with ID 4) is a "project (beta)" (https://github.com/orgs/eclipse-pass/projects?type=beta) rather than the traditional "project" like the "webmaster test project". I haven't been able to find any docs for a REST API for the beta projects; I suspect that endpoint doesn't exist: https://github.com/github/feedback/discussions/5589. There is a GraphQL API: https://docs.github.com/en/issues/trying-out-the-new-projects-experience/using-the-api-to-manage-projects which should work, though it feels like overkill for this use case.

**Comment by grant-mcs** [comment]
Automatically assigning issues added to the project to the `New` status is already in place within the project workflows (see screenshot) so do we want to pursue using GraphQL to add new issues to the project or should users simply choose the project when they're creating the issue? @bbranan 

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/22599622/166501726-d656ec23-7563-46a3-abcf-fc71304134fc.png">

**Comment by bbranan** [comment]
As discussed today's sprint call, we can make a point to add new issues to the project on creation. The workflow created as part of this ticket can be removed. We can always come back to this is there's a need to automate further.

**Comment by grant-mcs** [comment]
The no-longer-needed workflow has been removed.
