### ISSUE TITLE
Need to update locator id type constants used by grant loader

### ISSUE THREAD

**Issue by jrmartino** [eclipse-pass/main#213]
in version 4.5 of ShibAuthUserProvider in pass-authz-core,  we had:

    /** Employee ID Identifier type */
    public static final String EMPLOYEE_ID_TYPE = "employeeid";

    /** hopkins id identifier type */
    public static final String HOPKINS_ID_TYPE = "hopkinsid";

    /** JHED id type */
    public static final String JHED_ID_TYPE = "jhed";

    These agreed with usage in the grant loader:

    private static final String EMPLOYEE_ID_TYPE = "employeeid";
    private static final String HOPKINS_ID_TYPE = "hopkinsid";
    private static final String JHED_ID_TYPE = "jhed";

In tag 5.0 these values  changed to 
  /** Employee ID Identifier type */
    public static final String EMPLOYEE_ID_TYPE = "employeeid";

    /** hopkins id identifier type */
    public static final String HOPKINS_ID_TYPE = "unique-id";

    /** JHED id type */
    public static final String JHED_ID_TYPE = "eppn";

It appears that these values are used in forming locatorIds to be used in finding existing users in Fedora. However, if the TYPEs don't match what is on the locatorId lists, then matches will not be found - currently, it appears that only the employee ID is useful for the user service being able to locate a user created by the grant loader. This needs to be looked into and corrected.

**Comment by jrmartino** [comment]
this is related to pass-authz issues 90 and 91
https://github.com/eclipse-pass/pass-authz/issues/90  (already merged)
https://github.com/eclipse-pass/pass-authz/issues/91 (still open)

**Comment by jrmartino** [comment]
affects #213

**Comment by markpatton** [comment]
Constants in `pass-grant-loader/pass-grant-data/src/main/java/org/eclipse/pass/support/grant/data/JhuPassUpdater.java`. Also will need to update test data.
