### ISSUE TITLE
Add an initial GitHub Actions workflow to each PASS repo

### ISSUE THREAD

**Issue by bbranan** [eclipse-pass/main#215]
Use the GitHub Actions workflow templates in https://github.com/eclipse-pass/playground to add a workflow to each repository in the eclipse-pass organization to perform a build and run unit tests. This workflow should be executed at least on each pull request.

Definition of done:
- Each repo in https://github.com/orgs/eclipse-pass/repositories has a Github Actions workflow configured to perform at least a simple build and test process when a PR is opened

**Comment by jgara** [comment]
- Added a "workaround" for the parent POM not being published yet -- in pass "main", `mvn install` to the cache
- I have PRs for:
-- eclipse-pass/pass-deposit-services
-- eclipse-pass/pass-doi-service

**Comment by jgara** [comment]
Current status:

- [x] main
- [ ] modeshape
- [x] pass-authz
- [ ] pass-data-model
- [x] pass-deposit-services
- [ ] pass-docker
- [ ] pass-docker-mailserver
- [x] pass-doi-service
- [ ] pass-download-service (Go)
- [ ] pass-dupe-checker (Go)
- [ ] pass-ember-adapter
- [x] pass-fcrepo-jms
- [x] pass-fcrepo-jsonld
- [x] pass-fcrepo-module-auth-rbacl
- [x] pass-grant-loader
- [x] pass-indexer
- [x] pass-indexer-checker
- [x]  pass-java-client
- [x] pass-journal-loader
- [x] pass-messaging-support
- [ ] pass-metadata-schemas (Go)
- [x] pass-nihms-loader
- [x] pass-notification-services
- [x] pass-package-providers
- [ ] pass-policy-service (Go)
- [ ] pass-ui (Ember)
- [ ] pass-ui-public

**Comment by jgara** [comment]
Remaining: 
- [ ] modeshape
- [ ] pass-data-model
- [ ] pass-docker
- [ ] pass-docker-mailserver
- [ ] pass-download-service (Go)
- [ ] pass-dupe-checker (Go)
- [x] pass-ember-adapter (Andrew already added; Awaiting Jared's review)
- [ ] pass-metadata-schemas (Go)
- [ ] pass-policy-service (Go)
- [ ] pass-ui (Ember)
- [ ] pass-ui-public

**Comment by jgara** [comment]
- Opened https://github.com/eclipse-pass/main/issues/263 for `pass-dupe-checker`. 
- Noted missing Unit Tests for `pass-download-service` in pipeline doc (https://github.com/eclipse-pass/main/blob/main/docs/deploy/pipeline.md).

**Comment by jgara** [comment]
Change any instances of Java 14 -> 11

**Comment by jgara** [comment]
- Collapse called GH Actions scripts (e.g. `tests-unit.yml` & `tests-integration.yml`) into single file (`ci.yml`)
- Furthermore, for maven projects, consider eliminating `mvn test` since this build phase is included in `mvn verify`
