### ISSUE TITLE
Perform code base move for Data Conservancy repos

### ISSUE THREAD

**Issue by bbranan** [eclipse-pass/main#219]
Follow up to #208. Now that the IP review is complete, open a ticket with Eclipse (similar to https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1221) to transition the two Data Conservancy repos to eclipse-pass

Repo | Link
-- | --
pass-fcrepo-jms | https://github.com/DataConservancy/pass-fcrepo-jms
pass-fcrepo-jsonld | https://github.com/DataConservancy/pass-fcrepo-jsonld

**Comment by jabrah** [comment]
A ticket has been created in the Eclipse Helpdesk to handle this https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1267

However, I don't have the proper permissions to add the `eclipsewebmaster` user to these repos so they can do the transfer. Currently, Bill, Mark, Jeff (and Jason) are able to do this.

Once this user is added, I was to update the Helpdesk ticket letting them know they had proper permissions to proceed.

**Comment by bbranan** [comment]
I added `eclipsewebmaster` as admin to the two repos and made a note of this in the Eclipse ticket.
