### ISSUE TITLE
Create parent project for PASS code repositories

### ISSUE THREAD

**Issue by jrmartino** [eclipse-pass/main#220]
Some concerns will be common to all PASS code repositories. This ticket is for creating a parent project for PASS repos to eventually  handle things like code style management and chscking dependencies

**Comment by bbranan** [comment]
The parent POM should fit fairly naturally in the `main` repo.

**Comment by jabrah** [comment]
There is likely plenty of things we can consolidate in this parent POM, should we focus the scope of this ticket to the handling of code styles, or pursue other thigs like consolidating dependencies, properties, etc?

**Comment by bbranan** [comment]
@jabrah I'd be inclined to keep this first round of updates scoped to code style, just to avoid the inevitable rabbit trails. Getting all the repos updated to match the code style preferences will be a big enough job to start. That said, we should start collecting a list of other things to consider consolidating or bringing into consistency, like those you brought up. (One that's on my list is a dependency convergence check.) If you agree, please create a new ticket as a place to capture this list.

**Comment by jabrah** [comment]
Current skeleton POM: https://github.com/eclipse-pass/main/tree/220-parent-pom
