### ISSUE TITLE
Need to sync data model usage of pass-docker

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#231]
PASS in production is using data model 3.4.
In pass-docker, some components are using 3.4 such as deposit services and some are using 3.5 such as the authz user service bundled into the fcrepo image.
The different beteween 3.4 and 3.5 was the change in the affiliation field of User from a string to an array of strings.
PASS Java based components which use pass-java-client may fail if they try to access an object from a different data model due to the strong typing introduced by the client. In particular the user service will create a User object which submissions will reference thus causing deposits to fail.
The data model version of a java components support depends on their pass client version. So for pass-docker image of a docker component you have to determine which version of pass-java-client it uses. This is why a number of components started adding data model versions to their versions

Definition of Done:
1. All Java application components are using the latest version of the Java client, which is using version 3.5 of the data model
2. Docker images have been updated to make use of the latest Java application versions

**Comment by bbranan** [comment]
Decision made on 6/14/2022 sprint call to stick with ensuring consistent use of data model 3.4 across all of PASS for now.
