### ISSUE TITLE
Configure all Maven/Java repos to push artifacts to Central via Sonatype

### ISSUE THREAD

**Issue by bbranan** [eclipse-pass/main#234]
Due to the fact that the [GitHub Package Registry requires a GitHub PAT to download maven artifacts](https://github.community/t/download-from-github-package-registry-without-authentication/14407), we're going to use [Sonatype](https://oss.sonatype.org/) for publishing Maven artifacts.

This task is to configure all PASS repos that use Maven to publish to Sonatype.

Definition of Done:
* For each PASS repo using Maven for builds, the current project version set in the POM includes "-SNAPSHOT"
* For each PASS repo using Maven for builds, running `mvn deploy` will result in publishing artifacts to Sonatype
* A SNAPSHOT version of all PASS artifacts have been pushed to Sonatype
* A follow-on issue has been created to update GH Actions builds to perform the deploy

**Comment by bbranan** [comment]
One approach to this is to define a maven profile that can be used to indicate that the additional steps required for a release build should be included, like this: https://github.com/duracloud/duracloud/blob/develop/pom.xml#L166. The benefit to this method is that these additional steps aren't run on standard builds, so don't slow down development.

**Comment by jrmartino** [comment]
| claimed | repo | PR (when available) | Current version | Comments | 
| :---: | --- | --- | :--- |
| <ul><li>[] </li></ul> | [pass-indexer](https://github.com/eclipse-pass/pass-main) ||| Parent |
| <ul><li>[] </li></ul> | [pass-indexer](https://github.com/eclipse-pass/pass-indexer) ||||
| <ul><li>[] </li></ul> | [pass-java-client](https://github.com/eclipse-pass/pass-java-client) ||||
| <ul><li>[] </li></ul> | [pass-messaging-support](https://github.com/eclipse-pass/pass-messaging-support) ||||
| <ul><li>[] </li></ul> | [pass-authz](https://github.com/eclipse-pass/pass-authz) ||||
| <ul><li>[] </li></ul> | [pass-nihms-loader](https://github.com/eclipse-pass/pass-nihms-loader) ||||
| <ul><li>[] </li></ul> | [pass-grant-loader](https://github.com/eclipse-pass/pass-grant-loader) ||||
| <ul><li>[] </li></ul> | [pass-journal-loader](https://github.com/eclipse-pass/pass-journal-loader) ||||
| <ul><li>[] </li></ul> | [pass-notification-services](https://github.com/eclipse-pass/pass-notification-services) ||||
| <ul><li>[] </li></ul> | [pass-doi-service](https://github.com/eclipse-pass/pass-doi-service) |||| 
| <ul><li>[] </li></ul> | [pass-package-providers](https://github.com/eclipse-pass/pass-package-providers) ||||
| <ul><li>[] </li></ul> | [pass-deposit-services](https://github.com/eclipse-pass/pass-deposit-services) ||||
| <ul><li>[] </li></ul> | [pass-indexer-checker](https://github.com/eclipse-pass/pass-indexer-checker) ||||
| <ul><li>[] </li></ul> | [pass-fcrepo-jsonld](https://github.com/eclipse-pass/pass-fcrepo-jsonld) ||||
| <ul><li>[] </li></ul> | [pass-fcrepo-jms](https://github.com/eclipse-pass/pass-fcrepo-jms) ||||

**Comment by jrmartino** [comment]
this depends on #236 - once that is done, both tickets will close

**Comment by jrmartino** [comment]
work for this issue was essentiall done in #236
a follow-on issue #280 has been created to update 
 GH Actions guilds to perform deployment of these artifacts
