### ISSUE TITLE
Configure CI builds to publish maven artifacts to Sonatype

### ISSUE THREAD

**Issue by bbranan** [eclipse-pass/main#235]
https://github.com/eclipse-pass/main/issues/234 ensures that all PASS projects using Maven are capable of publishing to Sonatype. This process should be automated to ensure artifacts are published to Sonatype as part of the CI build procedure.

Definition of Done:
* For each PASS repo using Maven, when a PR is merged to main, a CI build will occur to publish the build artifacts to Sonatype.

**Comment by jabrah** [comment]
https://github.com/eclipse-pass/main/issues/432

**Comment by jabrah** [comment]
Should restrict the scope of this ticket to getting the SNAPSHOT publish to work in `pass-core`. New tickets will then need to be created for a few different things:

* Distribute SNAPSHOT action to `main` and `pass-support`
* Create GH action for publishing a full release 
  * Should we have a push-button release on `main` that will step through releasing all artifacts in order? Or have a "release" action for each repo, letting a release manager step through repositories in order and manually release
