### ISSUE TITLE
Update all Maven project groupIds to use org.eclipse.pass

### ISSUE THREAD

**Issue by bbranan** [eclipse-pass/main#236]
As part of the transition to Eclipse PASS, all Maven project groupIds should be updated to use `org.eclipse.pass` as a prefix rather than `org.dataconservancy.pass`

**Comment by jrmartino** [comment]
| repo | PR when available | GroupId updated |
|  [main](https://github.com/eclipse-pass/main)  |   |   | 
|  [pass-indexer](https://github.com/eclipse-pass/pass-indexer)  |   |   | 
|  [pass-java-client](https://github.com/eclipse-pass/pass-java-client)  |   |   | 
|  [pass-messaging-support](https://github.com/eclipse-pass/pass-messaging-support)  |   |   | 
|  [pass-authz](https://github.com/eclipse-pass/pass-authz)  |   |   | 
|  [pass-nihms-loader](https://github.com/eclipse-pass/pass-nihms-loader)  |   |   | 
|  [pass-grant-loader](https://github.com/eclipse-pass/pass-grant-loader)  |   |   | 
|  [pass-journal-loader](https://github.com/eclipse-pass/pass-journal-loader)  |   |   | 
|  [pass-notification-services](https://github.com/eclipse-pass/pass-notification-services)  |   |   | 
|  [pass-doi-service](https://github.com/eclipse-pass/pass-doi-service)  |   |   | 
|  [pass-package-providers](https://github.com/eclipse-pass/pass-package-providers)  |   |   | 
|  [pass-deposit-services](https://github.com/eclipse-pass/pass-deposit-services)  |   |   | 
|  [pass-indexer-checker](https://github.com/eclipse-pass/pass-indexer-checker)  |   |   | 
|  [pass-fcrepo-jsonld](https://github.com/eclipse-pass/pass-fcrepo-jsonld)  |   |   | 
|  [pass-fcrepo-jms](https://github.com/eclipse-pass/pass-fcrepo-jms)  |   |   |

**Comment by jrmartino** [comment]
almost done here, need to get a PR in for package providers - then will merge everything once reviewed

**Comment by jrmartino** [comment]
all repositories have now been updated
