### ISSUE TITLE
Select system metrics and capture approach

### ISSUE THREAD

**Issue by bbranan** [eclipse-pass/main#239]
1. Determine which system metrics are most important for operation of the PASS system. What will tell us if the system is operating properly or failing?
2. Determine the method we'd like to use for capturing metrics based on the outputs needed (graphs, alerts, etc)
  Examples: (1) Ensure log statements are well-defined and capture metrics via a logging system like Cloudwatch Logs. (2) Push data to ElasticSearch and use Kibana for display.
3. Create follow-on tickets to capture metrics and enable any necessary displays or alerts

**Comment by dkriethof** [comment]
post 1.0.0

**Comment by rpoet-jh** [comment]
An example of number 3 would be to monitor the deposit-service cloudwatch logs for Deposit errors and send notifications if we see more than x number for a time period.

**Comment by rpoet-jh** [comment]
The following has been set up in AWS PASS PROD for monitoring:

DB alert on cpu utilization - to detect high load on database
	- average DB cpu util is greater than 75% for more than an hour

ALB alert on average response time - to detect general slowness in app
	- average higher than 20 seconds over 15 minutes

ALB alert on unhealthy targets - to detect EC2 is not healthy
	- average over 15 minutes, greater than 0

Log metric created looking for %ERROR% in the following logs.  If more than one error is found in 15 minutes, an alert will be sent:
Alarm on errors in deposit logs
Alarm on errors in notification logs
Alarm on errors in pass-core logs

Alerts that are triggered send an email to pass@jh.edu

**Comment by rpoet-jh** [comment]
For the monitoring, I have created a synthetic canary monitor in aws cloudwatch.  This is a basic heartbeat script that calls https://app.pass.jhu.edu/ and ensures a response code between 200 and 499 is returned (the login page returns with a 403).  This will tell us if our app is down within 15 minutes.  Email is sent to [pass@jh.edu](mailto:pass@jh.edu).

This is a pretty neat feature in aws cloudwatch.  This script is written in javascript, so we could make this monitor more advanced if needed at some point in the future.

**Comment by rpoet-jh** [comment]
I enabled access logs on the public alb in PASS PROD, and created an athena database named alb_db.  It has a table in it named alb_logs.  It can be queried with SQL using the athena query editor

**Comment by rpoet-jh** [comment]
I have created a dashboard in the AWS PASS PROD account: https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards/dashboard/prod-pass?start=PT24H&end=null

It shows the number of Submission POSTed (looking at POST requests to /data/submissions), the Submission and Deposit Message count, and any error in the logs in cloudwatch.  You can set the timerange of the data using the filters at the top like other AWS UIs.
