### ISSUE TITLE
Ensure all Java logging is occurring through SLF4J and Logback

### ISSUE THREAD

**Issue by bbranan** [eclipse-pass/main#240]
Most of the Java projects in PASS use SLF4J in combination with Logback to handle logging. This task is to ensure that all projects use this common framework and ensure all transitive dependencies do as well. If this isn't done, then some application logging may be lost. Using a consistent framework also ensures that when shipping logs to external services, the logs are found in the expected places and the formatting is consistent.

**Comment by bbranan** [comment]
One option to ensure that no dependencies (including transitive dependencies) use other logging frameworks is to add the `maven-enforcer-plugin` to the parent pom and use it to ban specific dependencies. For example, see: https://github.com/duracloud/duracloud/blob/develop/pom.xml#L468. This is done in combination with SLF4J's shims (e.g. jcl-over-slf4j and log4j-over-slf4j) to capture logs from other frameworks and route them through SLF4J.

**Comment by jabrah** [comment]
Just a point of interest, looks like similar changes has been made in select PASS projects, the example can be utilized to consolidate implementations in the project POM. Example: https://github.com/eclipse-pass/pass-java-client/blob/main/pom.xml#L366-L382

**Comment by jabrah** [comment]
Adding the `maven-enforcer-plugin` with "normal" configuration fails in several places due to dependency convergence errors. May disable this check for now to focus on the logging dependencies

**Comment by bbranan** [comment]
Disabling the dependency convergence test for now is fine. Enabling that test is part of #243

**Comment by jabrah** [comment]
|  | repo | PR  | notes |
| --- | --- | --- | --- |
| <ul><li>[ ] </li></ul> |  pass-java-client | https://github.com/eclipse-pass/pass-java-client/pull/176 |  |
| <ul><li>[ ] </li></ul> | pass-authz |  |  |
| <ul><li>[ ] </li></ul> | pass-fcrepo-module-auth-rbacl |  |  |
| <ul><li>[ ] </li></ul> | pass-messaging-support |  |  |
| <ul><li>[ ] </li></ul> | pass-indexer |  |  |
| <ul><li>[ ] </li></ul> | pass-indexer-checker |  |  |
| <ul><li>[ ] </li></ul> | pass-grant-loader |  |  |
| <ul><li>[ ] </li></ul> | pass-doi-service |  |  |
| <ul><li>[ ] </li></ul> | pass-nihms-loader |  |  |
| <ul><li>[ ] </li></ul> | pass-fcrepo-jsonld |  |  |
| <ul><li>[ ] </li></ul> | pass-journal-loader |  |  |
| <ul><li>[ ] </li></ul> | pass-package-providers |  |  |
| <ul><li>[ ] </li></ul> | pass-fcrepo-jms |  |  |
| <ul><li>[ ] </li></ul> | pass-notification-services |  |  |
| <ul><li>[ ] </li></ul> | pass-deposit-services |  |  |
| ❌ | modeshape |  | Forked repo, ignore |
