### ISSUE TITLE
Ensure all Java repos can build and run using Java 11 

### ISSUE THREAD

**Issue by bbranan** [eclipse-pass/main#241]
Definition of Done:
* All PASS components in Java will build and run properly using Java 11 ([the previous LTS version](https://www.oracle.com/java/technologies/java-se-support-roadmap.html))
* A follow-on issue has been created to update all PASS components to build and run properly using Java 17 (the most current LTS version)

**Comment by jgara** [comment]
`eclipse-pass/pass-notification-services` required Java 8 for me

**Comment by jabrah** [comment]
## Requires Java 8

* [ ] [`eclipse-pass/pass-notification-services`](https://github.com/eclipse-pass/pass-notification-services)
* [ ] [`eclipse-pass/pass-fcrepo-jsonld`](https://github.com/eclipse-pass/pass-fcrepo-jsonld)

**Comment by jabrah** [comment]
`pass-authz` has a build error in its tests that seems to be related to its use of `powermock` (https://github.com/powermock/powermock/issues/969). It doesn't seem like this dependency has been updated to fix this. This ticket outlines a workaround that will explicitly ignore these Java illegal access exceptions, however the workaround will no longer work as of Java 17, as the arguments used have been removed :-)

Note that a local run with this work around was successful. See the draft PR with the change https://github.com/eclipse-pass/pass-authz/pull/173

Should we add the workaround for now, giving us time to properly rewrite the tests without `powermock`?

**Comment by bbranan** [comment]
I'm ok with this work-around going in so long as:
1. A new ticket is opened to remove the powermock dependency in `pass-authz`
2. Comments are added in the edited `pom.xml` to clarify why the configuration was added (with a link to the issue created in step 1)

**Comment by jabrah** [comment]
Powermock issue created https://github.com/eclipse-pass/main/issues/266
I'll leave any PRs created for this ticket in Draft form until the PRs for updating the GH actions are merged.

**Comment by jabrah** [comment]
Setting the `maven-compiler-plugin` to compile to Java 11:

* https://github.com/eclipse-pass/pass-java-client/pull/181
* https://github.com/eclipse-pass/pass-deposit-services/pull/279

**Comment by markpatton** [comment]
@jabrah I'm on board with targeting Java 11. I don't think there is a need to restrict the compiler.

**Comment by jabrah** [comment]
Follow-on ticket:
