### ISSUE TITLE
Update Java Dependencies and enforce dependency convergence

### ISSUE THREAD

**Issue by bbranan** [eclipse-pass/main#243]
1. Update Java project dependency versions
  a. Start with dependency version concerns called out by dependabot
  b. Consider adding a maven dependency check plugin (like the [OWASP dependency-check](https://owasp.org/www-project-dependency-check/) or similar)
2. Specify shared dependencies in the parent pom within a `<dependencyManagement>` section. Use properties to define the dependency versions.
2. Add a [dependency convergence test](https://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html) to ensure that we're using the same versions of dependencies across the board.

**Comment by markpatton** [comment]
Many integration tests have docker setups which are using old docker images. Those need to be updated.

**Comment by markpatton** [comment]
There seem to be incompatibilities between pass-java-client 0.8.0 and later which use okhttp 4 and projects which use okhttp 3. I suspect we will need to update that dependency to 4 everywhere. 

A symptom is an exception like:
```
	java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1412)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1220)
		at okhttp3.logging.HttpLoggingInterceptor.<init>(HttpLoggingInterceptor.kt)
		at org.dataconservancy.pass.client.fedora.FedoraPassCrudClient.<init>(FedoraPassCrudClient.java:157)
```

**Comment by dkriethof** [comment]
Tech debt, 1.0.0

**Comment by markpatton** [comment]
Can use `mvn dependency:analyze` to find dependency issues. Also could use it to fail the build if problems are found.

**Comment by rpoet-jh** [comment]
We have log4j-to-slf4j which is a bridge dependency to send log4j calls to slf4j, along with log4j-api .  I think we should drop these jar files since I don't think they are needed.  We are using logback as our logging provider, so we shouldn't be using any log4j loggers.  Additionally, because we are using logback as our logging provider, I think we can also drop slf4j-api since it is included in logback-classic.  We can also drop jcl-over-slf4jfrom what I can tell.

**Comment by bbranan** [comment]
In the past, I've found those bridge dependencies to be useful for ensuring logs generated by dependent jars that use log4j or jcl are included in the logback log stream. They also provide implementations of expected classes, so you don't end up with NoClassDefFound exceptions when all of the traditional log4j and jcl dependencies are excluded. If none of the dependencies in the baseline use log4j or jcl this is irrelevant, but if some do, it's worth considering.

**Comment by rpoet-jh** [comment]
@bbranan `If none of the dependencies in the baseline use log4j or jcl this is irrelevant, but if some do, it's worth considering.`. This is a good point.  Before the bridge jar files are removed, we should check that third party jar deps are not using log4j or jcl loggers.
