### ISSUE TITLE
pass-dupe-checker: Unit tests fail and pipeline instructions need to be corrected

### ISSUE THREAD

**Issue by jgara** [eclipse-pass/main#263]
Running `go test` succeeds, but some tests are skipped.
The full pipeline unit tests `go test ./...` fail (see below):

![Image](https://user-images.githubusercontent.com/13679887/173421146-2f0a6307-cc33-4198-a43a-a1747b22e162.png)

**Comment by markpatton** [comment]
Tests should be run just like the other Go unit components. There are no ITs.
