### ISSUE TITLE
Update Docker images to use Java 11

### ISSUE THREAD

**Issue by jabrah** [eclipse-pass/main#270]
Some projects use the `openjdk` base image, which will not work when trying to run code compiled to Java 11. These should be updated to support Java 11. Should be work to support an initial release of PASS.

Projects that are designed to be added to the `fcrepo` Docker image are the exception because there is no migration plan for this at the moment:

* [pass-authz](https://github.com/eclipse-pass/pass-authz) : because this has many submodules, one of which is deployed as a stand alone version, we could have the project target Java 8, as before, then have the stand-alone service target Java 11
* [pass-fcrepo-jms](https://github.com/eclipse-pass/pass-fcrepo-jms)
* [pass-fcrepo-jsonld](https://github.com/eclipse-pass/pass-fcrepo-jsonld)
* [pass-fcrepo-module-auth-rbacl](https://github.com/eclipse-pass/pass-fcrepo-module-auth-rbacl)

**Comment by jabrah** [comment]
Docker images that likely need updating:

pass-indexer
pass-notification-services
pass-doi-service
pass-deposit-services
pass-authz/pass-authz-listener: built from pass-docker/authz/Dockerfile

**Comment by jabrah** [comment]
Testing locally should be sufficient to consider this ticket done, since we'd need a few things done before publishing new images (such as getting GHCR lined up)

**Comment by jabrah** [comment]
the official `openjdk` images seem to be deprecated, so will switch over to image maintained by `eclipse-temurin` such as `eclipse-temurin:11.0.15_10-jre-alpine`

**Comment by jabrah** [comment]
Since this was shelved, we've started moving on a Fedora replacement, which will eliminate or modify some of the above services.

* ~pass-indexer~ (no longer needed)
* pass-notification-services
* pass-doi-service
* pass-deposit-services
* pass-authz (will be modified in refactored backend)
* ~pass-authz/pass-authz-listener: built from pass-docker/authz/Dockerfile~ (must verify) may no longer be needed

**Comment by jabrah** [comment]
the above artifacts are no longer relevant, but our new `pass-core-main` Docker image needs to be updated. The main Dockerhub description in the `openjdk` organization mentions a few alternatives. In order to keep compatibility, we should use a Debian/Ubuntu based image.

`eclipse-temurin:11-jre-jammy` is pinned to Ubuntu 22.04 LTS, whereas the `11-jre` tag can change it's Ubuntu version

**Comment by rpoet-jh** [comment]
@jabrah and @markpatton I saw this issue and see the comment above, note that the base image used in `pass-core-main` has been changed to `eclipse-temurin:17.0.7_7-jre`, which is a multi-arch image covering linux/windows/mac: https://hub.docker.com/layers/library/eclipse-temurin/17.0.7_7-jre/images/sha256-8ba9a9b2420204327d4f2813935bba7063a41672c4b39ed4d42671e3494bec7e?context=explore

If we want to control the ubuntu version, we could switch the base image to [17.0.7_7-jre-jammy](https://hub.docker.com/layers/library/eclipse-temurin/17.0.7_7-jre-jammy/images/sha256-ddf36656dc8920621fddf4928bdcb4b98c0d0e7bc9672f0cea8115c10ad5cbc6?context=explore)

`17.0.7_7-jre-jammy` is also multi-arch including `arm64/v8`, so maybe we should switch to this base image to stick the ubuntu version?  I wouldn't have a windows arch though.

**Comment by jabrah** [comment]
We probably don't have anything that would be impacted by an unpinned version of Ubuntu. It looks like both support `arm64/v8`, as far as I know either would work.

From here, I assume we'll need to modify the building of our Docker images to explicitly support these architectures (e.g. https://dmp.fabric8.io/#build-buildx)
