### ISSUE TITLE
Remove TravisCI configuration

### ISSUE THREAD

**Issue by bbranan** [eclipse-pass/main#275]
Many PASS repos still have a .travis.yml configuration file, which was used for automated build/test when the project was using TravisCI for this purpose. Now that we've transitioned to using GitHub Actions instead, these should be removed.

Note that the .travis.yml file can make reference to other files/scripts, so each should be reviewed to determine if there are other files that were used as part of the TravisCI build, as those additional files would likely also need to be removed.

The only potential lingering value of these files is a reference for building portions of the GitHub Actions workflow. Prior to removal, each file should be reviewed to determine if there is any lingering value as a reference.

**Comment by dkriethof** [comment]
Tech debt

**Comment by markpatton** [comment]
Almost done, I only see it pass-authz.

**Comment by tsande16** [comment]
From scrum: pass-authz is no longer used. Only look at the currently deployed repos and confirm that TravisCI is not in those repos.

**Comment by tsande16** [comment]
**Main**: TravisCI does not exist (although there is mention of it in the pipeline.md - perhaps can be cleaned up during documentation tickets)
**Pass-Core**: TravisCI does not exist
**Pass-Support**: TravisCI does not exist
**Pass-UI**: TravisCI does not exist
**Pass-Auth**: TravisCI does not exist
**Pass-Acceptance-Testing**: TravisCI does not exist
**Pass-Docker**: TravisCI does not exist
