### ISSUE TITLE
Update all project versions to 0.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by bbranan** [eclipse-pass/main#276]
The initial release version of the Eclipse PASS project will be: 0.1.0. To prepare for this release, all Java project versions should be updated to 0.1.0-SNAPSHOT.

**Comment by jrmartino** [comment]
| repo | PR when available | PR reviewed | release deployed |
|---|---|-|-|
|  [main](https://github.com/eclipse-pass/main)  | | | |
|  [pass-java-client](https://github.com/eclipse-pass/pass-java-client)  | | | | 
|  [pass-messaging-support](https://github.com/eclipse-pass/pass-messaging-support)  |  |  | | 
|  [pass-indexer](https://github.com/eclipse-pass/pass-indexer)  | | | | 
|  [pass-nihms-loader](https://github.com/eclipse-pass/pass-nihms-loader)  | | |  | 
|  [pass-grant-loader](https://github.com/eclipse-pass/pass-grant-loader)  | | | | 
|  [pass-journal-loader](https://github.com/eclipse-pass/pass-journal-loader)  | | | | 
|  [pass-notification-services](https://github.com/eclipse-pass/pass-notification-services)  | | | 
|  [pass-doi-service](https://github.com/eclipse-pass/pass-doi-service)  | | | | 
|  [pass-indexer-checker](https://github.com/eclipse-pass/pass-indexer-checker)  | | | |
|  [pass-fcrepo-jsonld](https://github.com/eclipse-pass/pass-fcrepo-jsonld)  | | | |
|  [pass-fcrepo-jms](https://github.com/eclipse-pass/pass-fcrepo-jms)  | | | | 
|  [pass-authz](https://github.com/eclipse-pass/pass-authz)  | | | |
|  [pass-package-providers](https://github.com/eclipse-pass/pass-package-providers)  | | | |
|  [pass-deposit-services](https://github.com/eclipse-pass/pass-deposit-services)   | |  |  |
