### ISSUE TITLE
Release Eclipse PASS version 0.1.0

### ISSUE THREAD

**Issue by bbranan** [eclipse-pass/main#277]
Depends on: #196 #234 #236 #276 

Java projects will be updated to version 0.1.0
Ember projects will be updated to version 0.1.0
Go projects will maintain their existing versions.

Documentation describing the specific steps taken to perform the release should be captured in /docs as part of this work. Keeping this record will make the next steps of automating the release actions easier to accomplish.

**Comment by jrmartino** [comment]
| repo | PR when available | PR reviewed | release deployed |
|---|---|-|-|
|  [main](https://github.com/eclipse-pass/main)  | | | |
|  [pass-java-client](https://github.com/eclipse-pass/pass-java-client)  | | | | 
|  [pass-messaging-support](https://github.com/eclipse-pass/pass-messaging-support)  |  |  | | 
|  [pass-indexer](https://github.com/eclipse-pass/pass-indexer)  | | | | 
|  [pass-nihms-loader](https://github.com/eclipse-pass/pass-nihms-loader)  | | |  | 
|  [pass-grant-loader](https://github.com/eclipse-pass/pass-grant-loader)  | | | | 
|  [pass-journal-loader](https://github.com/eclipse-pass/pass-journal-loader)  | | | | 
|  [pass-notification-services](https://github.com/eclipse-pass/pass-notification-services)  | | | 
|  [pass-doi-service](https://github.com/eclipse-pass/pass-doi-service)  | | | | 
|  [pass-indexer-checker](https://github.com/eclipse-pass/pass-indexer-checker)  | | | |
|  [pass-fcrepo-jsonld](https://github.com/eclipse-pass/pass-fcrepo-jsonld)  | | | |
|  [pass-fcrepo-jms](https://github.com/eclipse-pass/pass-fcrepo-jms)  | | | | 
|  [pass-authz](https://github.com/eclipse-pass/pass-authz)  | | | |
|  [pass-package-providers](https://github.com/eclipse-pass/pass-package-providers)  | | | |
|  [pass-deposit-services](https://github.com/eclipse-pass/pass-deposit-services)   | |  |  |

**Comment by jabrah** [comment]
POM structure convention: https://maven.apache.org/developers/conventions/code.html#pom-code-convention

**Comment by jrmartino** [comment]
looking through the poms, we see the following spread for plugin versions (single entry for a plugin indicates that all uses are the same version. This is the edited output of  

`grep -r plugin | grep version | awk '{print $2}' | sort`

executed in a directory containing all the java repos

<build-helper-maven-plugin.version>3.0.0</build-helper-maven-plugin.version>
<build-helper-maven-plugin.version>3.3.0</build-helper-maven-plugin.version>

<codehaus.build-helper.plugin.version>1.10</codehaus.build-helper.plugin.version>

<docker-maven-plugin.version>0.27.2</docker-maven-plugin.version>
<docker-maven-plugin.version>0.40.1</docker-maven-plugin.version>

<fabric8.docker.maven.plugin.version>0.27.2</fabric8.docker.maven.plugin.version>
<fabric8.docker.maven.plugin.version>0.30.0</fabric8.docker.maven.plugin.version>

<git-commit-plugin.version>2.2.4</git-commit-plugin.version>

<maven-checkstyle-plugin.version>3.1.2</maven-checkstyle-plugin.version>

<maven.compiler.plugin.version>2.5.1</maven.compiler.plugin.version>

<maven-compiler-plugin.version>3.10.1</maven-compiler-plugin.version>

<maven.dependency.plugin.version>3.1.1</maven.dependency.plugin.version>

<maven.deploy.plugin.version>2.8.2</maven.deploy.plugin.version>

<maven-enforcer-plugin.version>3.0.0</maven-enforcer-plugin.version>

<maven.failsafe.plugin.version>2.18.1</maven.failsafe.plugin.version>
<maven-failsafe-plugin.version>2.22.2</maven-failsafe-plugin.version>

<maven-gpg-plugin.version>3.0.1</maven-gpg-plugin.version>
<maven.jar.plugin.version>3.1.2</maven.jar.plugin.version>

<maven-javadoc-plugin.version>3.0.1</maven-javadoc-plugin.version>
<maven.release.plugin.version>2.5.3</maven.release.plugin.version>

<maven.remote-resources.plugin.version>1.5</maven.remote-resources.plugin.version>

<maven.resources.plugin.version>3.0.2</maven.resources.plugin.version>
<maven.resources.plugin.version>3.1.0</maven.resources.plugin.version>

<maven.shade.plugin.version>2.4.3</maven.shade.plugin.version>
<maven.shade.plugin.version>3.2.3</maven.shade.plugin.version>

<maven-source-plugin.version>3.0.1</maven-source-plugin.version>
<maven-source-plugin.version>3.2.1</maven-source-plugin.version>

<maven.surefire.plugin.version>2.18.1</maven.surefire.plugin.version>
<maven.surefire.plugin.version>2.22.2</maven.surefire.plugin.version>

<maven-war-plugin.version>3.2.2</maven-war-plugin.version>
<maven-war-plugin.version>3.2.3</maven-war-plugin.version>

**Comment by jrmartino** [comment]
so, we might try something like this in the main pom, and have all children inherit these versions:

<build-helper-maven-plugin.version>3.3.0</build-helper-maven-plugin.version>
<codehaus.build-helper.plugin.version>1.10</codehaus.build-helper.plugin.version>
<docker-maven-plugin.version>0.40.1</docker-maven-plugin.version>
<fabric8.docker.maven.plugin.version>0.30.0</fabric8.docker.maven.plugin.version>
<git-commit-plugin.version>2.2.4</git-commit-plugin.version>
<maven-checkstyle-plugin.version>3.1.2</maven-checkstyle-plugin.version>
<maven.compiler.plugin.version>2.5.1</maven.compiler.plugin.version>
<maven-compiler-plugin.version>3.10.1</maven-compiler-plugin.version>
<maven.dependency.plugin.version>3.1.1</maven.dependency.plugin.version>
<maven.deploy.plugin.version>2.8.2</maven.deploy.plugin.version>
<maven-enforcer-plugin.version>3.0.0</maven-enforcer-plugin.version>
<maven-failsafe-plugin.version>2.22.2</maven-failsafe-plugin.version>
<maven.jar.plugin.version>3.1.2</maven.jar.plugin.version>
<maven.release.plugin.version>2.5.3</maven.release.plugin.version>
<maven.remote-resources.plugin.version>1.5</maven.remote-resources.plugin.version>
<maven.resources.plugin.version>3.1.0</maven.resources.plugin.version>
<maven.shade.plugin.version>3.2.3</maven.shade.plugin.version>
<maven-source-plugin.version>3.2.1</maven-source-plugin.version>
<maven.surefire.plugin.version>2.22.2</maven.surefire.plugin.version>
<maven-war-plugin.version>3.2.3</maven-war-plugin.version>

**Comment by jabrah** [comment]
Go projects need minor updates to their IT testing environments in order to use the latest `fcrepo` image to test against. I can update these as soon as those changes are accepted

| Repo | PR | Reviewed | Merged | Notes |
| ---- | :----: | :---: | :---: | --- |
| [pass-metadata-schemas](https://github.com/eclipse-pass/pass-metadata-schemas) |  ![CI](https://github.com/eclipse-pass/pass-metadata-schemas/actions/workflows/ci.yml/badge.svg?branch=prep-for-0.1.0) https://github.com/eclipse-pass/pass-metadata-schemas/pull/45 |  |  |
| [pass-download-service](https://github.com/eclipse-pass/pass-download-service) | ![CI](https://github.com/eclipse-pass/pass-download-service/actions/workflows/ci.yml/badge.svg?branch=prep-for-0.1.0) https://github.com/eclipse-pass/pass-download-service/pull/10 |  |  |
| [pass-policy-service](https://github.com/eclipse-pass/pass-policy-service) | ![CI](https://github.com/eclipse-pass/pass-policy-service/actions/workflows/ci.yml/badge.svg?branch=prep-for-0.1.0) https://github.com/eclipse-pass/pass-policy-service/pull/20 |  |  |
