### ISSUE TITLE
Correct straggling pass artifact dependency versions

### ISSUE THREAD

**Issue by jrmartino** [eclipse-pass/main#288]
Versions for dependencies which are PASS artifacts should be configured in the main POM and inherited by child projects. During the release process some versions were not handled in this way, either through omission or something gone awry in teh release process. This issue is to iterate through the child projects and replace a hard-coded reference to a version for PASS dependencies with a reference to the version inherited from the parent pom

**Comment by markpatton** [comment]
Done.
