### ISSUE TITLE
Investigate what would be needed to migrate JHU data after #213 locatorId issue is addressed

### ISSUE THREAD

**Issue by jrmartino** [eclipse-pass/main#289]
Is affected by #213

Once  the above issue is fixed, we will have data in the JHU repo which references old names for locatorIds on User. We need to think about how the various processes which discover and create/update Users need to be changed to agree with the new names for these IDs, and whether data will need migration to avoid Bad Things® like duplicate User objects

**Comment by dkriethof** [comment]
relates to #623
