### ISSUE TITLE
Investigate DSpace deployment in pass-docker for manual testing

### ISSUE THREAD

**Issue by aforward** [eclipse-pass/main#295]
Currently, pass-docker (or pass-app if project is renamed) launches all services. For our dev.eclipse-pass.org site, we might not
necessarily want all this.  In this ticket we will isolate all the desired services that must be run and turn off any optional ones that are not needed (e.g. emails).

This will most likely result in the _current_ DEV configuration being relabelled as `full`, so that we don't lose that for local development / testing purposes separate from our `dev` which is for dev.eclipse-pass.org.

Note that these names (`dev` and `full`) are working titles and might change during implementation.

**Comment by dkriethof** [comment]
@markpatton re-name ticket "Investigate DSpace deployment in pass-docker or manual testing"
