### ISSUE TITLE
Remove Fedora REST API calls from project 

### ISSUE THREAD

**Issue by jrmartino** [eclipse-pass/main#302]
There are calls to the Fedora REST API, and the response from the new image differs from  what it was in the old image.  Basically, the old style response with those headers set when hitting the journals container returned all children plus their attributes. The new image does not return the children's attributes, which the logic requires for the integration tests to pass. I haven't determined yet whether this affects running the loader in a production environment, or whether it is just in the test environment.
At any rate, any project using the REST API needs to be scrubbed, at the very least as part of the getting out of Fedora goal. We could just document this, maybe make a ticket, and leave this alone without putting any more work into it at the moment.

**Comment by markpatton** [comment]
No longer relevant since Fedora has been removed.
