### ISSUE TITLE
Fix pass-ember-adapter tests

### ISSUE THREAD

**Issue by jaredgalanis** [eclipse-pass/main#305]
The tests in `pass-ember-adapter` are currently not passing and should be fixed. 

Note, the tests themselves are failing, but so is the build of the add-on during the unit test CI run.  The build issues seem to be related to this: https://github.com/ember-cli/ember-cli/issues/9235#issuecomment-637697483. 

As a result we might need to consider using yarn for it's resolutions feature or npm v8 for it's overrides feature, OR see if upgrading dependencies could resolve this issue.

It is currently unclear why the tests themselves are failing.

**Comment by jaredgalanis** [comment]
Devoting time to fixing the tests might be deferred until after we've developed a decision and roadmap for Fedora replacement, since it's possible this custom adapter might just go away.

**Comment by bbranan** [comment]
Sounds like completing https://github.com/eclipse-pass/main/issues/209 first, to verify this isn't a dependency issue, would also make sense.

**Comment by jabrah** [comment]
No longer using `pass-ember-adapter`
