### ISSUE TITLE
Consolidate static files with documentation

### ISSUE THREAD

**Issue by bbranan** [eclipse-pass/main#308]
Metadata schemas are served out by github pages in https://github.com/eclipse-pass/pass-metadata-schemas. Transition these and any other static files (e.g. those in pass-data-model) to an appropriate place within [main/docs](https://github.com/eclipse-pass/main/tree/main/docs) and link to them within documentation.

**Comment by markpatton** [comment]
The schemas are now included in pass-core and do not use github pages.
