### ISSUE TITLE
Create simplified login workflow demo

### ISSUE THREAD

**Issue by jabrah** [eclipse-pass/main#310]
For the sake of the demo, we should  be able to work around the SP and User Service work, Possibly simply returning a known user ID.

**Questions:**

* Architecture: Move the `pass-ui` outside of the "secured" realm and have a login page in the application? Update our top level proxy with a dummy login page?
  * Current production system had `pass-ui` sitting behind the shib proxy to ensure all requests are authenticated

**Comment by jaredgalanis** [comment]
This work is complete, and is currently being integrated into a docker-compose environment.
