### ISSUE TITLE
Transform existing assets image to a JSON format suitable for Elide

### ISSUE THREAD

**Issue by jrmartino** [eclipse-pass/main#312]
We have a minimal assets image needing to be dumped as JSON via Elasticsearch, and transformed into a JSON format which can be consumed by Elide

**Comment by markpatton** [comment]
You might think about one tool that dumps the pass objects (not elasticsearch documents) into ndjson format. See http://ndjson.org/. Then another tool which can take that file and use JSON API to create the objects. (It could be done in two passes. One pass creates all the objects without relationships and stores a mapping of the old uris to new ids. Second pass puts in all the relationships using the id mapping.

**Comment by jrmartino** [comment]
i used jq to do the processing - procedure was something like this:

First, increase the result window size to handle all 30477 items:
curl -XPUT "http://localhost:9200/pass/_settings" -d '{ "index" : { "max_result_window" : 45000 } }' -H "Content-Type: application/json"


Next retrieve the assets
curl -X GET "localhost:9200/_search?scroll=1m&pretty" -H 'Content-Type: application/json' -d' > results.json

Pick all the _source elements from the ES results:
 
cat results.json | jq '[ .hits.hits[]._source ]' > hits.json
 
then remove the journalName_suggest elements
 
jq 'del(.. | .journalName_suggest?)' hits.json > hits2.json
 
  
Finally convert to NDJsON
cat hits2.json | jq -c '.[]' > assetsNDJSON.json
