### ISSUE TITLE
Create new eclipse-pass repository to hold artifacts needed to support testing

### ISSUE THREAD

**Issue by jrmartino** [eclipse-pass/main#314]
System testing will require some kind of assets to test against. We have a JSON representation of the PASS objects in the minimal assets image which will serve the purpose, but need a place to store it. It seems that a `pass-test` or `pass-system-test` repository would be a natural place for this.

**Comment by bbranan** [comment]
Eclipse admins will create a new repo for us, just need to open a ticket here: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues

**Comment by jrmartino** [comment]
ticket has been oened 

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1905

**Comment by jrmartino** [comment]
this repository has been created, and now has an assets JSON file in it along with some documentation
