### ISSUE TITLE
Optimize ember builds

### ISSUE THREAD

**Issue by jaredgalanis** [eclipse-pass/main#317]
Ember builds take a very long time at the moment (even relative to other Ember projects). At a minimum, if we can remove our dependency on `node-sass`, this should improve greatly. However, there are probably some other things to do, but it would require a little bit of investigation to assess what those are.

Note that removing node-sass will require removing sass in the project. We don't have a huge reliance on it, so that shouldn't be too big of a lift, but it is worth pointing out.

**Comment by jabrah** [comment]
`node-sass` already removed 
Closing in favor of updating build system #550
