### ISSUE TITLE
Acceptance tests - first steps

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#319]
First steps:

1) Fork the `pass-docker` repository and ensure you can spin up the `pass-docker` stack up and have it running locally. Some instructions are here: https://github.com/eclipse-pass/pass-docker/#instructions. Exercise the application a bit to get familiar with the user interface;

2) Fork the `pass-acceptance-testing` repository and install dependencies. Also, ensure you can run test cafe locally. Some instructions are here: https://testcafe.io/documentation/402635/getting-started;

3) Get familiar with the `The “nice” NIH submission (base case)` scenario described in [this document](https://docs.google.com/document/d/1BpyH2Fzjzkvpe1rVEpb5nx6rLyr-C-jQfFf6Cr7_Ex0/edit#);

4) Get familiar with the `nih-submission-test` that’s already written as an ember acceptance test in `pass-ui`: https://github.com/eclipse-pass/pass-ui/blob/9ae9a7cc87b0ca70728af3f12577351f451b688b/tests/acceptance/nih-submission-test.js#L54-L232;

5) Start on a test written in test cafe that follows this base case.

**Comment by frogfoot9013** [comment]
So far, test to follow base case is successfully carrying out submissions; however, I need some clarification as to at what stage in the base case test the stringified JSON object of metadata (as outlined in the document containing the base case test) is supposed to be at, namely, if it should be found only at the very end, or in Step 6.

**Comment by frogfoot9013** [comment]
https://github.com/eclipse-pass/pass-acceptance-testing/pull/1
