### ISSUE TITLE
Investigate use of manuscript download service

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#321]
Look at how the service is actually used by running PASS locally with pass-docker.
See how the service interacts with the PASS data model.
Compare the existing documentation to what is actually happening.
Produce a report with any finding.
Create a pr to fix glaring inconsistencies in the documentation.

**Comment by maggieolaya** [comment]
I was able to use sandbox to get PASS running. I have been going through the go files, trying to understand how its running (go is new for me as a language)

**Comment by maggieolaya** [comment]
I have an understanding of the structure and flow of the Go files in terms of the manuscript service. I am working on planning out how I will implement this in Java and how to translate the specific components from Go to Java
