### ISSUE TITLE
Investigate use of policy service

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#322]
Look at how the service is actually used by running PASS locally with pass-docker.
See how the service interacts with the PASS data model.
Compare the existing documentation to what is actually happening.
Produce a report with any finding.
Create a pr to fix glaring inconsistencies in the documentation.

**Comment by DeeMac98** [comment]
Experiencing inconsistent issues when running PASS stack locally. Attempting to login to the app on pass.local usually leads to a 503 error, while on other occasions can result in a simple 404. The pass.local/app url is also returning a 404.

**Comment by DeeMac98** [comment]
Examined network requests to policy service from PASS application to understand the service's interaction with both the PASS application, and the PASS data model.
Basic understanding formed of structure of current API implementation.
Documentation appears to be correct so far in terms of the function of the API.
Docker issues have continued to slow progress at times, however when this has been the case I have used the time to examine the code directly to start forming a basic Java implementation.

**Comment by DeeMac98** [comment]
Verified that repositories endpoint is hit.
All documentation therefore appears to be accurate with regard to how the policy service behaves.
