### ISSUE TITLE
Fix enum handling in pass-core

### ISSUE THREAD

**Issue by jabrah** [eclipse-pass/main#326]
Our current version of Elide has a bug in handling enums. A newer version has a fix that we should pull in and implement. We should make sure the UI works with the fix as well, since the string representation in JSON:API is affected

**Comment by markpatton** [comment]
You will need to update elide to 6.1.8.
It is a bit tedious, but you will need a Serde for each enum.
I ended up putting the Converters (db <-> model) inside the classes for better or worse.
The Serdes (model <-> jsonapi) could go there to or in the serde package.

**Comment by jabrah** [comment]
PR against the `import` branch of the elide test repo https://github.com/markpatton/pass-elide-test/pull/3
