### ISSUE TITLE
Implement Elide JSON API service in pass-core

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#328]
- [x] Change path to /data
- [x] Discussed pluralization and decided not to support it for now
- [x] Add back in methods from original Java model and inherit from PassEntity
- [x] Put all Converters in own package
- [x] Put back methods that were stripped out
- [x] Examine attribute types and add Serdes as appropriate
- [x] Must fix code formatting problems
- [x] Maven should build the Docker image
- [x] Copyright statements in code files
- [x] Enable github ci actions
- [x] Docker compose setup should use postgres

**Comment by markpatton** [comment]
Initial version of pass-core with the Elide JSON API service committed: https://github.com/eclipse-pass/pass-core

**Comment by jabrah** [comment]
* No strong opinion, but I'd lean towards `/data`. Do we want or need to have API versioning? For example, the default JSON:API namespace from Elide was `/api/v1`
* +1 for pluralization to follow convention. From the UI perspective, singular version that we have now needs a small customization to work in Ember, but it's a 1-liner, so not a big deal
