### ISSUE TITLE
Port User Service to pass-core

### ISSUE THREAD

**Issue by jaredgalanis** [eclipse-pass/main#334]
The user service will need to be rewritten to communicate with Elide rather than Fedora.

**Comment by jabrah** [comment]
The current user service is responsible for creating new User entities in Fedora (for better or worse) if a user logs in with JHU credentials, but does not yet have a User entity in Fedora. We'll need to either port or rethink this functionality

**Comment by jrmartino** [comment]
this may be another place where the ability to search for a single string on a list is needed (locatorIds)

**Comment by markpatton** [comment]
Should also add authorization rules to at least the object service in order to test.

**Comment by markpatton** [comment]
Had some success modifying the spring security filter chain to wrap a PASS user as a principal and having Elide permission rules interact with it.
