### ISSUE TITLE
Add tests to pass-core

### ISSUE THREAD

**Issue by jabrah** [eclipse-pass/main#335]
There are currently no tests in [`pass-core`](https://github.com/eclipse-pass/pass-core) because it is an early / experimental implementation. Now that things are taking shape and becoming more formalized in this repo, we need reasonable testing

**Comment by markpatton** [comment]
There are old tests of the model that could be reused with some refactoring.
Then for testing jsonapi, an example here might be useful: https://github.com/yahoo/elide-standalone-example/blob/master/src/test/java/example/ExampleTest.java
(Note that this is from the standalone example so the configuration will be different.)

**Comment by jrmartino** [comment]
unit test for the model have been added

https://github.com/eclipse-pass/pass-core/pull/7

**Comment by jrmartino** [comment]
unit tests for model objects merged. no other tests planned at this time.
