### ISSUE TITLE
Design refactored Java metadata schema service

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#337]
The goal is to come up with a design for the service in sufficient detail that others can review and give feedback. To accomplish this goal, create a pull request that shows the design as a minimally implemented application. The application must compile, but does not need to run. The text of the pull request should give a high level explanation of the design and any differences from the original service.

The design should include a plan for how to handle metadata schemas. Figure out why schemas are being served out with GitHub pages and see if there is a reasonable alternative.  Could we instead use the main organization GitHub pages? Or perhaps the service could directly provide them directly?

Design:
- Compare the existing service to how it is actually being used.
  - Are all the features needed?
- Separate business logic from web request handling
- Provide skeleton code that should compile and show the general approach.
- Should either be a Spring Boot application or a Java web application
- Can be a single maven module or a multi-module if justified by the design

Infrastructure:
- Put in GitHub build actions. (Can copy from an existing project like pass-doi-service.)
- Figure out what dependencies you will need and add them to the pom
- Update the README to the extent possible such that it reflects the new design

**Comment by emmau678** [comment]
I have started reading through the go files in order to understand exactly what each of the functions is doing when designing the refactored Java implementation. Adding in comments to document undocumented functions. Annotating parameters and return values as per Javadoc convention. This stage is still ongoing because go is new to me but I’m making good progress with it and have fully investigated 6 files in lib/jsonschema so far.

**Comment by emmau678** [comment]
The skeleton java structure is ready to be reviewed but I'm still unsure of how to handle resources in a jar file in java so this is going to require some more research

**Comment by emmau678** [comment]
Investigated how best to implement the service as a Java web application. Followed the flow of the service and identified the most important actions performed on the schema URIs. Planned out the service at a high level in a flowchart and planned the main classes and functions required.

**Comment by emmau678** [comment]
Reviewed the next iteration of comments on the PR. The build is now passing, all check style issues have been resolved. PR is currently in review. Link: https://github.com/eclipse-pass/pass-metadata-schemas/pull/48

**Comment by markpatton** [comment]
Next stop is implementation!
