### ISSUE TITLE
Design refactored Java policy service

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#340]
The goal is to come up with a design for the service in sufficient detail that others can review and give feedback. To accomplish this goal, create a pull request that shows the design as a minimally implemented application. The application must compile, but does not need to run. The text of the pull request should give a high level explanation of the design and any differences from the original service.

Design:
- Compare the existing service to how it is actually being used.
  - Are all the features needed?
- Separate business logic from web request handling
- Provide skeleton code that should compile and show the general approach.
- Should either be a Spring Boot application or a Java web application
- Can be a single maven module or a multi-module if justified by the design

Infrastructure:
- Put in GitHub build actions. (Can copy from an existing project like pass-doi-service.)
- Figure out what dependencies you will need and add them to the pom
- Update the README to the extent possible such that it reflects the new design

**Comment by DeeMac98** [comment]
Implemented feedback from previous meeting.
Skeleton implemented
Business logic & web request handling separated
GitHub build actions implemented
Basic dependendies implemented
README and documentation updated

https://github.com/eclipse-pass/pass-policy-service/pull/21
