### ISSUE TITLE
Acceptance tests - proxy submission workflow

### ISSUE THREAD

**Issue by jaredgalanis** [eclipse-pass/main#342]
1) become familiar with the proxy submission workflow as implemented in the ember acceptance tests here: https://github.com/eclipse-pass/pass-ui/blob/9ae9a7cc87b0ca70728af3f12577351f451b688b/tests/acceptance/proxy-submission-test.js#L10;

2) become familiar with the proxy submission workflow described in this document: https://docs.google.com/document/d/1b4PXfLurzpHWlSyh-5CoLnjFrM79a87q60OJf7fpoZU/edit;

2) write test(s) in test cafe that exercise the proxy submission workflow.

**Comment by jaredgalanis** [comment]
As discussed in the meeting this morning. Let's add the configuration of timeouts via environment variables as an acceptance criteria for this task.

**Comment by frogfoot9013** [comment]
Draft PR: https://github.com/eclipse-pass/pass-acceptance-testing/pull/2

**Comment by frogfoot9013** [comment]
PR is awaiting feedback for latest changes: https://github.com/eclipse-pass/pass-acceptance-testing/pull/2

**Comment by frogfoot9013** [comment]
PR has been landed, will close if agreed to in standup.
