### ISSUE TITLE
Investigate unification of secrets handling

### ISSUE THREAD

**Issue by jaredgalanis** [eclipse-pass/main#345]
- the certs and keys for the idp / sp were previously brought in via secrets in the docker compose file 
- the auth service currently expects some of these certs / keys to be set directly as environment variables
- investigate --> do we need to make the keys available under docker compose secrets as they were before?

**Comment by dkriethof** [comment]
1.0.0

**Comment by dkriethof** [comment]
@jaredgalanis to review and see if part of this is complete, and update ticket accordingly
