### ISSUE TITLE
File Service

### ISSUE THREAD

**Issue by jabrah** [eclipse-pass/main#350]
Should this be done in `pass-core`? There was an earlier proposal for having an [OCFL](https://ocfl.io/) implementation to handle file data

`pass-ui` has some upload related logic that sets up requests that will need to be removed and mocked for now until we have a real implementation

**Comment by markpatton** [comment]
Yes. This would be part of pass-core. The service should be able to persist to S3. Note that https://github.com/UW-Madison-Library/ocfl-java has S3 support.

**Comment by tsande16** [comment]
A dump of notes from meeting with @markpatton 

Extend integration tests
Write tests do not blow up
Can be run in any order, and can be run with shared storage <- Can be configured with environment variables

- Persist to local file system 
- Persist to S3
- Docker image will be configurable with environment variables
- Everything needed to run service can be configured through environment variables
- Does it take a byte stream and return an opaque URL?
- Call URL get the byte stream back?
- Does it perform delete?
- Does it interact with the file object in the data model? -> Who is responsible for the File Objects? 
- Take a look at the pass data model
- This is a URI on that model to get a byte stream 
- This file service upload does not have to worry
- How does the pass-ui currently works? <- work on this first
- Think about replicating this? Or should we do things differently?
- Follow-up with a discussion with the UI team
- What are the limits of this service
     - File limits? 
     - Error Handling
     - Authorization issues
     - Security concerns?
- File types
     - Setting headers appropriately
- Content type
- Do not need to perform system testing at the moment

**Comment by tsande16** [comment]
Notes from meeting with @jabrah and @jaredgalanis 

- Endpoints:
	- Upload
	- Download (Maybe? - depending on implementation) <- might be a good idea to have a URL that they can access
		- pass on ID as URL parameter, and the download service returns byte stream
	- Delete

Proposed endpoints:
/File/Upload
	-returns identifier to the file entity
/File/UploadMeta
	- POST contains meta info about the file
/File/UploadAll
- Composed of Upload+UploadMeta
/File/Download
/File/Delete

validations in the backend?
- File size
- File type <- for now, no implementation, but add a TODO
- Add a env var blacklist of file types -> e.g. .exe should not be allowed

What is missing now is the authorization layer. User service will be reimplementated.
