### ISSUE TITLE
Capture Demo data set and automate re-applying data after each deployment

### ISSUE THREAD

**Issue by bbranan** [eclipse-pass/main#352]
Data can be loaded into PASS by using a process that takes ndjson from Fedora, transforms it, and submits it through the Elide API.  We want to ensure the PASS demo site always has a fresh data set after new code is deployed, but this flow is cumbersome.

This ticket is to capture the data in PASS after it has been loaded (likely by exporting from Postgres) and automating (using GitHub Actions) the step of putting that data back after each time a new build/deploy process updates the demo site.

**Comment by jabrah** [comment]
In the demo's compose file, there is a `loader` service that issues a single curl command after `pass-core` initializes that batch uploads data from a JSON file with our demo data. This will likely be maintained in some way moving forward for end to end system tests
