### ISSUE TITLE
Investigate content security policy headers

### ISSUE THREAD

**Issue by jaredgalanis** [eclipse-pass/main#353]
When attempting to turn on the helmet package (https://helmetjs.github.io/) for pass-auth we experienced failures to load around misaligned content security policy headers.

It does not appear that any of the web servers (outer proxy or the nginx serving the ember app) are setting CSP headers and this might be the reason for the failures.

Resolving the issue would be something that should be done in advance of using the auth service in a production capacity and optimally would be done in advance of using it in any deployed capacity (demo/test/etc).

**Comment by dkriethof** [comment]
IDP label
