### ISSUE TITLE
Update Publication data model in Elide

### ISSUE THREAD

**Issue by jabrah** [eclipse-pass/main#354]
Specifically the current `publicationAbstract` field, in my opinion, should change to `abstract` unless there is a backend reason to maintain the current name. I believe this field name is an artifact of the old Fedora client, which had intended to be named `abstract` in the JSON-LD serialization

Not sure if this would be a matter of renaming the field in the Java model class, or adjusting the annotation on the field to give it a different name. 

* [old pass-java-client Publication](https://github.com/eclipse-pass/pass-java-client/blob/main/pass-model/src/main/java/org/dataconservancy/pass/model/Publication.java#L38-L39)
* [pass-core/Publication](https://github.com/eclipse-pass/pass-core/blob/main/pass-core-object-service/src/main/java/org/eclipse/pass/object/model/Publication.java#L44)

**Comment by jabrah** [comment]
This would impact pass-core, pass-ui, and the data loaders that deal with publication entities

**Comment by markpatton** [comment]
This can be done by just renaming the field name in Java. I believe there are other fields that are also prefixed by their type. This can be useful in some circumstances, but probably does not matter hugely. For example if doing a global filter having different attribute names let you easily distinguish between the fields on different types.

I'm not opposed, but just note this would be something else that any tools doing migration would have to handle.

**Comment by jabrah** [comment]
Since this change would impact data loaders and possibly other tooling, does @jrmartino have an opinion on this renaming?

**Comment by markpatton** [comment]
Also the documentation in pass-data-model would have to correspondingly be updated. If we decide to do this, we should review all the objects. For example journalName in Journal.

**Comment by jaredgalanis** [comment]
Agree wit

> I'll note that this issue came up because of the difference between the Java field name vs JSON serialization. From the UI perspective this property was seen as `abstract`. If we consider what changes would need to be made if we decide to rename vs if we keep the same name, it seems that doing a rename would require significantly more work than adjusting the UI behavior to match the backend representation (I already have a temp workaround in the UI to get things working while we discuss this issue).

Agreed, I think the discussion began because we didn't want to update the UI if there was an easy way to do this on the backend, but this sounds pretty involved. The changes can stay UI side from my perspective.

**Comment by markpatton** [comment]
@jabrah 

The json API serialization should exactly match what is described in pass-data-model (at least as far as field names) which should also exactly match the Java field names. If that's not the case there are some consistency problems to fix.

**Comment by jabrah** [comment]
The current documentation uses [`Publication.abstract`](https://github.com/eclipse-pass/pass-data-model/blob/main/documentation/Publication.md) where the java client data model uses [`Publication.publicationAbstract`](https://github.com/eclipse-pass/pass-java-client/blob/53d694c6945196d70a401e0bf02fe106f8a96e60/pass-model/src/main/java/org/dataconservancy/pass/model/Publication.java#L39) that appears as `Publication.abstract` in the JSON-LD serialization so there's a bit of a disconnect between the documentation and UI side vs backend / Java side.

We could either update the documentation and adopt the Java representation, or change the Java implementation. It looks to me like updating the documentation and UI will be less work. On the other side, I'd assume that we wouldn't retroactively update the older Fedora implementations, so a Java change could be brought in as services are ported to the new architecture. Plus we don't have permanent data with the new architecture yet (nothing in production), so if we want to update the sql tables, it would be better to do so sooner rather than later.

**Comment by markpatton** [comment]
I think in this case it makes sense to correct the Java so it matches the documentation and the actual JSON-LD.

**Comment by markpatton** [comment]
I tried changing the annotation for publicationAbstract to 
```
@Column(name = "abstract", columnDefinition = "text")
```
But this did not work, it changes the name of the column in the db, but not the attribute in the JSON. There doesn't appear to be anyway to do so, some comments had implied that this approach would work. I'll try asking on the discord.

**Comment by markpatton** [comment]
Agreed that we will use publicationAbstract and update the data model documentation.
