### ISSUE TITLE
Behavior of nightly environment?

### ISSUE THREAD

**Issue by jabrah** [eclipse-pass/main#356]
Should we update `nightly` to pull `:latest` tags, combined with a general policy of releasing new images to `:latest` along side their respective version tags? This would have the effect of decoupling the `nightly` and `demo` deployments so this will depend on our intentions for these environments

**Comment by aforward** [comment]
That was my thinking.

The nightly would know (or be told) about all the latest and greatest, and demo would be manually managed.  The individual yaml compose files would accommodate those changes.
