### ISSUE TITLE
Create Github workflow for pass acceptance tests

### ISSUE THREAD

**Issue by jaredgalanis** [eclipse-pass/main#357]
Create a new Github `workflow.yml` in `pass-docker` that:

- runs on every opened pull request

- is manually triggerable from within the Github UI

- checks out and starts up `pass-docker` (see https://github.com/eclipse-pass/pass-docker/blob/main/.github/workflows/deploy_passnightly.yml)

- checks out and runs pass-acceptance-tests over `pass-docker` (see https://github.com/eclipse-pass/pass-docker/blob/main/.github/workflows/deploy_passnightly.yml)

* Note you might run into issues with permissions that we can help resolve

**Comment by frogfoot9013** [comment]
I've done some initial work on creating the workflow but I do need somewhat more clarification because it has been a while since I've last worked with YAML.

**Comment by jaredgalanis** [comment]
These docs might be helpful: https://docs.github.com/en/actions/using-workflows

**Comment by jaredgalanis** [comment]
@frogfoot9013 I think you should be able to create the yml file in pass-docker and checkout the pass-docker code and then checkout the pass-acceptance repo with some config in the yml file like: https://github.com/actions/checkout#checkout-multiple-repos-side-by-side

For pass-acceptance code, you probably also need to do things like `yarn install`, which you can with https://github.com/actions/setup-node

**Comment by jaredgalanis** [comment]
Also see https://testcafe.io/documentation/402817/guides/continuous-integration/github-actions#example

**Comment by frogfoot9013** [comment]
Awaiting PR to be merged to main: https://github.com/eclipse-pass/pass-docker/pull/287
