### ISSUE TITLE
Investigate use of relative relationship links in JSON:API responses in pass-core

### ISSUE THREAD

**Issue by jaredgalanis** [eclipse-pass/main#358]
Ember Data is using the relationship links provided by pass-core, which are being set by elide as absolute urls, when traversing relationships and this is causing some issues where the protocol is being set as `http` and not `https`. 

It would be ideal if we can tweak elide to force it to provide relative urls in the relationship links.

This may or may not be possible, see an older discussion here:

https://github.com/yahoo/elide/issues/282#issuecomment-229931872

And here: 

https://github.com/yahoo/elide/pull/1445

**Comment by jabrah** [comment]
https://github.com/eclipse-pass/pass-core/blob/main/pass-core-main/src/main/resources/application.yaml#L8

Config added that pulls an environment variable to set the base URL used for these links. Default value in pass-docker is set to `https://pass.local` but needs to be changed
