### ISSUE TITLE
Create a Demo script

### ISSUE THREAD

**Issue by AllenMoore22** [eclipse-pass/main#360]
We need to create a demo script to ensure the overall flow is finalized. This includes possibly creating sample test data to be used.

Notes:
1: What's the minimal amount of data needed?

**Comment by jabrah** [comment]
https://docs.google.com/document/d/1CySMtDsc6n_QNm5kKV_PNRuQX04ootT8VxlPpIbcuR0/edit?usp=sharing

**Comment by jabrah** [comment]
Steps for a "normal" flow through the submission workflow as well as a "proxy" submission (where the submission is prepared by an approved party, then approved and submitted by the PI of the grant.

A couple of TODOs that fell out of this script:
* https://github.com/eclipse-pass/main/issues/372 - some JSON:API filters incorrect, submissions list is too narrow and some filters need to be surrounded by double quotes
* Data should be updated in the sample loader (and later verified in the minimal assets) to match expectations in the acceptance tests (not strictly required by the demo script, but a good idea in general to begin automated testing of the new setup)
