### ISSUE TITLE
Port the Download service to make use of the Elide backend

### ISSUE THREAD

**Issue by bbranan** [eclipse-pass/main#364]

**Comment by markpatton** [comment]
Note that this depends on refactoring the service to Java #203, which a student is working on.

**Comment by jrmartino** [comment]
the file service will take care of this. what the original download service did was not download, but rather look up URLs for pdfs of submissions, from a DOI. this capability will probably be moved into the doi service. the ticket for this is https://github.com/eclipse-pass/main/issues/397
