### ISSUE TITLE
Correctly stop all docker services running on the demo / nightly servers

### ISSUE THREAD

**Issue by aforward** [eclipse-pass/main#367]
As our docker-compose files are churning a bit, let's make our demo / nightly deploys better handle changing services by stopping all running containers instead of relying on `docker-compose down` as the relevant compose files might be significantly different that not all services are indeed stopped.

Here are the two actions
https://github.com/eclipse-pass/pass-docker/blob/main/.github/workflows/deploy_passdemo.yml
https://github.com/eclipse-pass/pass-docker/blob/main/.github/workflows/deploy_passnightly.yml

This is the call that needs be fixed
```
      - name: Stop Existing App
        run: |
          (docker-compose -f eclipse-pass.base.yml -f eclipse-pass.nightly.yml down || true)
```

**Comment by dkriethof** [comment]
Closing. Added #658
