### ISSUE TITLE
Clean up warnings when starting demo system

### ISSUE THREAD

**Issue by aforward** [eclipse-pass/main#369]
When you try to run the demo system (`./demo.sh up`) you will see these warnings

```
WARN[0000] The "METADATA_SCHEMA_URI" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMBER_GIT_BRANCH" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMBER_GIT_REPO" variable is not set. Defaulting to a blank string.
```

Those environment variables should either be set to meaning values or removed if they are no longer needed.

**Comment by springstim** [comment]
I will provide "set if unset or empty envar" syntax (e.g. `"${METADATA_SCHEMA_URI:-}"` ) in the docker compose file for demo.yml ; however, we should probably consider:

- if we should actually be providing real values for these in the .demo_env file (e.g. there are no EMBER_ envars in the .demo_env file)
- if we only want to do this for this specific envars
- if we want to specify exit/error conditions if other envars are missing

**Comment by jabrah** [comment]
Closed with https://github.com/eclipse-pass/pass-docker/pull/281
