### ISSUE TITLE
Configure demo/nightly eclipse-pass.org to correctly load sample data 

### ISSUE THREAD

**Issue by aforward** [eclipse-pass/main#371]
This PR documents how to get a locally running demo system
https://github.com/eclipse-pass/main/pull/370

There is a small problem, in that the _loader_ can only be run **after** `pass-core` is ready.  I am duplicating the manually instructions here.

## Pull Latest Docker Images

This will pull all the latest pass docker images.

```bash
./demo.sh pull
```

## Start Pass

This will start pass in the background

```bash
./demo.sh up -d
```

At this point you will need to watch the logs to wait until the
`pass-core` shows that it has started.  This is something we
are actively working to address.

```bash
./demo.sh logs -f
```

It might take a while, but once the logs _stop_ with the message below
then it is ready to load the base data.

```
[main] [Pass, ] INFO  org.eclipse.pass.main.Main.logStarted - Started Main in 69.863 seconds (JVM running for 79.59)
```

That base data can now be loaded using the following command.

```bash
./demo.sh up loader
```

Here we want to address the dependency so that our demo systems (demo.eclipse-pass.org and nightly.eclipse-pass.org) can properly have the loaders run once ready.

The scripts managing our demo deploys are available here
https://github.com/eclipse-pass/pass-docker/blob/main/.github/workflows/deploy_passdemo.yml
https://github.com/eclipse-pass/pass-docker/blob/main/.github/workflows/deploy_passnightly.yml

Ideally this ticket is resolved once we can log into the demo URLs with `nih-user` / `moo` and see the appropriate demo data.

**Comment by springstim** [comment]
I started on this but @jabrah was already working on a more detailed fix for loader

**Comment by jabrah** [comment]
Prospective fix in this branch that Jared is currently updating, trying to update IDP in deployed instances
https://github.com/eclipse-pass/pass-docker/tree/20221104-misc-updates-and-rebranding
