### ISSUE TITLE
Fix logout bug in pass-auth

### ISSUE THREAD

**Issue by jaredgalanis** [eclipse-pass/main#375]
- we use https://github.com/jaredhanson/passport
- the most recent release of passport.js changed the signature for the logout method as described here: https://medium.com/passportjs/fixing-session-fixation-b2b68619c51d
- unfortunately using this new method signature causes the logout process to hang
- for now we've reverted to `v0.5.3`, but we should update to the latest version and fix whatever issue there is

**Comment by jabrah** [comment]
Need to upgrade Passport versions and check relevance of this issue

**Comment by jaredgalanis** [comment]
Closing due to #903
