### ISSUE TITLE
Implement refactored Java metadata schema service

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#380]
Implementation:
- Service should be fully implemented
- Business logic should separated from HTTP request handling

Documentation
- The README should be up to date with the implementation
- There should be at least some Javadoc for every class
- Generally public methods should have Javadoc
- Documentation should include build and configuration instructions
- Endpoint documentation should include request and response formats, headers, parameters and response codes
- There should be an example of using each endpoint
 
Testing
- There should be unit tests covering the major functionality
- Integration testing will be saved for later

**Comment by emmau678** [comment]
I have started implementing the main functions in the Schema Service, which handles the business logic of the service.

I looked into the PassClient and Repository classes from the PASS code and figured out how I can integrate them into this service.

I also tried a few different methods of reading, manipulating and processing JSON schemas in Java and I think I have figured out a good approach.

My next step is to write unit tests to test the functionality of the code I have written. I aim to do that this week and open a draft PR to build on from there.

**Comment by emmau678** [comment]
I now have the schema dereferencing and merging stages implemented and passing unit tests. I have come across an issue in the sorting stage which I hope to resolve this week.

**Comment by emmau678** [comment]
Extended unit testing for the merge stage to cover all cases and made some improvements to the rest of my code to make it more concise and more efficient. Created draft PR: https://github.com/eclipse-pass/pass-metadata-schemas/pull/49.

**Comment by emmau678** [comment]
**This week's progress:**

- I have addressed the comments on the PR.
- I improved the unit test for dereferencing schemas, using the local schemas in the classpath. This exposed an issue with referencing the same schema as the $ref. I resolved this issue
- I added unit testing for all of the functions in the SchemaFetcher class and successfully debugged some minor issues so they are all passing now.

**Blockers:**

- Running into an issue getting the PASS Client to read in the Repository objects using readResource(). 
  I think the repositories are password protected and I don't have access to them.
  When I try to read them using an instance of PASS Client, it says: Connection refused: no further information.
  This was blocking progress in other areas of the code, so I implemented a temporary fix for now, adding the repositories to the classpath, but this will be changed when I figure out how it should work.

**Comment by emmau678** [comment]
Updated PR with a new commit with improved unit testing and extended functionality. Added functionality into the Service and Servlet classes. https://github.com/eclipse-pass/pass-metadata-schemas/pull/49

**Comment by emmau678** [comment]
Extended unit testing to cover the larger functions: getSchemas(), getMergedSchema() and doPost().
Added exception handling and unit testing of the exception handling.
Updated PR with latest 4 commits.

**Comment by emmau678** [comment]
Implemented a solution to the schema sorting inconsistency issue, so it now gives consistent results every time.
Addressed the outstanding comments on the PR.
Fully functional service with all unit tests passing pushed to GitHub.
