### ISSUE TITLE
Implement refactored Java policy service

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#382]
Implementation:
- Service should be fully implemented
- Business logic should separated from HTTP request handling

Documentation:
- The README should be up to date with the implementation
- There should be at least some Javadoc for every class
- Generally public methods should have Javadoc
- Documentation should include build and configuration instructions
- Endpoint documentation should include request and response formats, headers, parameters and response codes
- There should be an example of using each endpoint

Testing:
-There should be unit tests covering the major functionality
- Integration testing will be saved for later

**Comment by DeeMac98** [comment]
Continuing with Java implementation of refactored Java Policy service.

**Implementation**

- Initial implementaiton of findPolicies() use case.
- Added PolicyRules class to handle resolution of policies (policy.go)
- Initial policy resolution steps.

**Testing**

- Initial junit tests for PolicyServlet and RepositoriesServlet testing endpoints

**Comment by DeeMac98** [comment]
Continuing implementation of findPolicies() use case. Completed some various resolve() methods needed as part of this. 
Now ready to implement some new classes to complete this use case, including Requirements.java, and Conditions.java.
Blockers at the moment are related to association of conditions with a specific Policy.

**Comment by DeeMac98** [comment]
Majority of business logic implemented (needs Unit tests).
Most of the business logic can be re-used for other use cases (ie. findRepositories).

BLOCKER: 
Currently blocked with the final two methods for findPolicies() use case. Methods are "resolveToObject()" and "resolveToObjects()".
In Go implementation, these methods simply receive a string that will either be a URI or a JSON blob. In Java implementation, this method will have to receive a URI. Issue faced is handling either a URI or JSON blob in java implementation.

Also facing issues understanding how conditions are assigned to check relevance of Policies.

**Comment by DeeMac98** [comment]
Completed first use case (findPolicies()). Most business logic can be re-use for other use cases once the initial web requests have been handled appropriately to make use of the existing logic.

Began implementing unit tests covering the main functions in the business logic, with branch coverage for valid and invalid test cases.

Most of the remaining work involves unit testing the business logic, and implementing initial web request handling for other use cases.

**Comment by DeeMac98** [comment]
Refactored current exception handling to better define all exceptions being thrown. Continuing to unit test current functionality as much as I can to verify current implementation. Won't be able to implement full service by EOD.
