### ISSUE TITLE
Properly resolve 404.html and its assets in pass-ui-public

### ISSUE THREAD

**Issue by jaredgalanis** [eclipse-pass/main#398]
Currently when visiting a page that does not exist that the pass-ui-public nginx server serves, assets for the 404.html page are broken as the browser is not redirected and the asset paths are relative and get added to the URL that includes the page that doesn't exist.

We want these assets to resolve properly so that the 404.html page renders in a user-friendly and styled way.

We may need to tweak the nginx config to fix this issue. Perhaps redirecting to the 404.html page entirely, would solve this.

https://github.com/eclipse-pass/pass-ui-public/blob/main/404.html

https://github.com/eclipse-pass/pass-docker/blob/main/static-html/nginx-template.conf

**Comment by jaredgalanis** [comment]
![Image](https://user-images.githubusercontent.com/6305935/205379571-f1bfbc2b-98ea-430b-b22c-642c2b23a1ae.png)

**Comment by jaredgalanis** [comment]
This is what we want it to look like:

![Image](https://user-images.githubusercontent.com/6305935/205379662-4e9c9587-b1f1-4b72-9c5f-48a185f549a2.png)

**Comment by springstim** [comment]
PR https://github.com/eclipse-pass/pass-docker/pull/292

Implemented solution replaces the in-place rendering of the 404.html with a redirect target to top-level 404 handler
