### ISSUE TITLE
Find secure solution for managing IDP secrets

### ISSUE THREAD

**Issue by grant-mcs** [eclipse-pass/main#400]
In the `pass-docker` repo there is a folder called `secrets` containing private keys and certs used by the `idp` and `sp` services. As a short term solution, Jared will be generating and deploying new secrets that can be used in our demo environment.

Long term, we need to consult with Eclipse to discover if there are any generally accepted practices for handling secrets in open source projects and then implement a solution that follows those practices.

**Comment by markpatton** [comment]
Will be taken up by a more general ticket.
