### ISSUE TITLE
Test JHU IDP with demo setup

### ISSUE THREAD

**Issue by jaredgalanis** [eclipse-pass/main#418]

**Comment by jaredgalanis** [comment]
currently blocked on https://github.com/eclipse-pass/main/issues/573

**Comment by dkriethof** [comment]
@jaredgalanis #573 was moved to Done. is this still blocked? if so, do we need to add a ticket to the board to work on to unblock? thanks!

**Comment by jaredgalanis** [comment]
@dkriethof, I think we moved #573 to done with the idea of opening follow on tickets that might come out of the AWS deployment meeting we're having this afternoon. 

There is not a staging instance deployed still, which remains a blocker for this ticket.
