### ISSUE TITLE
Update documentation about how to do a release

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#420]
Only required repositories need to be released.

Repositories to be released: main, pass-core, pass-support, pass-ui, pass-auth, pass-ui-public, pass-docker

**Comment by jabrah** [comment]
* Pass-ui: https://github.com/eclipse-pass/pass-ui/releases/tag/v0.2.0
* Pass-auth: https://github.com/eclipse-pass/pass-auth/releases/tag/v0.2.0

**Comment by markpatton** [comment]
Add information specifying the tag to use for the release so we are consistent across the repositories.

**Comment by markpatton** [comment]
Also should note that the change log is primary place for release notes and should be linked to by the github releases

**Comment by jabrah** [comment]
Would be good if @jrmartino could add some info about new maven CLI arguments we can add to run the release in batch mode to avoid the manual human intervention
