### ISSUE TITLE
Currently acceptance tests may be inconsistent in CI

### ISSUE THREAD

**Issue by jabrah** [eclipse-pass/main#426]
The tests run against PRs currently in `pass-docker` may fail occasionally, but then pass after being rerun. We should at least keep an eye on this and fix where possible.

It may be as simple as increasing some of the test-related timeouts

**Comment by jabrah** [comment]
Also, it looks like part of the Docker stack can hang during initialization. Canceling and rerunning the GH Action will sometimes work around this, but it should investigated

**Comment by jaredgalanis** [comment]
15 successful runs in a row, I think this is fixed by https://github.com/eclipse-pass/pass-acceptance-testing/pull/9.
