### ISSUE TITLE
Set GitHub tags to PASS version

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#433]
Ensure that GitHub tags created for releases are the same as the PASS version.
For example the 0.2.0 release of PASS should have 0.2.0 tags for all repositories.

**Comment by jabrah** [comment]
* Updated [pass-ui:0.2.0](https://github.com/eclipse-pass/pass-ui/releases/tag/0.2.0) 
* Updated [pass-auth:0.2.0](https://github.com/eclipse-pass/pass-auth/releases/tag/0.2.0)

**Comment by jabrah** [comment]
Need to also create a GH release for `pass-acceptance-testing` repo

**Comment by jabrah** [comment]
* Updated [pass-docker:0.2.0](https://github.com/eclipse-pass/pass-docker/releases/tag/0.2.0)

**Comment by markpatton** [comment]
Updated pass-core 0.1.0 0 and 0.2.0 releases to have the same tag as the version number.
