### ISSUE TITLE
Consolidating documentation markdown links between GH dev view and EF eclipse-pass.org/main view

### ISSUE THREAD

**Issue by aforward** [eclipse-pass/main#447]
Our documentation is run through Main.

```
https://github.com/eclipse-pass/main/tree/main/docs
```

When references between pages, absolutes paths work great for `GitHub.com/eclipse-pass/main` view but that will not work as expected in `eclipse-pass.org/main` view.

Let's (as best we can) make both documentation views support links and images properly.

**Comment by aforward** [comment]
An experiment showed that relative paths works great
https://github.com/eclipse-pass/main/pull/444

The main page
https://eclipse-pass.org/main

Can correctly link into
https://eclipse-pass.org/main/docs/dev/

**Comment by aforward** [comment]
Here is the fuller PR under review is
https://github.com/eclipse-pass/main/pull/446

**Comment by dkriethof** [comment]
moving documentation to Gitbook, no longer relevant
