### ISSUE TITLE
Create org level GH secrets for use in GH actions

### ISSUE THREAD

**Issue by jabrah** [eclipse-pass/main#450]
There are a few actions that should run against multiple repositories that will require credentials as GitHub Secrets. We should see about using organization level secrets to prevent duplicated repository-level secrets

`pass-core` has a few repository level secrets at the moment for testing workflows, but they can be removed when organization level secrets are added

**Comment by jabrah** [comment]
Need to determine how to best handle org level secrets, discussed with Andrew

### Some open questions:
* Will Eclipse-OPS own these secrets? For example, do they have an `eclipse-webmaster` account with publishing rights in Sonatype?
* Is it more appropriate to use the personal credentials of a project committer or even project owner (Bill)?
* How would maintenance happen (e.g. updating expired GPG key)?

### Required secrets
* `OSSRH_USERNAME`: username for logging into Sonatype
* `OSSRH_PASSWORD`: password for logging into Sonatype
* `MAVEN_GPG_PASSPHRASE`: passphrase for GPG signing key
* `MAVEN_GPG_KEY`: private key for signing Java artifacts. Needed to push artifacts to Maven Central

### Potentially needed
These are not yet in the GH automations, but could potentially be brought in. the `update-image` automation in `pass-core` does this for nightly updates

* `GH_USER`: a GH user that can perform operations on other eclipse-pass repos (e.g. update a docker-compose file on release)
* `GH_PAT`: auth token for GH_USER for performing these operations

**Comment by aforward** [comment]
I have created a ticket within EF and will reach out with updates as they become available.
https://gitlab.eclipse.org/eclipsefdn/infrazilla/-/issues/991

(the URL is probably not accessible, so more here so that I can recall the URL)

```
## Summary

The Eclipse Open Access PASS team has accounts with

* GitHub (Personal Access Tokens for git automations)
* Sonatype (Maven repo management)
* Maven (java repo management)

We are looking to create organization level secrets to be used with our GitHub Actions, namely


* `OSSRH_USERNAME`: username for logging into Sonatype
* `OSSRH_PASSWORD`: password for logging into Sonatype
* `MAVEN_GPG_PASSPHRASE`: passphrase for GPG signing key
* `MAVEN_GPG_KEY`: private key for signing Java artifacts. Needed to push artifacts to Maven Central
* `GH_USER`: a GH user that can perform operations on other eclipse-pass repos (e.g. update a docker-compose file on release)
* `GH_PAT`: auth token for GH_USER for performing these operations

## Approach

### A - Open Access PASS shares account secrets

We provide Eclipse Foundation with those secrets in a secure manner and they are set at the `eclipse-pass` org level

### B - EF has an account and manages secrets directly

Another approach is that we create an EF account within Sonatype and Maven (you already have access to our GitHub account) and then you manage the secrets directly the team (via our GH Actions) references them based on the environment variables above.
```


Thanks to @jabrah for the walkthrough

**Comment by aforward** [comment]
I checked that pass-docker did not have any repo secrets

```bash
gh secret list --repo eclipse-pass/pass-docker
```

Which returned

```
no secrets found
```

Then I updated an action to show that the secrets were there
https://github.com/eclipse-pass/pass-docker/actions/runs/4544757626/jobs/8011209103

```
- name: Check users available
  run: |
    echo "Using OSSRH_USERNAME ${{ secrets.OSSRH_USERNAME }}"
    echo "Using GH_USER ${{ secrets.GH_USER }}"
    echo "But an unknown secret shows ${{ secrets.GOOP }}"
```          

With the output of

```
Run echo "Using OSSRH_USERNAME ***"
Using OSSRH_USERNAME ***
Using GH_USER ***
But an unknown secret shows 
```

Implying that indeed they are set at the org level.

I didn't try echoing out the actual secrets (just the usernames)

I will keep the `spike/org-secrets` branch around for testing.

**Comment by aforward** [comment]
So we should have

```
OSSRH_USERNAME: username for logging into Sonatype      
OSSRH_PASSWORD: password for logging into Sonatype
MAVEN_GPG_PASSPHRASE: passphrase for GPG signing key
MAVEN_GPG_KEY: private key for signing Java artifacts. Needed to push artifacts to Maven Central
GH_USER: a GH user that can perform operations on other eclipse-pass repos (e.g. update a docker-compose file on release)
GH_PAT: auth token for GH_USER for performing these operations
```

**Comment by aforward** [comment]
Here's the _verification_ should any of the secrets not behave as expected.
https://github.com/eclipse-pass/pass-docker/blob/spike/org-secrets/.github/workflows/deploy_passdemo.yml

**Comment by jabrah** [comment]
Through several test runs of the release workflow in the `main` repo, I was unable to successfully run the action using the organization level credentials. After some messing around, I was only able to get the action to succeed after re-adding my own credentials to the repository, suggesting that there is something off about the values in place.

Error message reported in the action:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:3.0.1:sign (sign-artifacts) on project eclipse-pass-parent:
Unable to decrypt gpg passphrase: org.sonatype.plexus.components.sec.dispatcher.SecDispatcherException: 
java.io.FileNotFoundException
```

I am not entirely sure what the cause of this is, but in order to have a successful run, I re-added my own credentials:

OSSRH_USERNAME
OSSRH_PASSWORD
MAVEN_GPG_KEY
MAVEN_GPG_PASSPHRASE

I imagine that the org level OSSRH_USERNAME and OSSRH_PASSWORD are OK, given the error message, but I re-added these just in case. For each of these, I used Grant's Python tool: [github_secrets.py](https://github.com/eclipse-pass/main/blob/main/tools/github_secrets.py) to update the repository level secrets. The only special care I had to take is for the MAVEN_GPG_KEY: I used a process similar to this to export the private key and update the GH secret:

``` sh
# Export and add GPG key:
gpg --list-secret-keys # Get your private key ID
# /home/user/.gnupg/pubring.kbx  
# -------------------------------  
# sec rsa3072 2022-06-29 [SC] [expires: 2024-06-28]  
# 	<KEY_ID>
# uid [ultimate] Sample User <user@example.com>  
# ssb rsa3072 2022-06-29 [E] [expires: 2024-06-28]

gpg --armor --export-secret-keys <KEY_ID> > secret.txt
python ./tools/github_secrets.py -u <gh_user> -t <gh_pat> -r pass-core -n MAVEN_GPG_KEY -v "$(cat secret.txt)"
```

**Comment by jabrah** [comment]
I should have included where the error was occurring in the actions:
* Workflow log with the error (it's unfortunately proven to be non-trivial to change the log levels, so it's very spammy) : https://github.com/eclipse-pass/main/actions/runs/4556298768/jobs/8036483465 
* `mvn release:perform` is the specific command that will use all of the OSSRH and GPG secrets: https://github.com/eclipse-pass/main/actions/runs/4556298768/workflow#L104

**Comment by jabrah** [comment]
@aforward 
Adding `-DdryRun=true` to the release:perform command _may_ do a side-effect-free run, but from the maven documentation, it's not clear if the GPG secrets would be utilized in a dry run

**Comment by aforward** [comment]
No update on this ticket, as we have a work-around I will give the EF ops team another week to review.

**Comment by cshannon2** [comment]
@aforward have there been updates on the internal EF ops ticket? Also is it possible to setup GitHub Environments where we can define secrets for the two different deployment environments (Demo and Development)?

**Comment by aforward** [comment]
Here this branch purposely has `X` on the env vars to show they are "being used".

<img width="498" alt="Screenshot 2023-09-05 at 14 05 42" src="https://github.com/eclipse-pass/main/assets/48086/c57ddf20-e3f1-4a3b-969b-8c184d3e172f">

**Comment by jabrah** [comment]
Ran a test release after removing repository level secrets that failed to complete.  https://github.com/eclipse-pass/main/actions/runs/6100653559/job/16555422674

Will need to recreate repository level secrets while we can pinpoint the failure mechanism this time. 

I'll check back in with the Sonatype documentation to see if there's anything that we missed

**Comment by aforward** [comment]
@jabrah and I still found issues with the configured org level secrets, so going back to the per-repo workaround and will continue down the otterdog / bit warden approach

**Comment by jabrah** [comment]
org level secrets in place and tested with an alpha release to maven central proved successful. All repo level release secrets cleared out. It's important to note that these release secrets are now managed by Eclipse Ops. If for whatever reason, these secrets fail in the future, we'll need to put in a ticket with Eclipse Ops to fix. If we need an immediate workaround, we'll have to reinstate the repo level secrets. We'll continue to watch development of Otterdog around integration of Bitwarden so that we can swap to credentials that we can manage ourselves down the road.
