### ISSUE TITLE
Create full release GH action

### ISSUE THREAD

**Issue by jabrah** [eclipse-pass/main#452]
Will need to include GPG signing with Maven, can use [Duracloud action](https://github.com/duracloud/duracloud/blob/develop/.github/workflows/ci-build.yml#L44) as reference.

### Questions
* Should we have a single release action in `main` that can perform releases for everything? It would handle the building & publishing of artifacts and Docker images, proper sequencing, etc. This would most likely be a huge GH action. Or it may make more sense to have separate release actions for individual repositories and we'd need a release procedure to describe sequencing for a committer to follow.
* How would such an action (or set of actions) be tested? The main issue would be if there's some bug in the workflow that would somehow results in a bad artifact to be deployed to Maven Central, such an artifact could not be overwritten to be corrected. Maybe have a throwaway version like `0.3.0-test`. Such a throwaway version could be incremented as needed for testing

**Comment by jabrah** [comment]
Probably easiest to create actions for each repository that respond to the creation of releases in GH, then have good documentation about sequencing and procedure

**Comment by bbranan** [comment]
- It may help to list out the set of steps that should occur across repos first, then consider what the triggers should be and what outputs are expected at what points. (Capturing this will also make creating documentation of this process easier.) It would be nice to consolidate the Actions scripts in `main`, just for ease of maintenance, but that doesn't mean there should only be a single Action workflow. Breaking them out into multiple workflows could allow parts of the process to run in parallel. Of course, if the trigger that is needed is only available in the repo where the code lives, that necessitates having the workflows be more distributed.
- What can't be tested with -SNAPSHOT versions could be tested with release candidate versions (e.g. -RC1, -RC2). The release candidate model is [well known in the maven context](https://maven.apache.org/developers/release/maven-core-release.html)

**Comment by jabrah** [comment]
Currently testing/debugging the workflow in fork: [jabrah/pass-core](https://github.com/jabrah/pass-core)

**Comment by jabrah** [comment]
Initial automation merged and used with mixed success in the 0.3.0 release. In the end, I think the automation is OK, but there was something wrong with the GH secrets in pass-core such that Maven wasn't able to correctly read the passphrase for the artifact signing key
