### ISSUE TITLE
Refactor GH actions with reusable actions / workflows

### ISSUE THREAD

**Issue by jabrah** [eclipse-pass/main#467]
We should have one set of actions or workflows maintained in our `main` repo that can be used by other repositories to simplify maintenance. Such workflows and actions are still versioned, but the same actions won't need to be duplicated across code repositories

**Comment by jabrah** [comment]
https://github.com/eclipse-pass/main/pull/595

**Comment by jabrah** [comment]
May be able to separate the Java release workflows that upload release artifacts that the other Java release workflows can then download into the local .m2 repo for local resolution 

https://github.com/actions/upload-artifact
https://github.com/actions/download-artifact

**Comment by jabrah** [comment]
PR https://github.com/eclipse-pass/main/pull/595 has an in-progress attempt at consolidating all PASS releases. Some issues need to be taken care of before this is ready to test:

* `pass-ui`, `pass-auth`, `pass-acceptance-testing`, `pass-docker` release workflows need to be updated to include `on.workflow_call` with appropriate inputs to call the workflows remotely
  * Need to check the behavior of each of these workflows `checkout` step. For example, when calling the pass-ui release workflow, will it checkout `eclipse-pass/pass-ui` or will it checkout `eclipse-pass/main`, since that's the repository that will call the release workflow?

**Comment by dkriethof** [comment]
related to #907
