### ISSUE TITLE
Potential UI tasks

### ISSUE THREAD

**Issue by jabrah** [eclipse-pass/main#487]
Intended to collect a bunch of UI tasks for discussion. Very loose priority ranking, subject to change

### Tasks:
* ~~JS automations: release, deploy, etc~~
* Handling ongoing deprecations (such as Ember5 deprecations): come up with maintenance plan for "rolling" updates
  * At a minimum, we should have a plan for handling this
  * ember-cli-deprecation-workflow (or whatever it's called) can aid to generate a list, instead of only seeing deprecations at build-time
  * ~~Should make sure we're on newer versions of Node, currently on Node 14, which is close to EoL~~
* Server-side pagination - client-side impl
* Moving to JWT-based auth solution
  * Would be able to extract the UI from the Docker environment - development and deployment implications
* Migrating to Typescript: as long as we have a plan, this can be done piecemeal along with other tasks
* General submission (object) handling: we can actually delete objects now
* Embroider (may tie in to handling deprecations): new build system that's not ember-cli
  * Enables true code splitting
* Move from ember-models-table to a more supported library: ember-table
  * ember-table would need custom filter. Has nice API for hiding rows out of DOM - like client side "pagination"
  * ember-models-table provides some nice-to-haves, so we'd need to do some manual refactor
* Refactor Mirage stuff into factories
  * Would help with UI (unit/integration) testing
* Refactor components to be reusable
  * Component library would be awesome - could help with a potential Admin UI
    * Using Storybook would be nice for such a library. Would help greatly with a shared UI design language across PASS apps
  * Could bring in Tailwind at this stage
* Move away from Bootstrap
* Resumable submission workflow
  * Refactored workflow
  * Scope? Would this be arbitrarily resumable for a user? Resumable only during a session? This would impact potential 
* Configuration service
  * Would replace the janky config.json we use to init the app
  * Also touch on multitenancy
* Refactor metadata step to rip out AlpacaJS
  * Do we need to have the complex JSON Schema setup for presenting these dynamic forms (do we even need dynamic forms)?
    * To add a new repo or policy, would need only data change (current JSON Schema service) or code change (static forms) or do we define our own DSL for generating forms that is greatly simplified and roll our own dynamic form generator (or look for a new one)?
  * Not a <1.0.0 task due to amount of planning/design that would be needed

**Comment by jabrah** [comment]
* JS application state management
* Refactor submission workflow to make sense
  * With proper state management, many of the steps could be greatly simplified, since there's a lot of manipulation and logic occurring in each step to reason about submissions

**Comment by jaredgalanis** [comment]
Closing in favor of the tickets broken out individually
