### ISSUE TITLE
Question about how to handle versioning in pass-ui

### ISSUE THREAD

**Issue by jabrah** [eclipse-pass/main#498]
We currently don't have a well established practice for handling versioning in `pass-ui` and other JS projects in PASS. At the moment, we've been bumping the version in `package.json` on release to match the release version, but using the projected next version for Docker images, so the official "release" docker tag doesn't get overwritten. IMO we should keep the project version and Docker tags in sync while also being mindful about not overwriting release tags.

Keeping project version and Docker tag in sync OR using a static Docker tag is preferable from an automation standpoint to avoid any weird logic of determining one version from the other, which is prone to error.

There are a few options we could consider including (but not limited to):

1) Do not sync project version and Docker tag until release.

  We could not publish any versioned Docker tags during development, instead only updating `:latest` or similar. This doesn't address how to handle the project version in `package.json`, but breaks the link between project version and Docker tags so that we could handle the project version any other way we want.

2) Emulate Java version handling:

Standard practice in the Java world is to treat released versions as immutable. They would be cut only at release time, leaving active development to use `-SNAPSHOT` versions, which can be overwritten and updated continuously. If we were to emulate this method in the JS projects, we'd follow Java's release process of version updates. For example, after our `0.3.0` release, `pass-ui`'s version would be set to `0.4.0-SNAPSHOT` and the in development Docker tag would be kept in sync with this version.

Regardless of how the versioning is synced, it should be handled by automations only

**Comment by jaredgalanis** [comment]
John and I chatted and we settled on option #2 now for consistency across the PASS project even if it is not strictly what javascript projects do by convention.
