### ISSUE TITLE
Handle file deletion in the UI 

### ISSUE THREAD

**Issue by jabrah** [eclipse-pass/main#514]
PASS production currently doesn't delete files due to unresolved permissions issues. Now that we have the ported file service integration, we should take a look at this to properly remove files from storage when the user chooses to remove the file from the submission

**Comment by jabrah** [comment]
Need to look at security policies in pass-core to enable this

**Comment by dkriethof** [comment]
post 1.0.0

**Comment by jabrah** [comment]
Some bad UI behavior going on that were overlooked on the initial PR resulting in an unhandled error that boots the user to the login screen. Will submit a new PR to correct
