### ISSUE TITLE
Allow manuscript download endpoint to handle encoded URLs

### ISSUE THREAD

**Issue by jaredgalanis** [eclipse-pass/main#515]
While working on the file service / UI integrations we noticed that sending an encoded URL will cause the manuscript download endpoint to throw an error. 

It's expected that some DOI's will have characters that need encoding (like a `/`), so we should make this endpoint behave accordingly.

**Comment by markpatton** [comment]
I'm a bit confused by this. The client must encode every parameter in a query string. When the code handling the request gets the value of a parameter, it is automatically decoded. There is not much to get wrong. Sometimes there can be issues with double encoding or decoding.

Could a http request which causes the unexpected error be provided?

**Comment by jabrah** [comment]
The ticket above was a bit of a red herring. Based on manual testing with the Unpaywall API that this service was accessing, it seemed to behave as if it was sending a bad URL to the API. After more debugging, it was determined that this service was overeager in accessing some JSON properties in the Unpaywall API response, addressed in this PR by simply checking for the presence of the property before accessing it: 

https://github.com/eclipse-pass/pass-core/pull/39
