### ISSUE TITLE
Investigate the handling of method A journals

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#526]
Author is warned, but can still select PMC. Does deposit services handle that case.

**Comment by jabrah** [comment]
* What is the outcome of not handling this case?
  * PMC could have a duplicate submission for a paper - one from the journal, one from PASS
* How is it handled and displayed in the UI?
* Should this case be handled:
  * In the UI?
  * In /repositories endpoint?
    * Could not include PMC in this case, forcing it to not be added to the submission
  * In deposit services?
    * Could recognized a Method A journal in use on for a submission and not submit to PMC

**Comment by dkriethof** [comment]
@markpatton is this one still relevant, or can I close?

**Comment by markpatton** [comment]
So what happens is that the UI doesn't let you submit to the PMC if a method A journal is selected.
