### ISSUE TITLE
pass-doi-service update for new RSQL hasMember functionality

### ISSUE THREAD

**Issue by jrmartino** [eclipse-pass/main#527]
The `find(...) `method in the ElideConnector class in the DOI service scores journals in the database when deciding which existing Journal object (if any) in the database is the best match for the one pulled in from CrossRef.  We use issns as part of this scoring, but lacked the ability to query for a string against a list of strings. Now that this functionality has been added, we can uncomment code starting around line 240 and correct the RSQL call in that ` if (!issns.isEmpty()) `block to `RSQL.hasMember`. This will include issns in the scoring.

While we are in the project, we should also correct the package name in passs-core/main/java/test from doi.service to simply doi.

**Comment by jrmartino** [comment]
this should take about 3 minutes :-)

**Comment by markpatton** [comment]
Done.
