### ISSUE TITLE
Release 0.5.0 - Issues and fixes

### ISSUE THREAD

**Issue by tsande16** [eclipse-pass/main#533]
This issue documents the issues that arose during the 0.5.0 and the fixes that can be made to further improve the Pass Release Automation. 

GH Release automation worked for all releases except for Pass Docker, which needed to be released manually. 

It failed during the acceptance testing of the workflow:

`Run docker compose up -d --no-build --quiet-pull --pull never`
....
`Error response from daemon: no such image: ghcr.io/eclipse-pass/pass-ui:0.5.0: No such image: ghcr.io/eclipse-pass/pass-ui:0.5.0`
`Error: Process completed with exit code 1.`

Context for the failed workflow:
https://github.com/eclipse-pass/pass-docker/actions/runs/4822154330/jobs/8589009757

There was an issue with the updating the pass version. The regex need the s to be escaped and the double quotes were added. This issue was resolved during the release.

`Run ./.github/actions/update-pass-version`
`Run sed -i "/^PASS_VERSION/s/.*/PASS_VERSION=$RELEASE/" .env`

Context for the failed workflow:
https://github.com/eclipse-pass/pass-docker/actions/runs/4821887233/jobs/8588378384

**Comment by jabrah** [comment]
The issues discussed here were fixed during the release process, so should not be an issue in the future.

There was one more issue that resulted in us proceeding with the manual release. It's actually a known issue, discussed in https://github.com/eclipse-pass/main/issues/521. While a temporary workaround was implemented, it was not merged prior to the release. I think it would still be valuable to merge this workaround, but https://github.com/eclipse-pass/main/issues/521 should be addressed for next release by updating the acceptance tests
