### ISSUE TITLE
Fix AWS JHU Pass Demo Authentication 

### ISSUE THREAD

**Issue by cshannon2** [eclipse-pass/main#537]
"The login service was unable to identify a compatible way to respond to the requested application. This is generally due to a misconfiguration on the part of the application and should be reported to the application's support team or owner."

**Comment by jabrah** [comment]
We've provided some updates to environment variables in the `oapass.org` demo. The one remaining issue is that we need to automatically remove the Postgres volume when redeploying, or else the data loader will introduce duplicate users
