### ISSUE TITLE
Resolve Ember 5.0 deprecation warnings

### ISSUE THREAD

**Issue by jaredgalanis** [eclipse-pass/main#546]
Follow the Ember deprecation workflow in resolving deprecations for Ember 5.0. 

You can read more about the workflow here: https://guides.emberjs.com/release/configuring-ember/handling-deprecations/#toc_deprecation-workflow

**Comment by dkriethof** [comment]
post 1.0.0

**Comment by jaredgalanis** [comment]
We should work through the list of silenced deprecations in `app/deprecation-workflow.js` one-by-one, changing the `handler` to `throw` and working to make the changes necessary so that there are no more build errors.

Note there are less deprecations here than expected, but there are other linting issues to deal with.
