### ISSUE TITLE
General submission (object) handling: we can actually delete objects now

### ISSUE THREAD

**Issue by jaredgalanis** [eclipse-pass/main#549]
- previously our API would not allow deletion of submission object so we always dereferenced an object when performing a "delete" action, this left objects orphaned, but still taking up resources in the system
- do we want to handle object deletion now that the API supports such a thing?
- we might consider what data preservation requirements we have and how this impacts deleting an object permanently

**Comment by dkriethof** [comment]
post 1.0.0

**Comment by jabrah** [comment]
Only applicable to Draft submissions

* Delete permission needs to be added to Submission obj (pass-core)
* Would need to handle deletion errors

**Comment by jabrah** [comment]
Should generally be a safe operation as long as submission deletion is restricted to only submissions from pass that are in draft state. In these cases, the UI sets the submission status to 'cancelled' but does not create a submission event, so notification services shouldn't be triggered. For a proxy submission, as soon as the preparer clicks the final Submit button to request approval from the authorized submitter, the submission state changes out of draft. 

The UI currently only passes a `cancelled` SubmissionEvent to the backend when a proxy submission is cancelled during the approval stage. In this case, we should maintain the current behavior and send the cancelled submission event to the backend.

Deleting the Publication and Submission can be rolled back if errors occur, but deleting the Files cannot, so submission deletion in the UI should:

- First ensure submission source is `pass` and submission status is `draft`
- Delete linked Publication only if no other submissions reference it
- For any attached Files, clear their `File.submission` field so we don't run into referential integrity errors
- Delete the Submission only if all of the above succeed

If an error occurs at any time up to this point, we can recover by
- Restore Publication, Submission
- Add `File.submission` property to the attached files again

If previous steps succeeded we can commit:
- Commit Publication, Submission deletions
- Destroy attached Files
