### ISSUE TITLE
Cleanup of  pass-support

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#562]
Generally look through the poms and make sure they are in good shape.
We should be using dependency versions from the main pom when possible.
See if the IT test setup can be consolidated in the pass-support pom. 
Move the docker plugin setup to pluginManagement.
Remove properties that are no longer used.

See if some of the tests that log a lot of output such as pass-journal-loader can be quieted.
Generally address warnings in the build process.

**Comment by tsande16** [comment]
Error during `mvn clean install` - From initial research it seems like there should only be 1 dependency for logging on the classpath. If slf4j and logback are both dependencies, this message will occur. 

`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation`

**Comment by dkriethof** [comment]
label as Tech debt

**Comment by rpoet-jh** [comment]
This work has been completed via other tickets.
