### ISSUE TITLE
Investigate deployment of deposit and notification services in pass-docker

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#582]
This depends on #578 and #580. Note that pass-core needs to be configured to start an ActiveMQ broker with tcp transport.

**Comment by rpoet-jh** [comment]
We need to also figure out deployment architecture in staging and prod.

**Comment by dkriethof** [comment]
deposit piece:
https://github.com/eclipse-pass/pass-docker/pull/344

**Comment by rpoet-jh** [comment]
This ticket has been resolved as follows:

- Solution for how to run deposit-services with dspace7 is in PR: https://github.com/eclipse-pass/pass-docker/pull/344
- Infrastructure architecture was determined in staging meeting with ticket created: https://github.com/eclipse-pass/main/issues/640
