### ISSUE TITLE
Point eclipse-pass.org/ to use the JHU AWS Pass Deployment

### ISSUE THREAD

**Issue by cshannon2** [eclipse-pass/main#583]
IP Address: 54.81.229.33

**Comment by cshannon2** [comment]
@aforward Please let me know if there are any additional pieces of information needed.

**Comment by aforward** [comment]
@cshannon2 here are the three URLs we have

| URL | Notes | Status
| --- | --- | --- |
| eclipse-pass.org | Github Pages HTML / CSS | running-locally (DNS not configured)
| demo.eclipse-pass.org | GitHub Self-Hosted Runner / Docker Compose | running
| nightly.eclipse-pass.org | GitHub Self-Hosted Runner / Docker Compose | running-locally (DNS not configured)

(documented https://github.com/eclipse-pass/main/blob/main/docs/infra/eclipseops.md)

So I don't think we should change the `eclipse-pass.org` record, let me know if we are replacing the current ones (and if so, then the current GH action runners will break unless updated), or if we want new URLS (e.g.  `aws-demo.eclipse-pass.org` and `aws-nightly.eclipse-pass.org`, or some other prefix like `jhu-`)

**Comment by aforward** [comment]
Here are the three options to choose from.

1) Adding AWS URLs (leaving EF Azure's untouched and adding new AWS / JHU urls)
2) Changing URLs (so moving EF Azure's URL to something like ef-demo/ef-nightly, or based on the architecture so azure-demo/azure-nightly)
3) Replaced with AWS URLs (so we would nuke the Azure EF servers in addition to changing the DNS records

**Comment by bbranan** [comment]
We're shooting for option 3 - replacing with AWS and shutting down the EF servers. As you note, the runners will need to be updated. Note that we'll also be retiring the "nightly" subdomain and using "dev" instead, though the dev environment doesn't exist just yet.

**Comment by aforward** [comment]
Ticket has been created (only I have access, but linking here so I can easily find it)

https://gitlab.eclipse.org/eclipsefdn/infrazilla/-/issues/1143

We would like the following changes

| Name | Type | Value | Notes
| --- | --- | --- | --- |
| dev.eclipse-pass.org | A | 54.81.229.33 | New record
| demo.eclipse-pass.org | A | 54.81.229.33 | Update to existing record

Both will be routed to AWS infrastructure (so yes the IPs are the same).  Once the new infrastructure is up and running I will separately request that our Azure "EC2" instances be terminated (but I'll hold off until it is confirmed that the AWS is setup and working).

**Comment by aforward** [comment]
```
13:08 ~/sin/projects/arrowmight (f/one-server-3-apps)$ ping demo.eclipse-pass.org
PING demo.eclipse-pass.org (54.81.229.33): 56 data bytes
Request timeout for icmp_seq 0
^C
--- demo.eclipse-pass.org ping statistics ---
2 packets transmitted, 0 packets received, 100.0% packet loss
14:09 ~/sin/projects/arrowmight (f/one-server-3-apps)$ ping dev.eclipse-pass.org
PING dev.eclipse-pass.org (54.81.229.33): 56 data bytes
```

**Comment by aforward** [comment]
@cshannon2 the IPs are set!!!

**Comment by cshannon2** [comment]
@aforward thanks for the update. We were able to confirm that the demo url correctly points to our AWS infrastructure. Closing this ticket.
