### ISSUE TITLE
Investigate and implement JHU branded public pages

### ISSUE THREAD

**Issue by jaredgalanis** [eclipse-pass/main#587]
First attempt at pages is here: https://github.com/jhu-sheridan-libraries/pass-ui-public/pull/1

However, there is content on these pages that is relevant to Eclipse and should be removed (e.g. footer, references to Eclipse, etc).

Some investigation with the Scholarly Comms Group might need to be done to arrive at a final set of pages, but we might want to take a first stab at doing them on our own.

**Comment by kineticsquid** [comment]
@jaredgalanis Will we know enough to get a customization guide out of this exercise?

**Comment by dkriethof** [comment]
related to #652

**Comment by jaredgalanis** [comment]
related to https://github.com/eclipse-pass/main/issues/667
