### ISSUE TITLE
Add slack notifications for infra concerns

### ISSUE THREAD

**Issue by jaredgalanis** [eclipse-pass/main#594]
- we discussed adding a slack notification for when pass-acceptance-tests fail (esp impt for the nightly run that we might otherwise miss)
- but also add things like PR openings/merges just to generally keep better track of thigns

**Comment by kineticsquid** [comment]
@jaredgalanis I don't recall how this is done. Do we have the pieces of infra in place and/or do we need help from the Eclipse IT team?

**Comment by bbranan** [comment]
We may need assistance from Eclipse IT to enable things on the GitHub side. See: https://github.com/integrations/slack

**Comment by jaredgalanis** [comment]
Yes it does appear we'll need help from someone that has the required permissions.

![Image](https://github.com/eclipse-pass/main/assets/6305935/7d31107a-83ad-45a2-8194-7c652221eef6)

**Comment by kineticsquid** [comment]
@jaredgalanis I'll poke on this. It may just require a helpdesk ticket.

**Comment by kineticsquid** [comment]
@jaredgalanis You need to create a helpdesk ticket for this: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues. When you do, can you tag me on it?

**Comment by jaredgalanis** [comment]
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3341

**Comment by jaredgalanis** [comment]
Waiting for the Eclipse help desk's response

**Comment by jaredgalanis** [comment]
note that since this integration command needs to be run from the slack workspace i suspect we’ll either need @kineticsquid or @aforward to have the correct permissions so that you can run the command or we’ll need to add someone else from the eclipse side to this slack workspace with the correct Github permissions to run the command

**Comment by jaredgalanis** [comment]
Closing as pass-dev-notifications and pass-ci channels have been setup. we may want to adjust them over time but the principal work here is done.

For context on what was added to what channel:

https://eclipse-pass.slack.com/archives/C035MNLRD44/p1688590097743099
