### ISSUE TITLE
Come up with a plan for handling AWS credentials

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#599]
Several components of PASS optionally can use AWS services and need corresponding credentials. Currently pass-core uses the same credentials for S3 and for SQS and is given them via environment variables.

Would it be better to split credentials out per service? Should we keep using environment variables?

**Comment by steven-exarcos** [comment]
@markpatton @rpoet-jh 

The EC2 instance itself has a role which would ostensibly be given whatever permissions it needs, rather than more than one set of credentials.   This would also hold true if pass-core were to move into ECS.

There 'should' not be any reason to have AWS IAM credentials passed as env variables because of the service role.

**Comment by rpoet-jh** [comment]
> The EC2 instance itself has a role which would ostensibly be given whatever permissions it needs, rather than more than one set of credentials. This would also hold true if pass-core were to move into ECS.
> 
> There 'should' not be any reason to have AWS IAM credentials passed as env variables because of the service role used by the compute resource.

@markpatton @steven-exarcos This ticket was created pretty long ago before we actually had deployed PASS in the new AWS architecture.  And yes, we use IAM Service Roles for granting permissions to AWS resources in AWS.  We are not using IAM access keys for any AWS resource access for deployed PASS components.

The only case where we use AWS access keys is for local testing in pass-docker where we use localstack to simulate AWS services.  However, the configuration we have in pass-docker for local env is sufficient for local testing purposes I would say.

I'd say this ticket can be closed given these points.  WDYT?

**Comment by steven-exarcos** [comment]
Agreed.

**Comment by markpatton** [comment]
@rpoet-jh Makes sense. Closed.
