### ISSUE TITLE
Investigate using ZAP

### ISSUE THREAD

**Issue by rpoet-jh** [eclipse-pass/main#610]
I would like to test PASS using the ZAP UI to test PASS appSec, and then at some point investigate incorporating it into our CI pipeline.

https://www.zaproxy.org/

**Comment by kineticsquid** [comment]
@rpoet-jh Do you have the necessary GH authority to configure this. If you're going to need the EF IT team to configure stuff, create a ticket on the helpdesk queue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues

**Comment by rpoet-jh** [comment]
@kineticsquid Will do.  I think integrating into CI will be done within GH actions, so once my committer status comes through, it should be doable.  However, if we run into permission issues, I'll create a ticket with the EF IT team.  Thanks for the heads up.

**Comment by rpoet-jh** [comment]
Work done for ticket is as follows:

- Configured ZAP desktop to ajax spider scan and attack pass running locally.  Took a long time to get authentication/session management configured to work.  This is common issue while working with ZAP, and takes time to understand what ZAP is doing.
- Tried to configured ZAP desktop to ajax spider scan stage pass.  I was not able to get ZAP to authenticate PASS with JHU SSO.  The solution would require several scripts and tweaks, so I left this alone for now.  For stage, I did a manual test clicking on most links and buttons in PASS proxying through ZAP so ZAP records alerts.  No attack was run against stage though, just manual scanning.
- There were 33 security alerts found.  I reviewed those that were related to the /app and /data paths (I didn't include paths related to logging in).  I created tickets for the High and Medium Risk alerts, and one for Low Risk:
- https://github.com/eclipse-pass/main/issues/831
- https://github.com/eclipse-pass/main/issues/832
- https://github.com/eclipse-pass/main/issues/833
- https://github.com/eclipse-pass/main/issues/834
- https://github.com/eclipse-pass/main/issues/835
- https://github.com/eclipse-pass/main/issues/836
