### ISSUE TITLE
Features for manual testing

### ISSUE THREAD

**Issue by dkriethof** [eclipse-pass/main#617]
Enumerate all the features since will want to do manual testing to walk-through 

AC:

- User stories outlining the features a user should be able to navigate though (As a user I can log in using my JHU ID, As a user I can see all my grants, etc.) 
- Helpful steps for performing these functions (can help as a starting off point for user documentation)

**Comment by jabrah** [comment]
https://docs.google.com/document/d/1BpyH2Fzjzkvpe1rVEpb5nx6rLyr-C-jQfFf6Cr7_Ex0/edit?usp=sharing

**Comment by jabrah** [comment]
PR listing some historic use case documents and super high-level: https://github.com/eclipse-pass/main/pull/646

More fine grained feature breakouts forthcoming

**Comment by markpatton** [comment]
Done.
