### ISSUE TITLE
Recommend documentation systems for engagement w/ other institutions

### ISSUE THREAD

**Issue by dkriethof** [eclipse-pass/main#618]
Review/research various documentation systems for other institutions to be able to use to learn about PASS and how to implement for their institution.

Acceptance criteria:
Present several recommendations for documentation systems to use for the team to then discuss/decide upon

Reference:
https://github.com/eclipse-pass/main/issues/539

**Comment by dkriethof** [comment]
https://docs.google.com/presentation/d/1zb6J2hf6DfXqf9Wuu_F229OawUyYeGE0/edit?usp=drive_link&ouid=102870018102164937184&rtpof=true&sd=true

**Comment by tsande16** [comment]
After looking at all the different systems, we need to define a set of criteria for making a selection: https://github.com/eclipse-pass/main/issues/843
