### ISSUE TITLE
Create first outline/first draft of documentation for engagement w/ less technical users at external institutions.

### ISSUE THREAD

**Issue by dkriethof** [eclipse-pass/main#620]
Create an outline/first draft of documentation to be used in a more sales capacity/for less technical users at external institutions.

Ensure it includes:
What pieces need to get PASS in place
What are those pieces?

Blocked until decisions made from:
https://github.com/eclipse-pass/main/issues/618 and https://github.com/eclipse-pass/main/issues/619

Reference: https://github.com/eclipse-pass/main/issues/539

**Comment by tsande16** [comment]
This might be the next step after #891, #892 and #893. All three of these tickets are in review. We can look at these at our upcoming pass status meeting.

**Comment by dkriethof** [comment]
@tsande16 should we close this one too (like we did for #621) since all the newer tickets will cover this?

**Comment by tsande16** [comment]
@dkriethof Yes, this one should close as well.
