### ISSUE TITLE
Investigate outdated SSL issue in pass-docker

### ISSUE THREAD

**Issue by jaredgalanis** [eclipse-pass/main#625]

**Comment by dkriethof** [comment]
@rpoet-jh added ticket with Eclipse Foundation: ticket created: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3483

**Comment by rpoet-jh** [comment]
Valid certificate is now there for https://demo.eclipse-pass.org.

In JHU AWS demo env, created certificate, ALB, and target group containing EC2 instance running app.  Worked with EF to validate certificate and update DNS.
