### ISSUE TITLE
Create  GitHub Actions workflow to deploy notification-service to stage

### ISSUE THREAD

**Issue by dkriethof** [eclipse-pass/main#635]
Modify JHU AWS Deployment Python script to add additional actions to deploy the services

**Comment by rpoet-jh** [comment]
Started work on this now to ensure deployment of updated notification-service docker image to AWS to clarify any doubts.

**Comment by rpoet-jh** [comment]
New gh actions workflow has been implemented to deploy notification service, deposit services, and data loaders to AWS.

For notification and deposit service, the deployment script stops existing tasks so new tasks can start with new docker image.

Here is the workflow: https://github.com/jhu-library-devops/JHU-PASS-Deployment/actions/workflows/deployToAWS-ServicesAndDataLoaders.yml

You have to select Environment, Docker Image, and enter Docker tag.

**Comment by rpoet-jh** [comment]
The files added for this workflow are the following:

https://github.com/jhu-library-devops/JHU-PASS-Deployment/blob/main/.github/workflows/deployToAWS-ServicesAndDataLoaders.yml

https://github.com/jhu-library-devops/JHU-PASS-Deployment/blob/main/tools/aws_deploy_ecs_service.py
