### ISSUE TITLE
Change File uri field to a string

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#648]
Having the File contain a URI to the bytes making it up is problematic. The user interface and the backend may construct URIs for the file service with different hostnames that require different authentication to access. Instead the uri should should be a string identifying the upload to the file service and clients should know how to construct urls to access it.

**Comment by markpatton** [comment]
Or a less breaking change, the uri should be relative.

**Comment by dkriethof** [comment]
opening new ticket @markpatton
