### ISSUE TITLE
Manually load grant info into staging

### ISSUE THREAD

**Issue by dkriethof** [eclipse-pass/main#650]
Since we can't get to #623 right away, the plan is to manually load grant data for a 0.9.0 release for uses to log in and be able to see their grant information.

Create a fake grant file, using JHEDs for DRCC team + working group

**Comment by markpatton** [comment]
JHED ids to add for team: mpatton1,

**Comment by tsande16** [comment]
The endpoint to get an `EmployeeID` using the `HopkinsID` does not exist in the JHU internal API v2. To get the `EmployeeID`, upgrading to V3 will be needed to get the `EmployeeID`

For creating test accounts, using only the `HopkinsID` should work.

**Comment by tsande16** [comment]
@dkriethof Please add the JHED IDs for the individuals in the work group that need to be associated with a grant. Thanks!

**Comment by dkriethof** [comment]
@tsande16 shared the JHED IDs. Can we unblock this one?
