### ISSUE TITLE
Cleanup deposit service

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#657]
* Modules should be consolidated.
* Remove thread pool usage in deposit services.  This has been done already for some, but there was excessive use of thread pools when they are not needed.  See `ArchivingPackageStream` for example.  This code is executing in a service that is processing messages off a queue, so the deposit service is already async.  To add another thread pool is not needed and adds complexity to the service.
* Fix javadoc warnings
* Remove the CRI abstraction unless it is truly needed
* Tests can be simplified
* Revisit the aync behavior of the service
* Document the steps to add a new repository
* Make sure that logging of failure scenarios is appropriate.

**Comment by rpoet-jh** [comment]
These items have been completed via other tickets.
