### ISSUE TITLE
Pass Support Unit Test Failure on Windows 

### ISSUE THREAD

**Issue by tsande16** [eclipse-pass/main#660]
There is a unit test failure in Pass-Support. The `writeSampleMets` test fails with the following error:

`Suppressed: java.nio.file.FileSystemException: C:\Users\tsande16\AppData\Local\Temp\junit12966328472033608479\testSimple-mets.xml: The process cannot access the file because it is being used by another process`

Test runs successfully on Mac/Linux and the github checks. Likely this might have something to do with running on a Windows machine. 

Goal: Resolve failing unit test on a Windows machine.

**Comment by markpatton** [comment]
Looks like streams in the test aren't being closed.

**Comment by tsande16** [comment]
Some interesting things going on with this one:

- Try with resources doesn't work, same error persists.
- Deleting the files in a `@BeforeEach` or `@Afterall` doesn't work. The `@TempDir` still wants to clean up after closing the stream.
- Changed the cleanup policy on the `tempDir` @TempDir(cleanup = CleanupMode.NEVER): test will pass, but obviously the directory is still there.
- Changing the clean up policy to: @TempDir(cleanup = CleanupMode.ON_SUCCESS) yields a failing test, but the directory is still cleaned up?

**Comment by tsande16** [comment]
There may be something with `DspaceMetadataDomWriter` `write()` method that causes the file to no be released or still in process? 

I wrote a test method to test the `@TempDir` and it does not fail:
```
    @Test
    public void testWritingFileToTemp(@TempDir(cleanup = CleanupMode.ALWAYS) Path tempDir){
        java.io.File testFile = tempDir.resolve("testFile.xml").toFile();
        try (FileOutputStream fos = new FileOutputStream(testFile)){
            fos.write("test".getBytes());
        } catch (IOException e) {
            e.printStackTrace();
        }
    } 
```

**Comment by tsande16** [comment]
Solution: Both the file input and output streams needed to be closed. I was focusing on the output stream, I didn't even consider the `FileInputSteam` in the next lines.
