### ISSUE TITLE
make dashboard more personal

### ISSUE THREAD

**Issue by jaredgalanis** [eclipse-pass/main#665]
It’s not really obvious that this website is a personal dashboard. Several of the usual clues are missing, particularly in the language. Personal dashboards typically have sections for things like, “Recommended for Jessica,” “Keep watching this thing in your list,” and “your favorite things.” The headers and language are all very neutral, and the only indication that it is a personal dashboard is that my login name appears in the top right. I recommend revising the language and design in some key areas to provide easily-recognizable clues that this is a personal dashboard.

**Comment by dkriethof** [comment]
closing since this seems like a non-issue
