### ISSUE TITLE
[Deposit Services] Change repo credentials in repository.json to props

### ISSUE THREAD

**Issue by rpoet-jh** [eclipse-pass/main#671]
We need to change repo credentials in repository.json to props so the username and password can be externalized from json config file.

**Comment by jrmartino** [comment]
i'll need to do a little more testing, so far only able to get the SWORD connection to work without specifying a port. I'll see if that can work, else we'll need to change how repositories.json processes the address. one solution is to have a single property which contains both the host and its port, so we can pass it along. right now, specifying an empty port leaves a trailing : in the address (will test that too)

**Comment by tsande16** [comment]
Need to change the FTP environment variable username/password to pmc.ftp.user and pmc.ftp.password
