### ISSUE TITLE
Fix pass-nihms-loader ITs

### ISSUE THREAD

**Issue by rpoet-jh** [eclipse-pass/main#679]
The failsafe plugin was not declared in the child modules of `pass-nihms-loader` module in `pass-support`, so the ITs were not running when the maven verify was running.  I have fixed the POMs as part of work on 568 in the needed child modules, but the ITs are failing.  These need to be fixed.

**Comment by tsande16** [comment]
Switching tickets, so as a reminder to myself:

There is an issue with the old nihms-loader architecture and the new pass-data-client. The new pass-data-client doesn't generate an ID until the object is created by calling passClient.createObject(). Prior to this the nihms-loader would instantiate all the objects, package them in a SubmissionDTO and then perform the create/update operations once all objects were instantiated. The issue with this is that IDs are required during this process of generating the SubmissionDTO. Potentially these objects can be persisted once they are created, but some more investigation into this needs to be done as there is many steps to the process.

**Comment by tsande16** [comment]
Discussion with Mark:

In the `TransformAndLoadSmokeIT` there was an assertion for the number of submissions in this IT. In old pass it was 45, however after running all the other ITs that are running successfully, this is the only assertion that comes up with 37 submissions. This is being changed to 37, as it is reasonable to say that the same PMID PMCID and different PIs, should be on the same submission. 

This was changed:

`assertEquals(45, submissions.size());`

to:

`assertEquals(37, submissions.size());`

HOWEVER:

We need to test these changes in staging and see if the outcome is expected after the data migration and running all the loaders.
