### ISSUE TITLE
pass-core shib login user update should handle null values

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#682]
In pass-core-main/src/main/java/org/eclipse/pass/main/security/ShibAuthenticationFilter.java the update_pass_user method should handle the case of user values being null when doing the comparison

**Comment by rpoet-jh** [comment]
Here is the code in grant loader where the User object is created: https://github.com/eclipse-pass/pass-support/blob/30f3cbeae80a9b40047f8e1a63d10771d9427b64/pass-grant-loader/pass-grant-data/src/main/java/org/eclipse/pass/support/grant/data/JhuPassUpdater.java#L66

It then iterates through each locatorId to determine whether to update or create in PASS here: https://github.com/eclipse-pass/pass-support/blob/5309077b2267f883d6619c6bc053947bf38b4e8a/pass-grant-loader/pass-grant-data/src/main/java/org/eclipse/pass/support/grant/data/DefaultPassUpdater.java#L475
