### ISSUE TITLE
DOI lookup times out in staging env

### ISSUE THREAD

**Issue by jaredgalanis** [eclipse-pass/main#686]
In the submission workflow on the first step when a user enters a valid DOI the request to `https://stage.pass.jhu.edu/doi/journal?doi=10.1039%2Fc7an01256j` times out with a `504` status code.

![Image](https://github.com/eclipse-pass/main/assets/6305935/a2e77743-7988-4a63-b3c5-166279626bc6)

It appears that the `pass-auth` service is behaving in an expected manner forwarding the request to: `PASS_CORE_API_URL=http://pass-core:8080/` at this point: https://github.com/eclipse-pass/pass-auth/blob/2abb1672a700ff5ce14ff902b5ff3375f1fad1ee/src/config/proxies.ts#L88-L90

```
  app.all('/doi*', ensureAuthenticated, function (req: Request, res: Response) {
    apiProxy.web(req, res, { target: config.app.passCoreUrl });
  });
```

**Comment by markpatton** [comment]
The app makes a request like ```https://stage.pass.jhu.edu/doi/journal?doi=10.3352%2Fjeehp.2013.10.3```

**Comment by markpatton** [comment]
I can login to the staging environment and do the request directly to pass-core and it succeeds, but it takes a long time, 2 minutes and 46 seconds.

**Comment by markpatton** [comment]
The xref api returns immediately ```https://api.crossref.org/v1/works/10.3352%2Fjeehp.2013.10.3```

**Comment by markpatton** [comment]
Tested in loccal docker and the lookup of https://doi.org/10.3352/jeehp.2013.10.3 worked fine

**Comment by markpatton** [comment]
Turns out there needed to be indexes for issns. See linked pr.
