### ISSUE TITLE
Verify Permissions on DSpace Staging

### ISSUE THREAD

**Issue by tsande16** [eclipse-pass/main#701]
Currently the PASS service account to deposit into DSpace has permissions of `Admin` and `Submit` on the collection. Verify if using only the Submit permission will still allow the deposits from PASS.

**Comment by tsande16** [comment]
Jim did some testing in dspace over the weekend, and admin privileges are not required for submitting to dspace

@jrmartino will follow-up with Don on this.

**Comment by jrmartino** [comment]
Don will update the permissions for the PASS user on prod. Already updated and tested on stage, closing this ticket.
