### ISSUE TITLE
Bug: Checking the radio button stating "I have made an arrangement... will not submit my article as part of this process." still submits to PMC via PASS.

### ISSUE THREAD

**Issue by dkriethof** [eclipse-pass/main#727]
Chose radio button on Policies step that: "I have made (or intend to make) an arrangement with the publisher to deposit my article directly to MC and will not submit my article as part of this process."

Moving through the workflow it notes that my manuscript was deposited to PMC through PASS. Expectations would be that it just gets submitted to JScholarship.

![Image](https://github.com/eclipse-pass/main/assets/135133952/941dbb14-a9e4-4f21-985d-dd5fc382e010)

![Image](https://github.com/eclipse-pass/main/assets/135133952/b9643491-f069-45ea-b1a6-3bbf75a78de0)

![Image](https://github.com/eclipse-pass/main/assets/135133952/3065e794-0ed2-4371-a43f-fd38302f5606)

**Comment by jaredgalanis** [comment]
I have double checked the state of the of policies on the submission when using this radio and I think from a UI perspective the state is most likely correct (i.e. if you elect not to have the submission deposited to PMC then there is only a policy for JHU open access on the submission). So my guess is that there's something not being handled well in the API.

**Comment by markpatton** [comment]
It looks like the repositories are set on the submission by the repository service. Need to also take a look at effectivePolicies on Subission and see how that interacts.

**Comment by markpatton** [comment]
The policy service is ignoring the effectivePolicies property of the submission. It seems like when asked about the repositories for a submission, it should simply return the repositories of the effective policies.
