### ISSUE TITLE
Research spike: Workflow and feasibility of submission without a journal

### ISSUE THREAD

**Issue by dkriethof** [eclipse-pass/main#728]
Two use cases:

Users in the humanities departments cannot use PASS since they often do not have a journal associated w/ their work to put in the currently required journal field.

Users in the humanities departments cannot use PASS since their journal is not listed in the drop-down.

In order to make PASS useful for them, how can we remove this blocker in the most efficient/easiest way?

Some idea from our call included:

1. Options (no journal):
- Make journal field optional
- Include a option that says “no journal” or “n/a”

2.  If there is a journal, but not currently in the system
John: Need to check in UI and JSON Schemas if journal is expected.
Russ: Would also need to check the backend code to see if there are assumptions made
Could journal selection move after grant selection?

**Comment by markpatton** [comment]
Analysis and recommendation: https://docs.google.com/document/d/1AmrqFTbxtbefbI6otWbVkWonhD6aqambo8BS6jV9Yo0/edit?usp=sharing
