### ISSUE TITLE
Ensure that pass-ui handles File.uri having a different hostname

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#733]
File.uri may be an absolute uri with a hostname which the ui cannot resolve. The ui should should strip out the hostname and make a request using the path.

**Comment by jaredgalanis** [comment]
We decided to go ahead and make file URI's always relative.

`pass-ui` will perform whatever transforms are necessary to read a host into the URI for the purposes of allowing users to download files, but on save it will provide a relative URI starting with `/file/`. For example `/file/${file.uuid}/${encodeURIComponent(file.fileName)}` will likely be what constructs the URI for saving a file.

@msp will do what is necessary to make this possible in the backend as well.
