### ISSUE TITLE
DOI/manuscript service returns an empty manuscript

### ISSUE THREAD

**Issue by jaredgalanis** [eclipse-pass/main#741]
The UI is now guarding for this, but we should investigate why this is happening in the API at all.

**Comment by rpoet-jh** [comment]
@jaredgalanis @markpatton Looking at the code in `UnpaywallDoiService` which handles calls to the manuscript path, it loops over the `oa_locations` array and creates a Json manuscript object for each.  If the `url_for_pdf` is null, it sets `url` and `name` as null in the returned manuscript Json object.  

Based on unpaywall api docs, it is valid for `url_for_pdf` to be null.  I would say that based on this, `UnpaywallDoiService` appears to be doing the right thing.  If we don't want to display manuscripts from unpaywall that don't have a `url_for_pdf` we should filter them out on the UI as already being done.  We could also not include any manuscripts in the response if the `url_for_pdf` is null, but seems like that info may be useful in some other case.

**Comment by rpoet-jh** [comment]
We have decided to leave the `UnpaywallDoiService` code as is for now.  Closing.
