### ISSUE TITLE
Documentation and plan for cutover

### ISSUE THREAD

**Issue by dkriethof** [eclipse-pass/main#747]
- Document plan for cutover activity
- run-through plan using 1.0.0 release (pull from prod, put 1.0.0 in staging, follow cutover steps)
- run-through plan using 1.1.0 release

**Comment by markpatton** [comment]
Done. See https://jhulibraries.atlassian.net/wiki/spaces/PASS/pages/2250604556/Switching+Production+to+New+Pass
