### ISSUE TITLE
Update Help link once Help pages are posted on WordPress site

### ISSUE THREAD

**Issue by dkriethof** [eclipse-pass/main#754]
Once it is ready and live, we should update the link in the header that says, "Need help making a submission? Read our submission workflow [instructions ](https://github.com/eclipse-pass/main/blob/main/docs/user/README.md)." since those instructions seem pretty outdated and not very helpful for users.

**Comment by rpoet-jh** [comment]
This issue depends on https://github.com/eclipse-pass/main/issues/690

**Comment by dkriethof** [comment]
Will update this ticket once I have the WordPress site link

**Comment by rpoet-jh** [comment]
Moving this to blocked, waiting for link from wg.

**Comment by dkriethof** [comment]
Link is confirmed: https://pass.jhu.edu/guide

**Comment by rpoet-jh** [comment]
instructions link updated in stage and prod to https://pass.jhu.edu/guide
