### ISSUE TITLE
Show journal the user selected post-submission

### ISSUE THREAD

**Issue by dkriethof** [eclipse-pass/main#755]
Right now after a user does a submission, when they go back to either the submission list page or the detail for for a particular article, no where is what journal was related to the submission mentioned. This seems like an oversight in the first iteration of PASS.

We should add this info to both the final pre-submission summary and in the submission details.

**Comment by jaredgalanis** [comment]
Closed by https://github.com/eclipse-pass/pass-ui/pull/1235
