### ISSUE TITLE
Bug: Getting an error Policies step

### ISSUE THREAD

**Issue by dkriethof** [eclipse-pass/main#756]
Sometimes when I try to go through the workflow, I get this error. Not sure what the specific trigger is since it happens when just doing the normal testing things, and is intermittent.

![Image](https://github.com/eclipse-pass/main/assets/135133952/5cf4d61c-cfec-44b5-804a-51216862da9b)

**Comment by jaredgalanis** [comment]
Closed by https://github.com/eclipse-pass/pass-ui/pull/1224
