### ISSUE TITLE
Set user token for staging environment

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#759]
The staging environment needs to be configured with a user token key for generating user tokens.
See https://github.com/eclipse-pass/pass-core/tree/main/pass-core-user-service for the environment variable to set and how to generate they key.

**Comment by rpoet-jh** [comment]
Token generated.  Updated .eclipse-pass.JHUAWSstage_env to contain the `PASS_CORE_USERTOKEN_KEY` env var with the generated key.  Redeployed the app in stage to pick up new env.
