### ISSUE TITLE
Cannot update article title using Back button

### ISSUE THREAD

**Issue by dkriethof** [eclipse-pass/main#763]
Since we no longer allow editing on the Details page, I tried to use the Back button to go back in the workflow to the Basics step and update there.

I used the Back button, updated the article title, then clicked back through the workflow to the Details page, but am still seeing the old, original title (not the updated one). As a user, I would assume changing the title back at the start of the workflow/before submitting would update the title on the Details page.

**Comment by jaredgalanis** [comment]
https://github.com/eclipse-pass/pass-ui/pull/1234
