### ISSUE TITLE
Investigate adding SBOM creation into the PASS build process

### ISSUE THREAD

**Issue by dkriethof** [eclipse-pass/main#767]
What?
For all the PASS projects, we should investigate generating an Software Bill Of Materials (SBOM) and adding it to each project github repository.

From older ticket from EF: This link ([https://gitlab.eclipse.org/eclipsefdn/emo-team/sbom/-/blob/main/docs/sbom.adoc](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgitlab.eclipse.org%2Feclipsefdn%2Femo-team%2Fsbom%2F-%2Fblob%2Fmain%2Fdocs%2Fsbom.adoc&data=05%7C01%7Cdrietho1%40jh.edu%7C40a3ae52d3384c0922e408dbcab4eb76%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C638326650609752390%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sGnqWxS0dEfBGqE%2FLiEnj7w0E941Y%2FOUfJ0HYB9aX%2BE%3D&reserved=0)) is guidance from Eclipse about creating a SBOM (Software Bill of Materials) in a Maven-based Java project (as well as a Node-based project).

Why?
So it is clear what dependencies a project uses. This is especially important when reviewing dependencies for any security vulnerabilities within OS projects like PASS.

Here is a short article for Java projects, but same thing applies to npm projects. Any project that uses dependencies.

https://snyk.io/blog/create-sboms-java-maven-gradle/

How?
For java projects, we can checkout https://github.com/CycloneDX/cyclonedx-maven-plugin or maybe another maven plugin.

For npm projects, first one I found was https://docs.npmjs.com/cli/v10/commands/npm-sbom, but there may be others.

The SBOM generation should happen as part of the build process with latest version on main branch.

Acceptance Criteria
Make a decision on if we want to generate SBOM, come up with a plan to generate or implement if not huge effort.

**Comment by rpoet-jh** [comment]
This ticket is replacing this one: https://github.com/orgs/eclipse-pass/projects/4/views/2?filterQuery=sbom&pane=issue&itemId=67210443
