### ISSUE TITLE
Adjust funders/policies to match PMC-approved list

### ISSUE THREAD

**Issue by dkriethof** [eclipse-pass/main#786]
Contact at PMC confirmed this is the list to use, with some exceptions, listed below: https://www.ncbi.nlm.nih.gov/pmc/about/public-access/#partners

PASS should NOT support: DHS, NIST, or NASA
- Because of DHS policy, only DHS funded papers can only be accepted by PubMed from DHS
- NIST is similar to DHS
- NASA no longer deposits manuscripts in PMC

HHMI is still an active participant and PASS should still deposit to PMC for HHMI.

Please update the current deposit policies on PASS to add:
- Bill & Melinda Gates Foundation
- EPA
- HRA

and remove:
- NASA

also listed in first tab of this spreadsheet, and second tab shows new links/deposit policies:
https://docs.google.com/spreadsheets/d/1JyOhYAnfwrH3NKMCovw55sPn-yMtMYG2fibOO-p_MFc/edit#gid=1614637234

**Comment by markpatton** [comment]
Should create a quick script and/or document the process carefully for cutover. This will have to be repeated again.

**Comment by markpatton** [comment]
Also, I am pretty sure that EPA is the Environmental Protection Agency, but what is HRA?

**Comment by markpatton** [comment]
@dkriethof Ah got it. I didn't see the tabs.

**Comment by markpatton** [comment]
I cant find the Health Research Alliance in our list of funders anywhere.

**Comment by markpatton** [comment]
Done. Wrote notes in the cutover document.
