### ISSUE TITLE
Error when trying to cancel on multiple steps in the workflow (Grants, Policies, Files)

### ISSUE THREAD

**Issue by dkriethof** [eclipse-pass/main#789]
- In the workflow, on the Grants and Policies steps, when I hit Cancel I get the attached error message:

![Image](https://github.com/eclipse-pass/main/assets/135133952/37ce4e26-b34c-4e80-a8e6-78c957ac7ae2)

Also, even when I follow directions that says the page will reload if you hit OK, it actually take me back to the Basics step (though it is still populated with the information I had entered).

- Cancel button on the Files step doesn't throw an error; it just doesn't do anything

**Comment by jabrah** [comment]
A full page reload in the workflow will go all the way back to step 1. While not a good user experience, at least it's expected at the moment. We have a ticket scoped as part of a broader refactor to make the workflow properly resumable (#412)

**Comment by rpoet-jh** [comment]
The fix has been deployed to stage and prod.  Make sure to shift-refresh if already logged into either environment before testing.

**Comment by dkriethof** [comment]
looks good!
