### ISSUE TITLE
Stop/clean up AWS services in "old" PASS PROD

### ISSUE THREAD

**Issue by rpoet-jh** [eclipse-pass/main#792]
Once cutover is done to new AWS PASS PROD, we should stop AWS services in the old AWS PASS PROD account so we don't incur charges.  After some time, we should decommission the environment.

**Comment by dkriethof** [comment]
@rpoet-jh please ask Jeff is this is done - thanks!

**Comment by jgara** [comment]
ECS pass-prod environment in the AWS "ops" account (005956675899) was shutdown weeks ago -- so we are no longer incurring charges (or at least not at the rate we were). However the environment has not been deleted yet. If you guys are ok to do that now, please let me know. Sorry if you already gave the go-ahead and I missed it. Thanks, -jg

**Comment by rpoet-jh** [comment]
@jgara we have the go ahead to delete the resources in the old pass-prod AWS environment.

**Comment by steven-exarcos** [comment]
This is being track in ticket https://jhulibraries.atlassian.net/jira/software/c/projects/OPS/boards/173?selectedIssue=OPS-2641

**Comment by dkriethof** [comment]
@steven-exarcos I checked the associated Ops tickets and it is marked as "Stalled." Should I move this to blocked, and if so, can you add the reason why to the comments? Thanks!

**Comment by steven-exarcos** [comment]
> @steven-exarcos I checked the associated Ops tickets and it is marked as "Stalled." Should I move this to blocked, and if so, can you add the reason why to the comments? Thanks!

@dkriethof You can send this one to Done instead I think.  The cost-incurring components have been turned off. It's lingering as a Jira ticket for the clean up of non-cost-incurring items, which has its own tracking ticket, so the purpose of _this_ Issue is fulfilled.
