### ISSUE TITLE
Submission list page and submission detail page showing different statuses

### ISSUE THREAD

**Issue by dkriethof** [eclipse-pass/main#793]
Status on the submission list page shows "submitted," but when you click through to see the submission itself (submission detail page), it says deposit status is complete. Screenshots attached.

I would expect that the statuses match, and if the submission is completed, that the submission page also shows the related manuscript id.

Could be related to: https://github.com/eclipse-pass/main/issues/791

Also, I think this happened when JScholarship was behind the firewall, and then was maybe resubmitted so it might be related to it failing and then getting pushed through after?

![Image](https://github.com/eclipse-pass/main/assets/135133952/043e5322-89bf-4c32-81f1-9e55bf2513ef)

![Image](https://github.com/eclipse-pass/main/assets/135133952/c43793ed-0b34-43cc-ba8f-9c576f2589c8)

**Comment by rpoet-jh** [comment]
@dkriethof the status of the submission should be correct in stage now.
