### ISSUE TITLE
Investigate what “Policy Compliance” column on the Your Grants page is/where it comes from

### ISSUE THREAD

**Issue by dkriethof** [eclipse-pass/main#796]
Per attached screenshot, there is a "Policy Compliance" column on the Your Grants page. I can't really test to see if it is working properly since I am not sure what is used for/what triggers it.

![Image](https://github.com/eclipse-pass/main/assets/135133952/35b2a281-3487-4fbe-8d2d-47a492bd2a83)

**Comment by rpoet-jh** [comment]
Investigation was performed and found the status is derived by looking at the users associated submission deposits using the grant.  However, the status value was invalid.  A decision was made in slack to remove the Policy Compliance column for now.  If we decide this is something we want to display in the future, we need a larger discussion what determines that a grant is compliant with its associated policy.

**Comment by jaredgalanis** [comment]
Partially closed by: https://github.com/eclipse-pass/pass-ui/pull/1241
