### ISSUE TITLE
Remove download link on Files page if it doesn't actually download anything

### ISSUE THREAD

**Issue by dkriethof** [eclipse-pass/main#799]
On the Files page, if you have entered a pre-existing DOI, PASS gives the user a list of existing open access (OA) copies.

We show download links next to the articles names, but they seem to just link to the same place as the article link goes to, and not actually download anything. We should probably just remove the download icon since you cannot actually download from PASS.

Note: There may be some that work, as I only spot-checked a few random DOIs

![Image](https://github.com/eclipse-pass/main/assets/135133952/983ad8a8-846a-475c-bbdf-559025e347f2)

![Image](https://github.com/eclipse-pass/main/assets/135133952/9dd34676-a4a1-4036-b454-c507e2063945)

**Comment by jaredgalanis** [comment]
Some definitely do work, but I don't think we have a good way of knowing that in advance so let's just remove the link as you're staying.
