### ISSUE TITLE
Acceptance tests fail

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#800]
Acceptance tests currently fail on ` can walk through an nih submission workflow and make a submission - base case`.

**Comment by markpatton** [comment]
Fails in a different place on another run.

**Comment by jabrah** [comment]
Looks to me like it's caused by this UI change, which hasn't been accounted for in the acceptance tests yet: https://github.com/eclipse-pass/main/issues/402

**Comment by jabrah** [comment]
PR merged, rerunning tests in CI to confirm
