### ISSUE TITLE
Investigate how to detect or infer failure of a PMC submission

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#801]
Can the nihms loader do this by checking how long a deposit has gone without succeeding?

Suppose we detect a failure, what should happen?

**Comment by markpatton** [comment]
Note that the nihms bulk submission specification defines a set of error messages.

**Comment by markpatton** [comment]
These error messages go to an email address. 

Some example messages: 
```
The following file, uploaded on 2023-10-11, could not be accepted because it was found to be in an either invalid format or invalid directory: Nanometer-Scale Thermometry.pdf.

```

```
Package ID=nihms-native-2017-07_2021-06-24_21-06-31_9298c91e-aec0-45a4-8fb0-16ba59457664 for Manuscript ID 1718664 was submitted successfully.
```

**Comment by tsande16** [comment]
Compiling ideas from the slack channel:

Bill: "there are several action options that can be triggered by incoming email via SES: https://docs.aws.amazon.com/ses/latest/dg/receiving-email-action.html. Using Lambda would seem to be the most flexible and would allow for calling the PASS API. Of course, relying on email text to figure out status is pretty brittle. A simpler approach may be to trigger SNS and connect the topic to a slack channel that the team monitors."

ref: https://eclipse-pass.slack.com/archives/C14JBAT8C/p1698768012885039

Russ: "I was also looking at the spring integration option.  I see the benefit of going with spring integration is it keeps us somewhat decoupled from AWS for the integration.  We can investigate both options though and decide."

ref: https://eclipse-pass.slack.com/archives/C14JBAT8C/p1698768187036609

**Comment by tsande16** [comment]
@markpatton 

For more information and context:

This error message: `The following file, uploaded on 2023-10-11, could not be accepted because it was found to be in an either invalid format or invalid directory: Nanometer-Scale Thermometry.pdf.` was a test that I uploaded directly using filezilla to initially test the connection settings. 

The other two error message you mentioned above were old submissions that had been sitting there for sometime. I saw them initially when I logged into the FTP server. 

I think the new syntax for description which package failed/succeeded would look something like this: `Package ID=nihms-native-2017-07_2023-10-24_17-10-32_240467` where the last set of numbers after `2023-10-24_17-10-32` is the submission ID.

**Comment by markpatton** [comment]
Note that the ticket is to investigate if we can detect or infer failure.

**Comment by tsande16** [comment]
@markpatton so this would be detection prior to depositing to PMC?

**Comment by markpatton** [comment]
@tsande16 Detection or failure of deposit to the PMC

**Comment by markpatton** [comment]
Ok. It looks like all the error messages should include the package id which is determied by the uploaded package file name. We control that name currently. The code looks a bit odd in NihmsAssembler.java. It tries to add the submission id to the name, but falls back to a random uuid. It also includes the name and the spec in the file name. We can easily modify that to have the submission id. Then we can parse the package id to get the submission id.

**Comment by tsande16** [comment]
Yes, and then with the submission ID from the email that is sent, we can do either the two implementations mentioned above, spring integration or the AWS approach to parse the email for the submission ID.

**Comment by markpatton** [comment]
Just collecting info on a successful nihms deposit, the deposit object will get external ids like 
```
"PMC8293694", "NIHMS1718664"
```

**Comment by tsande16** [comment]
Adding google drive URL here: https://docs.google.com/document/d/15wSrRvNwRnoE9xagNgkm9ZlqMfXw7Kc-H8vBUiEizS4/edit#heading=h.w3jm8nsukie3

**Comment by tsande16** [comment]
Follow-up email from Pierce: https://docs.google.com/document/d/1x9Wgd0zrf3elYwbqkomZNWi7rehlPuXNJtsunzJ9rEo/edit
