### ISSUE TITLE
Clarify how PASS supports external submission requirements

### ISSUE THREAD

**Issue by dkriethof** [eclipse-pass/main#815]
1) PASS lists NIH plus Dept of Ed and USAID as required repositories. While they may be required from a funder perspective, the copy on the page makes it sound like PASS will do a submission for _all_ the funders (not just NIH).

"Based on the grant and journal information provided, you are required to submit your manuscript to the repositories below**. PASS will help you to create submissions for these in the following steps:**

2) Files step doesn't mention anything about it nno-NIH funders, even though it says in the prior step that the following steps will help you create submissions.

3) Final submission step _does_  make external submissions clear, but a user has to go through multiple steps to see that.

![Image](https://github.com/eclipse-pass/main/assets/135133952/88a88f03-8f97-4560-a490-ba9548daa226)

![Image](https://github.com/eclipse-pass/main/assets/135133952/f7e8cea9-d577-4c7e-9778-063772443d15)

![Image](https://github.com/eclipse-pass/main/assets/135133952/f29ca6ce-f241-42d1-a016-0b1170819411)

**Comment by jabrah** [comment]
Need some feedback on redesign and messaging. Some text in the screenshots won't be quite right, so I have also included the new text descriptions 

## Repository step
![Pasted image 20231220141742](https://github.com/eclipse-pass/main/assets/5167587/4cdaef3d-451a-4dbb-aae0-419b630da545)

* Web-link repositories separated into their own section with description
> You are required to make a submission to the following repositories because PASS is unable to make submissions to them on your behalf. PASS will provide links to these repositories with a summary of the information you've entered for your PASS submission before finalizing the submission. You will need to follow those links in order to make a submission in those separate repository systems.

## Files step
![image](https://github.com/eclipse-pass/main/assets/5167587/cdd765c0-f103-4acb-9419-1217d94cf0c5)

* Add new paragraph about web-link repositories, if the submission needs to go to one or more web-link repositories
  * This description should not be present if no web-link repositories are not associated with the submission
  * The direct reference to ERIC in this example may change according to the specific web-link repositories associated with the submission. So if the USAID repository is required, but not ERIC, then the message will mention USAID
> PASS cannot integrate with some external repositories, such as Educational Resources Information Center (ERIC). In these cases, you will have to create a submission in their repositories. They may have different requirements about the files that are submitted.


## Review step
![PASS_review_step_web-link_repo_notice_redesign](https://github.com/eclipse-pass/main/assets/5167587/4e858958-191f-45eb-b64e-9fa306289338)

* Web-link repo section moved to top
* Exclamation triangle icon changed to red to draw attention, section title
	* Hidden when all web-link repos are clicked
* Web-link repository links bolded
	* Unbolded on click?
* Submit button disabled by default if web-link repos are present
	* Enabled when all web-link repos clicked
	* Should replace the toast (popup) notice
* Web-link section description:
> You are required to visit the following web portal to submit your manuscript directly because PASS cannot submit to these systems on your behalf. Metadata displayed here can be used to aid in your submission progress.

**Comment by dkriethof** [comment]
@jabrah The screenshots and language all look good to me! Once it is all up on staging, I will give it another review and we can make any small tweaks if needed.

**Comment by jabrah** [comment]
This includes some changes related to #820. Should review that ticket after to see if its requirements are met with this set of changes
