### ISSUE TITLE
Design of Nihms email integration

### ISSUE THREAD

**Issue by dkriethof** [eclipse-pass/main#826]

**Comment by rpoet-jh** [comment]
I propose the following design to listen and process emails from nihms:

- Use Spring Integration Mail Support https://docs.spring.io/spring-integration/reference/mail.html
- Add needed spring configuration objects to setup channel to listen for emails to pass-support/pass-deposit-services.  The service for processing emails will run in pass-deposit-services in the single instance job running process running existing submission/deposit status jobs.
- Add NihmsEmailService class to pass-support/pass-deposit-services.  This new class will be responsible for:
	- Receiving MimeMessage from spring integration email
	- Extract submission/deposit information from email
	- Map email contents to deposit state update
	- Post DepositUpdate message with state update to deposit queue
	- Update DepositListener to handle nihms deposit status update
		- Currently, DepositTaskHelper does nothing for nihms deposit status updates

By going with this approach, we will accomplish:

- Email integration support for nihms status updates will be provided by deposit-services out of the box, no additional infrastructure/code is needed other than email inbox for institution.
- Email integration implementation is handled by spring, we just have to implement the configuration to enable the communication channels.
- All pieces of integration code are in pass-deposit-services, so it makes it easier/possible to write tests and ITs.

**Comment by tsande16** [comment]
@rpoet-jh Your proposal sounds good! It will definitely be beneficial for other institutions, using the built-in spring integration is a major plus too.

**Comment by markpatton** [comment]
@rpoet-jh I think using the spring mail support with the existing deposit service is a nice approach.

**Comment by rpoet-jh** [comment]
I think we have a good enough consensus with the proposed design.  I have created the implementation issue https://github.com/eclipse-pass/main/issues/856.  Closing this issue.
