### ISSUE TITLE
Update Hopkins logo

### ISSUE THREAD

**Issue by dkriethof** [eclipse-pass/main#830]
Update log on the PASS app to be the standard JHU logo - see attached.

![Image](https://github.com/eclipse-pass/main/assets/135133952/87db3d8d-0e28-48ff-ae0c-d1c287f3d9aa)

**Comment by dkriethof** [comment]
Blocking since it seems we have not landed on which logo to use yet.

**Comment by dkriethof** [comment]
Per Jessica: I have changed out the logo on the WP site. The file is attached for you to use on the PASS app. I confirmed with Heather that the PASS site is not in compliance with the guidelines we’d have to meet to use the enterprise logo, so the JHU logo is the one to go with, at least for now.

**Comment by tsande16** [comment]
Removed the 1.2.0 milestone since it's JHU related.
