### ISSUE TITLE
[Security - med] Missing Anti-clickjacking Header zap alert

### ISSUE THREAD

**Issue by rpoet-jh** [eclipse-pass/main#834]
Risk: Medium

https://pass.local/app/
https://pass.local/app/auth-callback

The response does not include either Content-Security-Policy with 'frame-ancestors' directive or X-Frame-Options to protect against 'ClickJacking' attacks.

Modern Web browsers support the Content-Security-Policy and X-Frame-Options HTTP headers. Ensure one of them is set on all web pages returned by your site/app.
If you expect the page to be framed only by pages on your server (e.g. it's part of a FRAMESET) then you'll want to use SAMEORIGIN, otherwise if you never expect the page to be framed, you should use DENY. Alternatively consider implementing Content Security Policy's "frame-ancestors" directive.

**Comment by rpoet-jh** [comment]
I checked in pass-docker local and PASS JHU stage and prod, and I see the X-Frame-Options response header set to DENY from our server. This was probably resolved with the re-architecting of proxy into pass-core. Setting this as Done.

Some of the js/css resources on our index.html page don't set the X-Frame-Options response header, but these servers are not ours and we have no control over them. js/css resources like jquery, bootstrap, handlebars, etc.

**Comment by rpoet-jh** [comment]
@msp to confirm, https://pass.local/app/auth-callback is no longer a valid URL, right?

**Comment by markpatton** [comment]
Yes. This was handled when we updated spring security in pass-core.
