### ISSUE TITLE
[Security - low] Investigate Strict-Transport-Security Header Not Set zap alert

### ISSUE THREAD

**Issue by rpoet-jh** [eclipse-pass/main#837]
Risk: Low

Many urls in /app and /data

HTTP Strict Transport Security (HSTS) is a web security policy mechanism whereby a web server declares that complying user agents (such as a web browser) are to interact with it using only secure HTTPS connections (i.e. HTTP layered over TLS/SSL). HSTS is an IETF standards track protocol and is specified in RFC 6797.

Ensure that your web server, application server, load balancer, etc. is configured to enforce Strict-Transport-Security.

Not sure if this applies to pass since we do enforce HTTPS on the load balancer.  However, we should investigate to be sure.

**Comment by markpatton** [comment]
@rpoet-jh Agreed.
