### ISSUE TITLE
The toplevel module version commit should only happen if the release succeeds

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#846]
Currently the release action updates the toplevel module version and then calls the release plugin. This can cause problems if the release fails because the commit will have been made. The version update should be done as part of the release plugin work if possible. It is updating the submodule versions.

**Comment by jabrah** [comment]
We should probably also allow the release plugin to push (version bump) commits and tags itself, instead of pushing manually

**Comment by markpatton** [comment]
For release of child modules of main, pass-core and pass support it works like:
  1. Update parent dependency to release version
  2. Commit pom change
  3. Release plugin prepare
  4. Release plugin perform in release profile
  5. Update parent pom to new dev version (submodules should be at dev version)
  6. Commit pom change and push all changes
  7. Create docker image for dev by running maven deploy with release profile
  8. Push git tags
  9.  Push docker images

**Comment by markpatton** [comment]
build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing
