### ISSUE TITLE
Investigate code coverage reports to PASS repos

### ISSUE THREAD

**Issue by rpoet-jh** [eclipse-pass/main#868]
What?
Investigate options to add code coverage reports to PASS repositories.  First focus on backend repos (Java based), and then check pass-ui if it would be beneficial.

Why?
Having code coverage reports is fairly standard on code repositories.  It would be good to know how well our code is covered by tests.

How?
https://about.codecov.io/ is widely used and can cover and java and javascript.  However, there may be other options.

Acceptance Criteria
Code coverage should run as part of an open PR status check.  It would be good to add a badge on the repo as well.

Related Issues

**Comment by tsande16** [comment]
May want to look into open source options. Codecov could also have agreements with open source projects.

**Comment by tsande16** [comment]
[Research Analysis](https://docs.google.com/document/d/1_Bs_MIAYBIHf86B7v90kcJEMPpitdtpojD2gCWQxRIY/edit?usp=sharing)

**Comment by tsande16** [comment]
Outcome from PASS Status meeting: 

Tim to create two tickets re: code coverage:
- Work to set up JaCoCo
- Discuss SonarQube vs. CodeCov (after JaCoCo is implemented)
