### ISSUE TITLE
Grant loader CSV pilot analysis

### ISSUE THREAD

**Issue by rpoet-jh** [eclipse-pass/main#899]
What?
We need to do two things related to the grant loader CSV pilot:

- Investigate impact of award_number being null on Grant.
- Set up being able to load a CSV of grant data locally and show what it looks like in PASS running locally.  We should use the CSV file we received from Oregon, ask Daryl for link to data (**don't link the sheet to this issue since this issue is public**).

Why?
To move the pilot forward and answer questions.

How?
As described

Acceptance Criteria
As described

Related Issues

**Comment by rpoet-jh** [comment]
Re: "Investigate impact of award_number being null on Grant."

@markpatton Searched for usage in pass-support/pass-core/pass-ui.  Didn't find anything stopping a grant with no award number.  Grant will be available in UI and submissions can be done based on testing locally (created grant with null awardNumber and award status pre-award).  I also noticed that submission can be done on grants that are terminated.  I wonder if this is correct, but it is a different question than the original question.

Found this in UI: https://github.com/eclipse-pass/pass-ui/blob/965f8694bb70e0550b6887d2cad50527798a7187/app/models/grant.js#L5 saying it is required, but I don't see any issues happening if not there.  @jaredgalanis can you confirm UI doesn't require Grant.awardNumber?

**Comment by rpoet-jh** [comment]
@markpatton In order to run grant loader locally against pass-docker running locally, here are the steps:

1. Create dir named grantloadertest
2. cd grantloadertest
3. touch connection.properties
4. touch grant_update_timestamps
5. touch policy.properties

6. create env.list file containing in grantloadertest:

APP_HOME_ENV=/data/grantloader
PASS_CORE_URL=http://localhost:8080
PASS_CORE_USER=<pass-core-username> (value from .eclipse-pass.local_env PASS_CORE_BACKEND_USER)
PASS_CORE_PASSWORD=<pass-core-password> (value from .eclipse-pass.local_env PASS_CORE_BACKEND_PASSWORD)

7. Copy test.csv to grantloadertest dir

[test.csv](https://github.com/eclipse-pass/main/files/14336571/test.csv)

9. In pass-docker, modify docker-compose.yml:

For pass-core, add:
     ports:
      - "8080:8080"

10. Start pass-docker in local mode: `docker compose -f docker-compose.yml -f eclipse-pass.local.yml up -d --no-build --quiet-pull`

11. Once pass-docker is up and loader container is done running, login with nih-user to pass.local
12. Go to Grants tab

13. In another terminal, cd to dir above grantloadertest

14. execute `docker run -it -v ./grantloadertest:/data/grantloader --env-file ./grantloadertest/env.list --network host ghcr.io/eclipse-pass/jhu-grant-loader:1.4.0-SNAPSHOT -a load /data/grantloader/test.csv`

15. Once done, in pass.local, click on Dashboard then Grants links to show Sample NIH Grant loaded.

Notes:

- If grant csv contains new Funders, you should figure out PASS policy ID and put the funder local key to policy ID mapping in policy.properties (i.e. funder_local_key=pass_policy_id)

**Comment by markpatton** [comment]
I was able to load in the test data using the instructions. 

But very strangely running the grant loader image with the volume mount causes the Java in the container to fail for me with a class not found exception. Removing the volume mount lets Java run successfully. I tried changing the mount location without success.

 In any case I just ran the grant loader jar directly and it worked fine.

**Comment by markpatton** [comment]
Working perfectly. I think I figured out why the volume mounts weren't working. I had a typo in env.list which was somehow messing up the processing.
