### ISSUE TITLE
Create a GitHub deployment action with does a complete deployment

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#908]
# What? 

Create a GitHub deployment action which does a complete PASS deployment of a given version to a given environment. The action should also run tests against the new deployment. 

The action should deploy snapshots versions to staging on pr merge.

Documentation should be updated and the existing deployment actions cleaned up.

# Why?

Completely deploying PASS requires triggering several GitHub actions. It should be simpler. Also automated updates to staging will make sure we are testing current work.

# How?

This should be able to build off of the existing actions.

# Acceptance Criteria 

Demonstrate a snapshot being deployed to staging.

# Related Issues

* Depends on #909

**Comment by rpoet-jh** [comment]
Automated Stage Deployment Proposal

From what I read, there is no clean publish/subscribe mechanism in github actions across repos/org.  Github Webhook requires creation of a webhook in source repo (e.g. pass-core) with a URL pointing to consumer (e.g. JHU-PASS-Deployment).  This is reverse of what it should be for our case, pass-core should have an endpoint JHU-PASS-Deployment can subscribe to without pass-core having knowledge about subscribers.

The only other option I saw was using `repositor_dispatch` or `workflow_dispatch`, which has the same issue.  The publishing repo must know about the subscribing repo to make these calls.

Given this, I propose we do the following to implement automatic stage deployments as PRs are merged in eclipse-pass repos:

- Create a scheduled github action workflow named `DeploymentPoller` in JHU-PASS-Deployment that executes every 30 minutes (or whatever frequency we decide).  
- When `DeploymentPoller` executes, it will do the following:
	- Checkout eclipse-pass/main to get the release version (it will be the snapshot version)
	- Get the sha for each of the PASS docker images in ghcr
	- Get the sha for each of the PASS docker images in AWS ECR
	- If the sha values are different, execute the appropriate deployment to stage using existing deployment workflows.
- A couple changes will be needed in pass-core/ui deployment:
	- Change pass-core/pass-ui deployment script to push pass-core/pass-ui images to AWS ECR with release tag like deposit/notification/data loader deployment does
	- Change pass-docker to pull images from AWS ECR for pass-docker running in AWS

**Comment by rpoet-jh** [comment]
The following items have been completed for this ticket:

-`Staging Deployment` github workflow is in JHU-PASS-Deployment.  This workflow is running on a schedule: runs at ~20 after each hour from 6a to 8p. If you want to deploy any PASS docker image to stage, you can manually run the workflow.  It will check all docker images and deploy the latest snapshot tagged docker image if not already deployed.  Note the two workflows we used to use Publish to SNS Topic: Triggers Deployment to AWS and Deploy PASS Services and Data Loaders to ECS AWS can no longer be run from the github UI.  These workflows are used by Staging Deployment , and Staging Deployment is the workflow to use now to do Staging deployments.  

-`Production Deployment` github workflow is in `JHU-PASS-Deployment`.  This workflow is meant to run manually.  The Release Version is required when running this workflow.  This workflow will deploy all the docker images tag with Release Version to the PASS AWS production environment.

-Changes were made in the `pass-jhu-aws` repo so the pass app images (pass-core/pass-ui/auth/proxy) are now pulled from AWS ECR.
