### ISSUE TITLE
Develop a Documentation Style Guide

### ISSUE THREAD

**Issue by tsande16** [eclipse-pass/main#912]
# What? 

Develop a Documentation Style Guide of the team.

# Why?

It's important that our documentation is aligned in one voice and is consistent in formatting, style, and conventions. This will make the writing flow well and be easily understood by the reader.

# Acceptance Criteria 

A written Documentation Style Guide.

**Comment by tsande16** [comment]
Another style guide to consider when developing our own documentation style guide. This one mostly relates to markdown, but there are a few points we might want to consider.

- Prefer lists to tables
- Strongly prefer Markdown to HTML
- Inline and code blocks
- Use informative Markdown link titles

https://google.github.io/styleguide/docguide/style.html

**Comment by tsande16** [comment]
Some other interesting bits of style guide here as well. Talking about using inclusive language: 

https://support.apple.com/guide/applestyleguide/general-guidelines-apd91d6c2458/1.0/web/1.0

**Comment by cshannon2** [comment]
The style guide has been completed and reviewed. Closing this issue.
