### ISSUE TITLE
Review and add sample grant CSV to PASS to share via local machine

### ISSUE THREAD

**Issue by dkriethof** [eclipse-pass/main#924]
**What?**
Like we did for University of Oregon, add sample grant data to PASS on dev local machine to share in demo.

Notes from UVA to keep in mind below - may need to spin off into another ticket?

"We still need to have a more detailed conversation with our Office of Sponsored Programs to determine what values they can give us access to – we are cautiously optimistic that we will be able to get most of the fields in the template you shared.

For some of the fields, we have an approximate match, rather than an exact match to what you are listing. For instance, our dump doesn’t appear to have the actual Grant Title, but rather a shorthand title that UVA OSP assigns to the grant for their internal use. Of course, this is the title we presumably want for all of the internal work we would be doing, but it wouldn’t match anything in the NIH or NSF systems, so we will need to explore if the original title can be revealed to us as well, when we talk to OSP."

**Why?**
We want as much sample data from our community institutions as possible to see how the simple grant data loader will work. Would like ot be able to share PASS demo w/ group in **Feb 28** meeting.

**How?**

**Reference**
Link to data [here](https://docs.google.com/spreadsheets/d/1xvS_nobkL_si89M66_XQmoJ_VdC_uzyJ/edit?usp=sharing&ouid=111557914426764136619&rtpof=true&sd=true
)

**Related tickets**
n/a

**Comment by rpoet-jh** [comment]
@dkriethof I looked at the linked sheet, and there is no sample CSV from UVA.  I think there are just questions they have that need more discussion.

**Comment by dkriethof** [comment]
Ack, you are correct. That's what I get for not looking at the spreadsheet first. Guess for now we can just use this for discussion in our call, but nothing to do from a dev perspective so will just close.

**Comment by dkriethof** [comment]
@rpoet-jh Wait, check out the second tab... is that something we can use?

**Comment by rpoet-jh** [comment]
@dkriethof it doesn't appear so to me.  I think that is analysis they were doing, but it definitely is not in the required grant CSV format.

**Comment by dkriethof** [comment]
Bummer. Ok, just something to be discussed then. Thanks!
