### ISSUE TITLE
Report syntax errors when loading grant data

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#935]
# What? 

When loading grant data, detailed information about syntax errors should be reported such that problems can be easily debugged. If a value in the CSV does not match the expected format, that value, the entire line, and the expected format should be reported.

# Why?

It is currently hard to figure out errors in the CSV.

# How?

# Acceptance Criteria 

Demonstrate that common problems like date errors are reported.

# Related Issues

**Comment by rpoet-jh** [comment]
As part of this, we should make the date/timestamp consistent and somewhat flexible if possible.

**Comment by rpoet-jh** [comment]
We should change the program that if there are any errors loading at least one row, then the system should exit with code 1 in the end.  In other words, the grant loader should load all the jobs it can, but exit with code 1 with one or more of the rows fail for some reason so we know the load wasn't clean.
