### ISSUE TITLE
Investigate nihms deposit that was set to accepted in PROD

### ISSUE THREAD

**Issue by rpoet-jh** [eclipse-pass/main#936]
Investigation of nihms deposit in PROD to determine how it was set to accepted even though nihms sent an email that the manuscript had an issue:

nihms deposit, it has a nihms-id value: "depositStatus":"accepted","depositStatusRef":"nihms-id:1968297"
[4:46](https://eclipse-pass.slack.com/archives/C14JBAT8C/p1709156814699689)
either came from email or nihms loader i guess?

```
You can see the deposits and repository copies here: https://app.pass.jhu.edu/data/deposit?filter=submission.id==249539&include=repositoryCopy
There are deposits to JScholarship and NIHMS.

There does seem to be an additional problem. The deposit to NIHMS has a status of accepted which must be wrong given the message above. I'm not sure how that status could have gotten set to accepted. We will have to debug.

Mark

On Wed, Feb 28, 2024 at 3:53 PM Mark Patton <[mark.patton@gmail.com](mailto:mark.patton@gmail.com)> wrote:
This is the submission:

https://app.pass.jhu.edu/data/submission/249539

Apparently it is missing some required metadata about authors. The metadata does include author information. But perhaps not exactly what they wanted. We will have to work directly with them to fix it up and also try to understand if there was anything PASS could have done to help.

Mark

On Wed, Feb 28, 2024 at 3:22 PM Russell Poetker <[rpoetke1@jh.edu](mailto:rpoetke1@jh.edu)> wrote:
Not a test from me.
From: Bill Branan <[bbranan@jhu.edu](mailto:bbranan@jhu.edu)>
Sent: Wednesday, February 28, 2024 3:13 PM
To: PASS <[PASS@jh.edu](mailto:PASS@jh.edu)>
Subject: Re: Complete title page requested for NIHMS submission
 
Is this a test, or a real submission?
From: [nihms-help@ncbi.nlm.nih.gov](mailto:nihms-help@ncbi.nlm.nih.gov) <[nihms-help@ncbi.nlm.nih.gov](mailto:nihms-help@ncbi.nlm.nih.gov)>
Sent: Wednesday, February 28, 2024 2:44 PM
To: pass-nihms <[pass-nihms@jh.edu](mailto:pass-nihms@jh.edu)>; PASS <[PASS@jh.edu](mailto:PASS@jh.edu)>
Subject: Complete title page requested for NIHMS submission
 
"Exploring HIV disease indicators at MDR-TB treatment initiation in South Africa" (NIHMS1968297)

Dear Johns Hopkins University,

In reviewing the above-listed manuscript, we've found that a complete title page containing the title, author name(s) and affiliation(s), and corresponding author contact information was not provided. We are, therefore, unable to proceed with the processing of this manuscript for PubMed Central at this time.

I have moved the manuscript back to a state where you can upload files. To access the manuscript record, please log in to [https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nihms.nih.gov%2F&data=05%7C02%7Cbbranan%40jhu.edu%7C88cab11879f64121915f08dc3895c72e%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C638447463148181630%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=GZb4GkSERn6dzeF3hQsVwIXiaSkLmKXGxOaLljzvynQ%3D&reserved=0](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nihms.nih.gov%2F&data=05%7C02%7Crpoetke1%40jh.edu%7Cb6c7d7bde5fb430091d508dc389fe40c%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C638447506573963569%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=I%2BL7NdL3aLa3HgLebY%2FNzxRrA0EdwYxDd6TRWMU%2Byv4%3D&reserved=0) and click on the manuscript title in the Needs Your Attention filter of your manuscript list.

Thank you,

The NIHMS Team
NTCSR5

**Comment by markpatton** [comment]
What happened is that the email service set the status of the Deposit to ACCEPTED. Somewhat confusingly (inconsistently with CopyStatus and SubmissionStatus), ACCEPTED is used by PASS to indicate that a deposit to a repository has been completed and is available. When all of a submissions deposits are ACCEPTED, a submission status is set to COMPLETE. So then the submission status for this submission was set to COMPLETE, which is wrong. Instead the email service should keep the deposit status as SUBMITTED when a deposit to NIHMS is accepted into the NIHMS pipeline. Then the submission status will be kept as submitted and won't be updated to COMPLETE until the nihms loader sets the deposit status to ACCEPTED.

We should update the deposit status and the submission status of the for this particular submission and deposit both to SUBMITTED.

We should change the email service not to set the deposit status to ACCEPTED when there is an email indicating success.

**Comment by markpatton** [comment]
Thinking about if the submission shows up in PACM as in process, the deposit and submission status should be updated appropriately so let's give it a few days and see what happens.

**Comment by markpatton** [comment]
To see all the objects: https://app.pass.jhu.edu/data/deposit?filter=submission.id==249539&include=repositoryCopy,submission.publication

The nihms deposit moved to in process and is now in embargo. (In JScholarship, it is in embargo as well.)
The deposit has its status updated to SUBMITTED. The submission status stayed as COMPLETE instead of changing to SUBMITTED. This may be because COMPLETE is a terminal state, the status code is hard to interpret.
