### ISSUE TITLE
Initiate Documentation Review Spreadsheet

### ISSUE THREAD

**Issue by tsande16** [eclipse-pass/main#947]
# What? 

Create a Documentation Review spreadsheet that will assist with tracking our documentation review process.

# Why?

This will help keep tracking of what each person is reviewing, the documents that are completed, and documents that need further review.

# How?

Spreadsheet with the following fields: Document Name,Location,Category,Status,Reviewer1,Reviewer2,Reviewer3,Status,Notes

# Acceptance Criteria 

Spreadsheet containing all the names and locations of documents to review.

**Comment by tsande16** [comment]
Waiting on consensus of the team. Developed new documentation review plans with @cshannon2 and will want these reviewed before more development on this tracking spreadsheet, in case there are an major changes.

- Current state: Wrote python script to get document names from Google drive API. This will be used to prepopulate the spreadsheet.
- Will need link to the google document as well as the author.

**Comment by cshannon2** [comment]
This looks good to me. Good to close.
