### ISSUE TITLE
Pre-process Documentation (2nd half) 

### ISSUE THREAD

**Issue by tsande16** [eclipse-pass/main#949]
# What? 

Pre-process second half of the documents in the Documentation Review Process spreadsheet. Archive any documents that are no longer relevant to the documentation corpus.

# Why?

Preprocessing the documents will make it easier for the whole team to review.

# Acceptance Criteria 

First half of the spreadsheet if updated with information detailing the category of the document and if it was archived or not.

# Related Issues

  * #947 is the spreadsheet to track preprocessing

**Comment by dkriethof** [comment]
@cshannon2 should this be moved to Done?
