### ISSUE TITLE
Fix stale ember auth session cookie

### ISSUE THREAD

**Issue by rpoet-jh** [eclipse-pass/main#974]
During the production 1.6.0 deployment, we noticed the `ember_simple_auth-session` cookie was not clearing even after closing the browser or shift-refresh the tab.  This caused an issue with the pass auth consolidation after logging in in chrome.

Mark found this SO describing the fact that some browsers are not respecting the session scope of the cookie and hanging onto them longer than they should: https://stackoverflow.com/questions/10617954/chrome-doesnt-delete-session-cookies

We should look to validate the `ember_simple_auth-session` cookie in pass-ui to ensure it is still valid

**Comment by markpatton** [comment]
I wonder if, in addition to making sure we validate the cookie, we should also just set a reasonable timeout?
